# Inicialização

In [1]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor
import torch.optim as optim
from torchmetrics.functional.classification import multiclass_f1_score
from sklearn.metrics import f1_score, confusion_matrix

import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import copy
from copy import deepcopy
from tqdm import tqdm
import time
import os
from sklearn.cluster import KMeans
from scipy.spatial import distance
from scipy.signal import find_peaks, sosfiltfilt, butter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device

In [3]:
actis = ['climbingdown', 'climbingup', 'jumping', 'lying', 'running', 'sitting', 'standing', 'walking']
posis = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
users = ['proband' + x for x in np.arange(1,16).astype(str)]

In [4]:
# data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz')
# Xdata = data['Xdata']
# ydata = data['ydata']
# pos = np.where(np.diff(ydata[:,0])==-6)[0]
# pos = np.insert(pos, 0, 0)
# pos = np.insert(pos, len(pos), len(ydata))
# yu = np.zeros_like(ydata[:,0])
# for i in range(len(pos)-1):
#     yu[pos[i]:pos[i+1]] = i
# J = 150
# fs = 50
# T0_loaded = pd.read_csv('T0_values.csv')
# T0 = T0_loaded['T0'].values.reshape(-1, 1)
# Vm = np.mean(Xdata, axis=1)
# Xm = Xdata - np.mean(Xdata, axis=1, keepdims=True)
# En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

In [5]:
data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xycort.npz')
Xcort = data['Xcort']
ycort = data['ycort']
J = 150
fs = 50
data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\f0est.npz')
f0est = data['f0est']
Vm = np.mean(Xcort, axis=1)
Xm = Xcort - np.mean(Xcort, axis=1, keepdims=True)
En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

# Pré-processamento dados RealWorld Chang

In [7]:
def recortar_janelas(acc, J, passo):
    N = acc.shape[0]
    Nj = (N - J) // passo + 1
    janelas = np.zeros((Nj, J, 3))
    for i in range(Nj):
        janelas[i] = acc[i * passo:i * passo + J]
    return janelas

In [4]:
actis = ['climbingdown', 'climbingup', 'jumping', 'lying', 'running', 'sitting', 'standing', 'walking']
posis = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
users = ['proband' + x for x in np.arange(1,16).astype(str)]

In [ ]:
pasta = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\Dataset\\realworldcsvs\\'
J = 150
Xdata = []
ydata = []
for user in tqdm(users):
    for i, pos in enumerate(posis):
        for j, act in enumerate(actis):
            files = os.listdir(pasta+user+'\\acc\\')
            inds = [(file.find(act)>-1) and (file.find(pos)>-1) for file in files]
            if np.array(inds).any():
                ind = inds.index(True)
                acc = pd.read_csv(pasta+user+'\\acc\\'+files[ind]).values[:,2:]
                janelas = recortar_janelas(acc, J, J)
                rotulos = np.full((janelas.shape[0], 2), [i, j], dtype=int)
                Xdata.append(janelas)
                ydata.append(rotulos)
Xdata = np.concatenate(Xdata, axis=0)
Xdata = Xdata/20
ydata = np.concatenate(ydata, axis=0)
Xdata.shape, ydata.shape

100%|██████████| 15/15 [00:45<00:00,  3.02s/it]

((151486, 150, 3), (151486, 2))

In [ ]:
# Vamos salvar os dados em um arquivo .npz para facilitar o carregamento posterior
np.savez('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz', Xdata=Xdata, ydata=ydata)

In [21]:
data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz')
Xdata = data['Xdata']
ydata = data['ydata']
pos = np.where(np.diff(ydata[:,0])==-6)[0]
pos = np.insert(pos, 0, 0)
pos = np.insert(pos, len(pos), len(ydata))
yu = np.zeros_like(ydata[:,0])
for i in range(len(pos)-1):
    yu[pos[i]:pos[i+1]] = i

In [ ]:
T0 = []
for x in tqdm(Xdata):
    x = x - np.mean(x, axis=0, keepdims=True)
    cor = [np.sum(x*x, axis=0)]
    for i in range(1, x.shape[0]):
        cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
    cor = np.array(cor).sum(axis=1)
    peaks, _ = find_peaks(cor)
    if len(peaks) > 0:
        T0.append(peaks[cor[peaks].argmax()])
    else:
        T0.append(0)
T0 = np.array(T0).reshape(-1, 1)

In [10]:
px.histogram(np.array(actis)[ydata[:, 1].astype(int)])

In [11]:
px.histogram(np.array(posis)[ydata[:, 0].astype(int)])

## Recorte das pausas de atividades de energia

In [22]:
cont = np.zeros((15, 7, 8))
for u in range(15):
    for i in range(7):
        for act in range(8):
            inds = (yu==u) & (ydata[:,0]==i) & (ydata[:,1]==act)
            cont[u,i,act] = np.sum(inds)

In [ ]:
u = 7
act = 1
J = 150
aux = []
lim = min(cont[u,:,act]).astype(int)
if lim == 0:
    lim = np.partition(cont[u,:,act], 1)[1].astype(int)
for p in range(7):
    inds = (ydata[:,1]==act) & (yu==u) & (ydata[:,0]==p)
    if np.any(inds):
        aux.append(Xdata[inds].reshape(-1,3)[:lim*J,:])
aux = np.concatenate(aux, axis=1)
px.line(aux)

In [ ]:
cortes = {(0,0): [[400, 25000]],
          (0,1): [[450, 26850]],
          (0,2): [[150, 4200]],
          (0,4): [[150, 30300]],
          (0,7): [[300, 31650]],
          (1,0): [[450, 24000]],
          (1,1): [[300, 24600]],
          (1,4): [[150, 16350]],
          (1,7): [[150, 30450]],
          (2,0): [[450, 27450]],
          (2,1): [[300, 29100]],
          (2,2): [[100, 5050]],
          (2,4): [[300, 12000], [19200, 37200]],
          (2,7): [[300, 33900]],
          (3,0): [[300, 11100]],
          (3,1): [[150, 13950]],
          (3,4): [[400, 9100], [22000, 26800], [32800, 36400], [46000, 50800]],
          (3,7): [[450, 30600]],
          (4,1): [[450, 30150]],
          (4,2): [[150, 4650]],
          (4,4): [[600, 10200], [12000, 18900], [27800, 35900], [49300, 55300]],
          (4,7): [[450, 34200]],
          (5,0): [[600, 24450]],
          (5,4): [[300, 12300], [13900, 32500]],
          (5,7): [[300, 31200]],
          (6,4): [[300, 20100], [23000, 36200]],
          (6,7): [[450, 30600]],
          (7,1): [[300, 25200], [44300, 56600]],
          (8,4): [[450, 6000], [16200, 39600]],
          (9,0): [[300, 21600]],
          (9,1): [[300, 21900]],
          (9,4): [[450, 30900]],
          (9,7): [[600, 31200]],
          (10,7): [[600, 32400]],
          (11,0): [[1200, 24150]],
          (12,1): [[300, 28800]],
          (13,4): [[600, 30600]],
          (14,0): [[600, 25200]],
          (14,1): [[150, 28500]],
          (14,4): [[150, 28200], [31100, 33200]],
          (14,7): [[450, 32400]]}

In [ ]:
par = []
for (u, act), vals in cortes.items():
    par.append([u, act])
par = np.array(par)

Xcort = []
ycort = []

for u in range(15):
    for act in range(8):
        if np.any(np.all(par == [u, act], axis=1)):
            aux = []
            lim = min(cont[u,:,act]).astype(int)
            if lim == 0:
                lim = np.partition(cont[u,:,act], 1)[1].astype(int)
            for p in range(7):
                inds = (ydata[:,1]==act) & (yu==u) & (ydata[:,0]==p)
                if np.any(inds):
                    aux.append(Xdata[inds].reshape(-1,3)[:lim*J,:])
            aux = np.concatenate(aux, axis=1)
            aux2 = []
            rotulos = []
            for p in range(7):
                vals = cortes[u, act]
                recortes = [aux[i:f,p*3:(p+1)*3] for i, f in vals]
                aux2.append(np.concatenate(recortes, axis=0).reshape(-1,150,3))
                rotulos.append(np.full((aux2[-1].shape[0], 3), [p, act, u], dtype=int))
            aux2 = np.concatenate(aux2, axis=0)
            rotulos = np.concatenate(rotulos, axis=0)
        else:
            inds = (ydata[:,1]==act) & (yu==u)
            aux2 = Xdata[inds]
            rotulos = np.concatenate([ydata[inds], yu[inds].reshape(-1,1)], axis=1)
        Xcort.append(aux2)
        ycort.append(rotulos)
Xcort = np.concatenate(Xcort)
ycort = np.concatenate(ycort)

In [45]:
np.savez('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xycort.npz', Xcort=Xcort, ycort=ycort)

## Calculando T0

In [ ]:
def harmonic_score(T, peaks, cor, tol=2):
    score = 0
    for k in range(1,8):
        target = k*T
        d = np.abs(peaks-target)
        if np.min(d)<=tol:
            p = peaks[np.argmin(d)]
            score += cor[p]
    return score

In [ ]:
sos = butter(N=6, Wn=10, btype='lp', fs=50, output='sos')
Xf = np.swapaxes(sosfiltfilt(sos, np.swapaxes(Xdata, 1, 2)), 1, 2)
T0 = []
for x in tqdm(Xf):
    x = x - np.mean(x, axis=0, keepdims=True)
    cor = [np.sum(x*x, axis=0)]
    for i in range(1, x.shape[0]):
        cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
    cor = np.array(cor).sum(axis=1)
    peaks, _ = find_peaks(cor)
    if len(peaks) > 0:
        scores = np.array([harmonic_score(T, peaks, cor) for T in peaks])
        T0.append(peaks[scores.argmax()])
    else:
        T0.append(0)
T0 = np.array(T0).reshape(-1, 1)

In [ ]:
T2 = np.copy(T0)
EnInds = (En.ravel()>1)
for u in range(14):
    for act in [0, 1, 4, 7]:
        inds = (ydata[:,1]==act) & (yu==u) & EnInds
        aux = T2[inds]
        km = KMeans(n_clusters=2, init = 'random')
        labels = km.fit_predict(aux.reshape(-1,1))
        if np.mean(aux[labels==0]) > np.mean(aux[labels==1]):
            aux[labels==1] = aux[labels==1] * 2
        else:
            aux[labels==0] = aux[labels==0] * 2
        T2[inds] = aux

## Calculando f0 de maneira mais precisa...

In [ ]:
u, act = 14, 7
inds = (ycort[:,1]==act) & (ycort[:,2]==u)
J = 150
fs = 50
L = 4
f0est = []
f0s = np.arange(1.7, 2.7, 0.01)
for janela in tqdm(Xm[inds]):
    erro = []
    for f0 in f0s:
        arg = np.outer(np.arange(J)/fs, np.arange(1,L+1)*2*np.pi*f0)
        C = np.cos(arg)
        S = np.sin(arg)
        theta = np.hstack((C, S))
        coefs = np.linalg.pinv(theta).dot(janela)
        recon = theta.dot(coefs)
        erro.append(np.sqrt(np.sum((janela - recon)**2)))
    f0est.append(f0s[np.argmin(erro)])

In [ ]:
inds = (ycort[:,1]==act) & (ycort[:,2]==u)
N = len(Xm[inds].reshape(-1,3))
N2 = len(T0[inds])
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.arange(N2)*N/N2/50, y=50/T0[inds].ravel(), mode='markers', name='T0'))
fig.add_trace(go.Scatter(x=np.arange(N2)*N/N2/50, y=np.array(f0est), mode='markers', name='f0est'))
fig.add_trace(go.Scatter(x=np.arange(N2)*N/N2/50, y=En[inds].ravel(), mode='markers', name='En'))
fig.add_trace(go.Scatter(x=np.arange(N)/50, y=Xm[inds].reshape(-1,3)[:,0], mode='lines', name='x'))
fig.add_trace(go.Scatter(x=np.arange(N)/50, y=Xm[inds].reshape(-1,3)[:,1], mode='lines', name='y'))
fig.add_trace(go.Scatter(x=np.arange(N)/50, y=Xm[inds].reshape(-1,3)[:,2], mode='lines', name='z'))
fig.show()

In [ ]:
# Faixa de busca do f0
faixa = {(0, 0): [0.5, 1.2],
         (0, 1): [0.5, 1.2],
         (0, 2): [1.5, 2.1],
         (0, 4): [0.9, 1.7],
         (0, 7): [0.6, 1.2],
         (1, 0): [0.6, 1.2],
         (1, 1): [0.5, 1.2],
         (1, 2): [1.5, 2.5],
         (1, 4): [0.9, 1.6],
         (1, 7): [0.7, 1.2],
         (2, 0): [0.5, 1.2],
         (2, 1): [0.5, 1.2],
         (2, 2): [1.5, 2.1],
         (2, 4): [0.9, 1.7],
         (2, 7): [0.7, 1.2],
         (3, 0): [0.5, 1.2],
         (3, 1): [0.5, 1.2],
         (3, 2): [1.5, 2.2],
         (3, 4): [0.9, 1.7],
         (3, 7): [0.7, 1.2],
         (4, 0): [0.5, 1.2],
         (4, 1): [0.6, 1.2],
         (4, 2): [1.7, 2.3],
         (4, 4): [0.9, 1.7],
         (4, 7): [0.7, 1.2],
         (5, 0): [0.6, 1.2],
         (5, 1): [0.6, 1.2],
         (5, 2): [1.7, 2.3],
         (5, 4): [0.9, 1.6],
         (5, 7): [0.6, 1.1],
         (6, 0): [0.6, 1.3],
         (6, 1): [0.6, 1.3],
         (6, 7): [0.6, 1.],
         (6, 4): [0.9, 1.7],
         (6, 2): [1.5, 2.3],
         (7, 0): [0.6, 1.3],
         (7, 1): [0.3, 1.1],
         (7, 7): [0.6, 1.2],
         (7, 4): [0.9, 1.6],
         (7, 2): [1.5, 2.3],
         (8, 0): [0.6, 1.2],
         (8, 1): [0.6, 1.2],
         (8, 7): [0.6, 1.2],
         (8, 4): [0.9, 1.5],
         (8, 2): [1.4, 2.3],
         (9, 0): [0.6, 1.3],
         (9, 1): [0.6, 1.3],
         (9, 7): [0.7, 1.3],
         (9, 4): [0.9, 1.6],
         (9, 2): [1.5, 2.3],
         (10, 0): [0.6, 1.3],
         (10, 1): [0.5, 1.2],
         (10, 7): [0.6, 1.2],
         (10, 4): [0.9, 1.5],
         (10, 2): [1.5, 2.5],
         (11, 0): [0.6, 1.2],
         (11, 1): [0.5, 1.2],
         (11, 7): [0.7, 1.2],
         (11, 4): [0.9, 1.5],
         (11, 2): [1.5, 2.5],
         (12, 0): [0.6, 1.3],
         (12, 1): [0.5, 1.2],
         (12, 7): [0.6, 1.3],
         (12, 4): [0.9, 1.52],
         (12, 2): [1.5, 2.5],
         (13, 0): [0.5, 1.3],
         (13, 1): [0.6, 1.3],
         (13, 7): [0.6, 1.3],
         (13, 4): [0.9, 1.7],
         (13, 2): [1.5, 2.2],
         (14, 0): [0.5, 1.3],
         (14, 1): [0.6, 1.2],
         (14, 7): [0.6, 1.2],
         (14, 4): [0.9, 1.6],
         (14, 2): [1.5, 2.7]}

In [ ]:
L = 4
f0est = []
for i, x in tqdm(enumerate(Xm)):
    if (ycort[i,2], ycort[i,1]) in faixa:
        [fmin, fmax] = faixa[ycort[i,2], ycort[i,1]]
        f0s = np.arange(fmin, fmax, 0.01)
        erro = []
        for f0 in f0s:
            arg = np.outer(np.arange(J)/fs, np.arange(1,L+1)*2*np.pi*f0)
            C = np.cos(arg)
            S = np.sin(arg)
            theta = np.hstack((C, S))
            coefs = np.linalg.pinv(theta).dot(x)
            recon = theta.dot(coefs)
            erro.append(np.sqrt(np.sum((x - recon)**2)))
        f0est.append(f0s[np.argmin(erro)])
    else:
        cor = [np.sum(x*x, axis=0)]
        for i in range(1, x.shape[0]):
            cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
        cor = np.array(cor).sum(axis=1)
        peaks, _ = find_peaks(cor)
        if len(peaks) > 0:
            f0est.append(50/peaks[cor[peaks].argmax()])
        else:
            f0est.append(10)
f0est = np.array(f0est).reshape(-1, 1)
np.savez('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\f0est.npz', f0est=f0est)

# Modelo Chang

## Definição do modelo de Chang

In [6]:
class ChangEncoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv1d(in_channels=3, out_channels=16, kernel_size=3)
        self.inst1 = nn.InstanceNorm1d(16, affine=True)
        self.drop1 = nn.Dropout(p=0.2)

        self.conv2 = nn.Conv1d(in_channels=16, out_channels=16, kernel_size=3)
        self.inst2 = nn.InstanceNorm1d(16, affine=True)
        self.drop2 = nn.Dropout(p=0.2)

        self.conv3 = nn.Conv1d(in_channels=16, out_channels=32, kernel_size=5, stride=4)
        self.inst3 = nn.InstanceNorm1d(32, affine=True)
        self.drop3 = nn.Dropout(p=0.2)

        self.conv4 = nn.Conv1d(in_channels=32, out_channels=32, kernel_size=3, stride=1)
        self.inst4 = nn.InstanceNorm1d(32, affine=True)
        self.drop4 = nn.Dropout(p=0.2)

        self.conv5 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=5, stride=4)
        self.inst5 = nn.InstanceNorm1d(64, affine=True)
        self.drop5 = nn.Dropout(p=0.2)

        self.conv6 = nn.Conv1d(in_channels=64, out_channels=100, kernel_size=5, stride=1)

        self.relu = nn.LeakyReLU(0.3)
        self.glap = nn.AvgPool1d(kernel_size=4)

    def forward(self, x):
        # (N,T,C) -> (N,C,T)
        x = x.transpose(1, 2)
        x = self.conv1(x)
        x = self.relu(x)
        x = self.inst1(x)
        x = self.drop1(x)

        x = self.conv2(x)
        x = self.relu(x)
        x = self.inst2(x)
        x = self.drop2(x)

        x = self.conv3(x)
        x = self.relu(x)
        x = self.inst3(x)
        x = self.drop3(x)

        x = self.conv4(x)
        x = self.relu(x)
        x = self.inst4(x)
        x = self.drop4(x)
        
        x = self.conv5(x)
        x = self.relu(x)
        x = self.inst5(x)
        x = self.drop5(x)
        
        x = self.conv6(x)
        x = self.relu(x)

        x = self.glap(x)
        x = x.flatten(start_dim=1)

        logits = x
        return logits

In [7]:
class ChangClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.densa = nn.Linear(in_features=100, out_features=8)

    def forward(self, x):
        logits = self.densa(x)
        return logits

## Avaliação

In [8]:
@torch.no_grad()
def evaluate(encoder, classifier, loader, loss_fn, device):
    encoder.eval()
    classifier.eval()
    total_loss = 0
    total_samples = 0
    y_true = []
    y_pred = []

    for X, y in loader:
        X = X.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        logits = classifier(encoder(X))
        loss = loss_fn(logits, y)
        total_loss += loss.item() * len(y)
        total_samples += len(y)
        pred = torch.argmax(logits, dim=1)
        y_true.append(y)
        y_pred.append(pred)

    y_true = torch.cat(y_true)
    y_pred = torch.cat(y_pred)
    f1 = multiclass_f1_score(y_pred, y_true, num_classes=8, average="macro").item()

    return total_loss / total_samples, f1

In [15]:
baselinef1 = np.zeros((7,7))
enc = ChangEncoder().to(device)
cla = ChangClassifier().to(device)
for i in range(7):
    state_dict = torch.load('..\\modelos\\baseline_encoder_'+posis[i]+'.pth', weights_only=True)
    enc.load_state_dict(state_dict)
    state_dict = torch.load('..\\modelos\\baseline_classifier_'+posis[i]+'.pth', weights_only=True)
    cla.load_state_dict(state_dict)
    for j in range(7):
        inds = ycort[:,0]==j
        X = Xcort[inds]
        y = ycort[inds][:,1]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
        X_test  = torch.tensor(X_test, dtype=torch.float32)
        y_test  = torch.tensor(y_test, dtype=torch.long)
        test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        baselinef1[i,j] = test_f1

In [16]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          85    85     52        47       32     39     45    27
chest         93    40     93        40       36     42     48    29
upperarm      91    49     64        91       26     16     62    52
forearm       88    33     35        43       88     33     38    38
waist         93    44     31        19       25     93     29    13
thigh         93    42     42        46       40     35     93    51
shin          93    14     36        39       28     12     37    93

## Treinamento

### Versão 0 (código antigo)

In [446]:
for posi in range(7):
    print(D[posi].iloc[:,:450].max().max(), D[posi].iloc[:,:450].min().min())

30.24330038394172 -27.905772938181507
29.10584118741573 -23.004128879086824
24.60838945941594 -23.373795119211223
27.10391661258158 -35.01022254108014
28.35246581033783 -32.08145329447701
25.498862803206386 -28.645988494886826
24.63936106304582 -26.89441535730718

In [447]:
posi = 0
# Vamos descartar a classe jump por ter poucas amostras
# E mudar o código de walking para 2 (era 7)
# aux = D[posi][D[posi]['activity code']!=2].replace({'activity code': 7}, 2)
# tarefas = np.array(['climbingdown', 'climbingup', 'walking', 'lying', 'running', 'sitting', 'standing'])
N = aux.shape[0]
X = aux.iloc[:,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
y = aux.iloc[:,-3].values

In [448]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

y_train = nn.functional.one_hot(torch.tensor(y_train), num_classes=8).to(torch.float32).to(device)
y_val = nn.functional.one_hot(torch.tensor(y_val), num_classes=8).to(torch.float32).to(device)
y_test = nn.functional.one_hot(torch.tensor(y_test), num_classes=8).to(torch.float32).to(device)

X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
X_val = torch.tensor(X_val, dtype=torch.float32, device=device)
X_test = torch.tensor(X_test, dtype=torch.float32, device=device)

In [449]:
[y_train.shape, y_test.shape, y_val.shape]

[torch.Size([15881, 8]), torch.Size([4412, 8]), torch.Size([1765, 8])]

In [450]:
encoder = ChangEncoder().to(device)
classif = ChangClassifier().to(device)

# torch.manual_seed(42)

loss_fn = nn.CrossEntropyLoss()

optimizer = optim.Adam(list(encoder.parameters()) + list(classif.parameters()), lr=0.001)
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

n_epochs = 20   # number of epochs to run
batch_size = 125  # size of each batch
batch_start = torch.arange(0, len(X_train), batch_size)

trainLoss = []
trainAcc = []
valLoss = []
valAcc = []

# training loop
for epoch in range(n_epochs):
    encoder.train()
    classif.train()
    with tqdm(batch_start, unit="batch", mininterval=0, disable=False) as bar:
        bar.set_description(f"Epoch {epoch}")
        for start in bar:
            # take a batch
            X_batch = X_train[start:start+batch_size,:,:]
            y_batch = y_train[start:start+batch_size,:]
            # forward pass
            y_pred = classif(encoder(X_batch))
            loss = loss_fn(y_pred, y_batch)
            # backward pass
            optimizer.zero_grad()
            loss.backward()
            # update weights
            optimizer.step()
            # print progress
            bar.set_postfix(loss=float(loss))
    # evaluate accuracy at end of each epoch
    encoder.eval()
    classif.eval()
    y_pred = classif(encoder(X_val))
    valLoss.append(float(loss_fn(y_pred, y_val)))
    labels = torch.nonzero(y_val)[:,1]
    labels_pred = torch.argmax(y_pred, dim=1)
    valAcc.append(multiclass_f1_score(labels_pred, labels, num_classes=8))
    y_pred = classif(encoder(X_train))
    trainLoss.append(float(loss_fn(y_pred, y_train)))
    labels = torch.nonzero(y_train)[:,1]
    labels_pred = torch.argmax(y_pred, dim=1)
    valAcc.append(multiclass_f1_score(labels_pred, labels, num_classes=8))

fig = go.Figure()

fig.add_trace(go.Scatter(y=valLoss, mode="lines", showlegend=True, name='validação'))
fig.add_trace(go.Scatter(y=trainLoss, mode="lines", showlegend=True, name='treino'))

fig.show()

Epoch 0: 100%|██████████| 128/128 [00:11<00:00, 11.16batch/s, loss=0.833]
Epoch 1: 100%|██████████| 128/128 [00:11<00:00, 11.27batch/s, loss=0.359]
Epoch 2: 100%|██████████| 128/128 [00:11<00:00, 11.27batch/s, loss=0.436]
Epoch 3: 100%|██████████| 128/128 [00:11<00:00, 10.91batch/s, loss=0.318]
Epoch 4: 100%|██████████| 128/128 [00:11<00:00, 11.06batch/s, loss=0.357]
Epoch 5: 100%|██████████| 128/128 [00:11<00:00, 11.03batch/s, loss=0.297]
Epoch 6: 100%|██████████| 128/128 [00:11<00:00, 11.14batch/s, loss=0.272]
Epoch 7: 100%|██████████| 128/128 [00:11<00:00, 11.08batch/s, loss=0.277]
Epoch 8: 100%|██████████| 128/128 [00:11<00:00, 11.16batch/s, loss=0.352]
Epoch 9: 100%|██████████| 128/128 [00:11<00:00, 10.92batch/s, loss=0.196]
Epoch 10: 100%|██████████| 128/128 [00:11<00:00, 11.00batch/s, loss=0.286]
Epoch 11: 100%|██████████| 128/128 [00:11<00:00, 10.98batch/s, loss=0.16]
Epoch 12: 100%|██████████| 128/128 [00:11<00:00, 10.97batch/s, loss=0.246]
Epoch 13: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.173]
Epoch 14: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.191]
Epoch 15: 100%|██████████| 128/128 [00:11<00:00, 11.03batch/s, loss=0.202]
Epoch 16: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.166]
Epoch 17: 100%|██████████| 128/128 [00:11<00:00, 11.08batch/s, loss=0.131]
Epoch 18: 100%|██████████| 128/128 [00:11<00:00, 10.77batch/s, loss=0.0931]
Epoch 19: 100%|██████████| 128/128 [00:11<00:00, 11.01batch/s, loss=0.113]
Epoch 20: 100%|██████████| 128/128 [00:11<00:00, 11.10batch/s, loss=0.0912]
Epoch 21: 100%|██████████| 128/128 [00:11<00:00, 11.13batch/s, loss=0.215]
Epoch 22: 100%|██████████| 128/128 [00:11<00:00, 11.11batch/s, loss=0.235]
Epoch 23: 100%|██████████| 128/128 [00:11<00:00, 11.25batch/s, loss=0.157]
Epoch 24: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0734]
Epoch 25: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.0418]
Epoch 26: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.292]
Epoch 27: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.112]
Epoch 28: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0454]
Epoch 29: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0862]
Epoch 30: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.0931]
Epoch 31: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.0874]
Epoch 32: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0495]
Epoch 33: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.0673]
Epoch 34: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.152]
Epoch 35: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0372]
Epoch 36: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.137]
Epoch 37: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.119]
Epoch 38: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.097]
Epoch 39: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0446]
Epoch 40: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.124]
Epoch 41: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.0573]
Epoch 42: 100%|██████████| 128/128 [00:11<00:00, 11.25batch/s, loss=0.0563]
Epoch 43: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.0577]
Epoch 44: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.126]
Epoch 45: 100%|██████████| 128/128 [00:11<00:00, 11.23batch/s, loss=0.033]
Epoch 46: 100%|██████████| 128/128 [00:11<00:00, 10.95batch/s, loss=0.104]
Epoch 47: 100%|██████████| 128/128 [00:11<00:00, 11.15batch/s, loss=0.0786]
Epoch 48: 100%|██████████| 128/128 [00:12<00:00, 10.47batch/s, loss=0.0801]
Epoch 49: 100%|██████████| 128/128 [00:11<00:00, 11.04batch/s, loss=0.0689]

In [14]:
def treinoModelo(dados):
        N = dados.shape[0]
        X = dados.iloc[:,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
        y = dados.iloc[:,-3].values
        X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=1, stratify=y)

        X_train, X_val, y_train, y_val = train_test_split(
                X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

        y_train = nn.functional.one_hot(torch.tensor(y_train), num_classes=8).to(torch.float32).to(device)
        y_val = nn.functional.one_hot(torch.tensor(y_val), num_classes=8).to(torch.float32).to(device)
        y_test = nn.functional.one_hot(torch.tensor(y_test), num_classes=8).to(torch.float32).to(device)

        X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
        X_val = torch.tensor(X_val, dtype=torch.float32, device=device)
        X_test = torch.tensor(X_test, dtype=torch.float32, device=device)

        encoder = ChangEncoder().to(device)
        classif = ChangClassifier().to(device)
        loss_fn = nn.CrossEntropyLoss()
        optimizer = optim.Adam(list(encoder.parameters()) + list(classif.parameters()), lr=0.001)
        n_epochs = 20   # number of epochs to run
        batch_size = 125  # size of each batch
        batch_start = torch.arange(0, len(X_train), batch_size)
        trainLoss = []
        trainAcc = []
        valLoss = []
        valAcc = []

        # training loop
        for epoch in range(n_epochs):
                encoder.train()
                classif.train()
                with tqdm(batch_start, unit="batch", mininterval=0, disable=False) as bar:
                        bar.set_description(f"Epoch {epoch}")
                        for start in bar:
                                # take a batch
                                X_batch = X_train[start:start+batch_size,:,:]
                                y_batch = y_train[start:start+batch_size,:]
                                # forward pass
                                y_pred = classif(encoder(X_batch))
                                loss = loss_fn(y_pred, y_batch)
                                # backward pass
                                optimizer.zero_grad()
                                loss.backward()
                                # update weights
                                optimizer.step()
                                # print progress
                                bar.set_postfix(loss=float(loss))
                # evaluate accuracy at end of each epoch
                encoder.eval()
                classif.eval()
                y_pred = classif(encoder(X_val))
                valLoss.append(float(loss_fn(y_pred, y_val)))
                labels = torch.nonzero(y_val)[:,1]
                labels_pred = torch.argmax(y_pred, dim=1)
                valAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))
                y_pred = classif(encoder(X_train))
                trainLoss.append(float(loss_fn(y_pred, y_train)))
                labels = torch.nonzero(y_train)[:,1]
                labels_pred = torch.argmax(y_pred, dim=1)
                trainAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))

        fig = go.Figure()
        fig.add_trace(go.Scatter(y=valLoss, mode="lines", showlegend=True, name='validação'))
        fig.add_trace(go.Scatter(y=trainLoss, mode="lines", showlegend=True, name='treino'))
        fig.show()

        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(y=valAcc, mode="lines", showlegend=True, name='validação'))
        fig2.add_trace(go.Scatter(y=trainAcc, mode="lines", showlegend=True, name='treino'))
        fig2.show()
        return encoder, classif

In [15]:
encoders = [None] * 7
classifs = [None] * 7
for posi in range(7):
    encoders[posi], classifs[posi] = treinoModelo(D[posi])

Epoch 0: 100%|██████████| 130/130 [00:01<00:00, 82.67batch/s, loss=1.25]
Epoch 1: 100%|██████████| 130/130 [00:01<00:00, 91.41batch/s, loss=0.943]
Epoch 2: 100%|██████████| 130/130 [00:01<00:00, 80.21batch/s, loss=0.847]
Epoch 3: 100%|██████████| 130/130 [00:01<00:00, 68.67batch/s, loss=0.817]
Epoch 4: 100%|██████████| 130/130 [00:01<00:00, 70.06batch/s, loss=0.764]
Epoch 5: 100%|██████████| 130/130 [00:01<00:00, 78.05batch/s, loss=0.776]
Epoch 6: 100%|██████████| 130/130 [00:01<00:00, 74.06batch/s, loss=0.724]
Epoch 7: 100%|██████████| 130/130 [00:01<00:00, 72.94batch/s, loss=0.699]
Epoch 8: 100%|██████████| 130/130 [00:01<00:00, 70.46batch/s, loss=0.73]
Epoch 9: 100%|██████████| 130/130 [00:01<00:00, 72.91batch/s, loss=0.662]
Epoch 10: 100%|██████████| 130/130 [00:01<00:00, 66.86batch/s, loss=0.612]
Epoch 11: 100%|██████████| 130/130 [00:02<00:00, 63.04batch/s, loss=0.646]
Epoch 12: 100%|██████████| 130/130 [00:01<00:00, 69.72batch/s, loss=0.682]
Epoch 13: 100%|██████████| 130/130 [00:02<00:00, 61.91batch/s, loss=0.641]
Epoch 14: 100%|██████████| 130/130 [00:02<00:00, 59.58batch/s, loss=0.666]
Epoch 15: 100%|██████████| 130/130 [00:02<00:00, 53.89batch/s, loss=0.701]
Epoch 16: 100%|██████████| 130/130 [00:02<00:00, 52.08batch/s, loss=0.609]
Epoch 17: 100%|██████████| 130/130 [00:02<00:00, 55.42batch/s, loss=0.597]
Epoch 18: 100%|██████████| 130/130 [00:02<00:00, 53.89batch/s, loss=0.612]
Epoch 19: 100%|██████████| 130/130 [00:02<00:00, 44.48batch/s, loss=0.622]

Epoch 0: 100%|██████████| 128/128 [00:02<00:00, 54.22batch/s, loss=1.42]
Epoch 1: 100%|██████████| 128/128 [00:01<00:00, 86.40batch/s, loss=1.24]
Epoch 2: 100%|██████████| 128/128 [00:01<00:00, 90.22batch/s, loss=1.13]
Epoch 3: 100%|██████████| 128/128 [00:01<00:00, 91.05batch/s, loss=1.11]
Epoch 4: 100%|██████████| 128/128 [00:01<00:00, 88.36batch/s, loss=1.11]
Epoch 5: 100%|██████████| 128/128 [00:01<00:00, 74.27batch/s, loss=1.06]
Epoch 6: 100%|██████████| 128/128 [00:09<00:00, 14.03batch/s, loss=0.981]
Epoch 7: 100%|██████████| 128/128 [00:13<00:00,  9.80batch/s, loss=1.06]
Epoch 8: 100%|██████████| 128/128 [00:08<00:00, 15.82batch/s, loss=1.04]
Epoch 9: 100%|██████████| 128/128 [00:07<00:00, 16.06batch/s, loss=1.04]
Epoch 10: 100%|██████████| 128/128 [00:07<00:00, 16.22batch/s, loss=0.867]
Epoch 11: 100%|██████████| 128/128 [00:08<00:00, 15.60batch/s, loss=1]
Epoch 12: 100%|██████████| 128/128 [00:07<00:00, 16.30batch/s, loss=0.872]
Epoch 13: 100%|██████████| 128/128 [00:07<00:00, 16.25batch/s, loss=0.882]
Epoch 14: 100%|██████████| 128/128 [00:07<00:00, 16.28batch/s, loss=0.99]
Epoch 15: 100%|██████████| 128/128 [00:07<00:00, 16.04batch/s, loss=0.896]
Epoch 16: 100%|██████████| 128/128 [00:07<00:00, 16.39batch/s, loss=0.895]
Epoch 17: 100%|██████████| 128/128 [00:07<00:00, 16.35batch/s, loss=0.805]
Epoch 18: 100%|██████████| 128/128 [00:07<00:00, 16.42batch/s, loss=0.799]
Epoch 19: 100%|██████████| 128/128 [00:07<00:00, 16.47batch/s, loss=0.769]

Epoch 0: 100%|██████████| 130/130 [00:08<00:00, 16.22batch/s, loss=1.53]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.29batch/s, loss=1.4]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.38batch/s, loss=1.23]
Epoch 3: 100%|██████████| 130/130 [00:08<00:00, 16.19batch/s, loss=1.17]
Epoch 4: 100%|██████████| 130/130 [00:08<00:00, 15.99batch/s, loss=1.09]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.39batch/s, loss=1.06]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.52batch/s, loss=0.992]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.54batch/s, loss=1.02]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.29batch/s, loss=0.978]
Epoch 9: 100%|██████████| 130/130 [00:08<00:00, 16.14batch/s, loss=0.928]
Epoch 10: 100%|██████████| 130/130 [00:08<00:00, 16.00batch/s, loss=0.929]
Epoch 11: 100%|██████████| 130/130 [00:08<00:00, 16.16batch/s, loss=0.934]
Epoch 12: 100%|██████████| 130/130 [00:08<00:00, 16.00batch/s, loss=0.886]
Epoch 13: 100%|██████████| 130/130 [00:08<00:00, 16.15batch/s, loss=0.906]
Epoch 14: 100%|██████████| 130/130 [00:08<00:00, 15.72batch/s, loss=0.889]
Epoch 15: 100%|██████████| 130/130 [00:10<00:00, 12.89batch/s, loss=0.846]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.57batch/s, loss=0.832]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.817]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.794]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.774]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.54batch/s, loss=1.31]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.948]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.777]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.704]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.669]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.613]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.628]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.607]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.588]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.57batch/s, loss=0.501]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.521]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.538]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.534]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.525]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.495]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.47batch/s, loss=0.514]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.49batch/s, loss=0.496]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.471]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.506]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.488]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=1.52]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.47batch/s, loss=1.14]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.50batch/s, loss=1.09]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=1.04]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.933]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.924]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.87]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.65batch/s, loss=0.865]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.83]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.854]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.796]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.782]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.52batch/s, loss=0.811]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.819]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.787]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.739]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.751]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.687]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.73]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.686]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=1.24]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=1.06]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.851]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.793]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.77]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.693]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.644]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.67]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.555]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.614]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.576]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.544]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.594]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.558]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.52]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.501]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.497]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.485]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.47]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.5]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.32batch/s, loss=0.916]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.732]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.679]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.619]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.545]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.504]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.539]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.466]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.465]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.404]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.53batch/s, loss=0.387]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.44batch/s, loss=0.401]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.438]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.46batch/s, loss=0.402]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.30batch/s, loss=0.437]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.48batch/s, loss=0.355]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.383]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.412]
Epoch 18: 100%|██████████| 130/130 [00:08<00:00, 16.06batch/s, loss=0.384]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.34batch/s, loss=0.397]

### Versão 1

In [56]:
inds = ydata[:,0]==0
X = Xdata[inds]
y = ydata[inds][:,1]
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

X_train = torch.tensor(X_train, dtype=torch.float32)
X_val   = torch.tensor(X_val, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.long)
y_val   = torch.tensor(y_val, dtype=torch.long)
y_test  = torch.tensor(y_test, dtype=torch.long)

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
val_loader = DataLoader(TensorDataset(X_val, y_val), batch_size=256, shuffle=False, pin_memory=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)

In [62]:
@torch.no_grad()
def evaluate(encoder, classifier, loader, loss_fn, device):
    encoder.eval()
    classifier.eval()
    total_loss = 0
    total_samples = 0
    y_true = []
    y_pred = []

    for X, y in loader:
        X = X.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        logits = classifier(encoder(X))
        loss = loss_fn(logits, y)
        total_loss += loss.item() * len(y)
        total_samples += len(y)
        pred = torch.argmax(logits, dim=1)
        y_true.append(y)
        y_pred.append(pred)

    y_true = torch.cat(y_true)
    y_pred = torch.cat(y_pred)
    f1 = multiclass_f1_score(y_pred, y_true, num_classes=8, average="macro").item()

    return total_loss / total_samples, f1

In [63]:
def train_model(train_loader, val_loader, device):
    encoder = ChangEncoder().to(device)
    classifier = ChangClassifier().to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=1e-3)
    n_epochs = 100
    history = {
        "train_loss": [],
        "val_loss": [],
        "train_f1": [],
        "val_f1": []
    }
    best_f1 = -1
    best_encoder = None
    best_classifier = None

    for epoch in range(n_epochs):
        encoder.train()
        classifier.train()
        running_loss = 0
        n_samples = 0
        bar = tqdm(train_loader)

        for X, y in bar:
            X = X.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            optimizer.zero_grad()
            logits = classifier(encoder(X))
            loss = loss_fn(logits, y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * len(y)
            n_samples += len(y)
            bar.set_description(f"Epoch {epoch+1}")
            bar.set_postfix(loss=loss.item())

        train_loss, train_f1 = evaluate(
            encoder,
            classifier,
            train_loader,
            loss_fn,
            device
        )

        val_loss, val_f1 = evaluate(
            encoder,
            classifier,
            val_loader,
            loss_fn,
            device
        )

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_f1"].append(train_f1)
        history["val_f1"].append(val_f1)

        print(
            f"Epoch {epoch+1:3d} | "
            f"Train F1={train_f1:.4f} | "
            f"Val F1={val_f1:.4f}"
        )

        if val_f1 > best_f1:
            best_f1 = val_f1
            best_encoder = deepcopy(encoder)
            best_classifier = deepcopy(classifier)

    return best_encoder, best_classifier, history

In [65]:
enc, cla, history = train_model(train_loader, val_loader, device)

Epoch 1: 100%|██████████| 125/125 [00:01<00:00, 81.84it/s, loss=1.12]

Epoch   1 | Train F1=0.4455 | Val F1=0.4241

Epoch 2: 100%|██████████| 125/125 [00:01<00:00, 81.44it/s, loss=0.916]

Epoch   2 | Train F1=0.5688 | Val F1=0.5400

Epoch 3: 100%|██████████| 125/125 [00:01<00:00, 71.19it/s, loss=0.845]

Epoch   3 | Train F1=0.6446 | Val F1=0.6322

Epoch 4: 100%|██████████| 125/125 [00:01<00:00, 63.27it/s, loss=0.637]

Epoch   4 | Train F1=0.7040 | Val F1=0.6920

Epoch 5: 100%|██████████| 125/125 [00:02<00:00, 48.85it/s, loss=0.654]

Epoch   5 | Train F1=0.6917 | Val F1=0.6863

Epoch 6: 100%|██████████| 125/125 [00:01<00:00, 78.80it/s, loss=0.533]

Epoch   6 | Train F1=0.7293 | Val F1=0.7185

Epoch 7: 100%|██████████| 125/125 [00:01<00:00, 82.22it/s, loss=0.782]

Epoch   7 | Train F1=0.7627 | Val F1=0.7615

Epoch 8: 100%|██████████| 125/125 [00:01<00:00, 89.27it/s, loss=0.554]

Epoch   8 | Train F1=0.7821 | Val F1=0.7742

Epoch 9: 100%|██████████| 125/125 [00:01<00:00, 85.96it/s, loss=0.551]

Epoch   9 | Train F1=0.8021 | Val F1=0.7996

Epoch 10: 100%|██████████| 125/125 [00:02<00:00, 51.37it/s, loss=0.48]

Epoch  10 | Train F1=0.7973 | Val F1=0.7789

Epoch 11: 100%|██████████| 125/125 [00:01<00:00, 64.60it/s, loss=0.5]

Epoch  11 | Train F1=0.8206 | Val F1=0.8030

Epoch 12: 100%|██████████| 125/125 [00:01<00:00, 67.59it/s, loss=0.544]

Epoch  12 | Train F1=0.8260 | Val F1=0.7918

Epoch 13: 100%|██████████| 125/125 [00:04<00:00, 29.26it/s, loss=0.476]

Epoch  13 | Train F1=0.8363 | Val F1=0.8192

Epoch 14: 100%|██████████| 125/125 [00:03<00:00, 32.61it/s, loss=0.438]

Epoch  14 | Train F1=0.8445 | Val F1=0.8113

Epoch 15: 100%|██████████| 125/125 [00:03<00:00, 39.99it/s, loss=0.45]

Epoch  15 | Train F1=0.8418 | Val F1=0.8078

Epoch 16: 100%|██████████| 125/125 [00:02<00:00, 44.52it/s, loss=0.47]

Epoch  16 | Train F1=0.8562 | Val F1=0.8340

Epoch 17: 100%|██████████| 125/125 [00:02<00:00, 46.48it/s, loss=0.411]

Epoch  17 | Train F1=0.8593 | Val F1=0.8358

Epoch 18: 100%|██████████| 125/125 [00:02<00:00, 57.96it/s, loss=0.44]

Epoch  18 | Train F1=0.8566 | Val F1=0.8250

Epoch 19: 100%|██████████| 125/125 [00:02<00:00, 56.14it/s, loss=0.54]

Epoch  19 | Train F1=0.8680 | Val F1=0.8459

Epoch 20: 100%|██████████| 125/125 [00:01<00:00, 69.44it/s, loss=0.534]

Epoch  20 | Train F1=0.8762 | Val F1=0.8568

Epoch 21: 100%|██████████| 125/125 [00:01<00:00, 63.37it/s, loss=0.494]

Epoch  21 | Train F1=0.8797 | Val F1=0.8505

Epoch 22: 100%|██████████| 125/125 [00:02<00:00, 58.31it/s, loss=0.447]

Epoch  22 | Train F1=0.8805 | Val F1=0.8597

Epoch 23: 100%|██████████| 125/125 [00:01<00:00, 77.87it/s, loss=0.475]

Epoch  23 | Train F1=0.8816 | Val F1=0.8603

Epoch 24: 100%|██████████| 125/125 [00:01<00:00, 82.18it/s, loss=0.36]

Epoch  24 | Train F1=0.8862 | Val F1=0.8600

Epoch 25: 100%|██████████| 125/125 [00:06<00:00, 18.81it/s, loss=0.37]

Epoch  25 | Train F1=0.8984 | Val F1=0.8702

Epoch 26: 100%|██████████| 125/125 [00:08<00:00, 15.37it/s, loss=0.453]

Epoch  26 | Train F1=0.8953 | Val F1=0.8590

Epoch 27: 100%|██████████| 125/125 [00:07<00:00, 16.36it/s, loss=0.359]

Epoch  27 | Train F1=0.8956 | Val F1=0.8702

Epoch 28: 100%|██████████| 125/125 [00:07<00:00, 16.47it/s, loss=0.4]

Epoch  28 | Train F1=0.8978 | Val F1=0.8646

Epoch 29: 100%|██████████| 125/125 [00:07<00:00, 16.59it/s, loss=0.346]

Epoch  29 | Train F1=0.8981 | Val F1=0.8715

Epoch 30: 100%|██████████| 125/125 [00:07<00:00, 16.55it/s, loss=0.462]

Epoch  30 | Train F1=0.9022 | Val F1=0.8710

Epoch 31: 100%|██████████| 125/125 [00:07<00:00, 16.48it/s, loss=0.447]

Epoch  31 | Train F1=0.9084 | Val F1=0.8736

Epoch 32: 100%|██████████| 125/125 [00:07<00:00, 16.57it/s, loss=0.487]

Epoch  32 | Train F1=0.9035 | Val F1=0.8720

Epoch 33: 100%|██████████| 125/125 [00:07<00:00, 16.52it/s, loss=0.379]

Epoch  33 | Train F1=0.9111 | Val F1=0.8777

Epoch 34: 100%|██████████| 125/125 [00:07<00:00, 16.58it/s, loss=0.396]

Epoch  34 | Train F1=0.9140 | Val F1=0.8901

Epoch 35: 100%|██████████| 125/125 [00:07<00:00, 16.60it/s, loss=0.368]

Epoch  35 | Train F1=0.9090 | Val F1=0.8755

Epoch 36: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.425]

Epoch  36 | Train F1=0.9142 | Val F1=0.8836

Epoch 37: 100%|██████████| 125/125 [00:08<00:00, 15.20it/s, loss=0.332]

Epoch  37 | Train F1=0.9105 | Val F1=0.8771

Epoch 38: 100%|██████████| 125/125 [00:08<00:00, 15.05it/s, loss=0.342]

Epoch  38 | Train F1=0.9181 | Val F1=0.8815

Epoch 39: 100%|██████████| 125/125 [00:08<00:00, 15.03it/s, loss=0.377]

Epoch  39 | Train F1=0.9184 | Val F1=0.8854

Epoch 40: 100%|██████████| 125/125 [00:08<00:00, 14.86it/s, loss=0.297]

Epoch  40 | Train F1=0.9205 | Val F1=0.8838

Epoch 41: 100%|██████████| 125/125 [00:08<00:00, 15.07it/s, loss=0.412]

Epoch  41 | Train F1=0.9193 | Val F1=0.8814

Epoch 42: 100%|██████████| 125/125 [00:08<00:00, 14.92it/s, loss=0.368]

Epoch  42 | Train F1=0.9096 | Val F1=0.8723

Epoch 43: 100%|██████████| 125/125 [00:08<00:00, 15.22it/s, loss=0.373]

Epoch  43 | Train F1=0.9202 | Val F1=0.8775

Epoch 44: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.273]

Epoch  44 | Train F1=0.9199 | Val F1=0.8789

Epoch 45: 100%|██████████| 125/125 [00:08<00:00, 15.53it/s, loss=0.388]

Epoch  45 | Train F1=0.9203 | Val F1=0.8806

Epoch 46: 100%|██████████| 125/125 [00:08<00:00, 15.13it/s, loss=0.31]

Epoch  46 | Train F1=0.9199 | Val F1=0.8813

Epoch 47: 100%|██████████| 125/125 [00:08<00:00, 14.74it/s, loss=0.377]

Epoch  47 | Train F1=0.9226 | Val F1=0.8778

Epoch 48: 100%|██████████| 125/125 [00:08<00:00, 14.98it/s, loss=0.319]

Epoch  48 | Train F1=0.9208 | Val F1=0.8845

Epoch 49: 100%|██████████| 125/125 [00:08<00:00, 14.92it/s, loss=0.321]

Epoch  49 | Train F1=0.9303 | Val F1=0.8911

Epoch 50: 100%|██████████| 125/125 [00:08<00:00, 14.76it/s, loss=0.367]

Epoch  50 | Train F1=0.9275 | Val F1=0.8865

Epoch 51: 100%|██████████| 125/125 [00:08<00:00, 14.84it/s, loss=0.303]

Epoch  51 | Train F1=0.9273 | Val F1=0.8821

Epoch 52: 100%|██████████| 125/125 [00:08<00:00, 14.99it/s, loss=0.387]

Epoch  52 | Train F1=0.9287 | Val F1=0.8847

Epoch 53: 100%|██████████| 125/125 [00:08<00:00, 14.98it/s, loss=0.299]

Epoch  53 | Train F1=0.9236 | Val F1=0.8799

Epoch 54: 100%|██████████| 125/125 [00:07<00:00, 16.63it/s, loss=0.346]

Epoch  54 | Train F1=0.9282 | Val F1=0.8903

Epoch 55: 100%|██████████| 125/125 [00:07<00:00, 16.33it/s, loss=0.348]

Epoch  55 | Train F1=0.9304 | Val F1=0.8918

Epoch 56: 100%|██████████| 125/125 [00:07<00:00, 15.98it/s, loss=0.24]

Epoch  56 | Train F1=0.9333 | Val F1=0.8977

Epoch 57: 100%|██████████| 125/125 [00:07<00:00, 15.99it/s, loss=0.308]

Epoch  57 | Train F1=0.9284 | Val F1=0.8896

Epoch 58: 100%|██████████| 125/125 [00:07<00:00, 16.42it/s, loss=0.299]

Epoch  58 | Train F1=0.9337 | Val F1=0.8923

Epoch 59: 100%|██████████| 125/125 [00:07<00:00, 16.10it/s, loss=0.407]

Epoch  59 | Train F1=0.9317 | Val F1=0.8938

Epoch 60: 100%|██████████| 125/125 [00:08<00:00, 14.57it/s, loss=0.443]

Epoch  60 | Train F1=0.9217 | Val F1=0.8769

Epoch 61: 100%|██████████| 125/125 [00:08<00:00, 14.89it/s, loss=0.331]

Epoch  61 | Train F1=0.9345 | Val F1=0.9007

Epoch 62: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.32]

Epoch  62 | Train F1=0.9316 | Val F1=0.8902

Epoch 63: 100%|██████████| 125/125 [00:08<00:00, 15.04it/s, loss=0.405]

Epoch  63 | Train F1=0.9303 | Val F1=0.8873

Epoch 64: 100%|██████████| 125/125 [00:08<00:00, 14.34it/s, loss=0.318]

Epoch  64 | Train F1=0.9355 | Val F1=0.8905

Epoch 65: 100%|██████████| 125/125 [00:08<00:00, 14.99it/s, loss=0.358]

Epoch  65 | Train F1=0.9377 | Val F1=0.8948

Epoch 66: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.312]

Epoch  66 | Train F1=0.9369 | Val F1=0.8936

Epoch 67: 100%|██████████| 125/125 [00:08<00:00, 14.71it/s, loss=0.331]

Epoch  67 | Train F1=0.9332 | Val F1=0.8917

Epoch 68: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.355]

Epoch  68 | Train F1=0.9422 | Val F1=0.8978

Epoch 69: 100%|██████████| 125/125 [00:08<00:00, 14.81it/s, loss=0.327]

Epoch  69 | Train F1=0.9442 | Val F1=0.8986

Epoch 70: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.284]

Epoch  70 | Train F1=0.9408 | Val F1=0.8974

Epoch 71: 100%|██████████| 125/125 [00:07<00:00, 16.18it/s, loss=0.212]

Epoch  71 | Train F1=0.9383 | Val F1=0.8834

Epoch 72: 100%|██████████| 125/125 [00:07<00:00, 15.94it/s, loss=0.231]

Epoch  72 | Train F1=0.9437 | Val F1=0.9013

Epoch 73: 100%|██████████| 125/125 [00:07<00:00, 15.77it/s, loss=0.353]

Epoch  73 | Train F1=0.9413 | Val F1=0.8868

Epoch 74: 100%|██████████| 125/125 [00:07<00:00, 16.32it/s, loss=0.225]

Epoch  74 | Train F1=0.9371 | Val F1=0.8880

Epoch 75: 100%|██████████| 125/125 [00:07<00:00, 16.39it/s, loss=0.293]

Epoch  75 | Train F1=0.9354 | Val F1=0.8879

Epoch 76: 100%|██████████| 125/125 [00:08<00:00, 14.64it/s, loss=0.398]

Epoch  76 | Train F1=0.9348 | Val F1=0.8848

Epoch 77: 100%|██████████| 125/125 [00:08<00:00, 14.77it/s, loss=0.362]

Epoch  77 | Train F1=0.9334 | Val F1=0.8881

Epoch 78: 100%|██████████| 125/125 [00:08<00:00, 14.88it/s, loss=0.332]

Epoch  78 | Train F1=0.9411 | Val F1=0.8960

Epoch 79: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.301]

Epoch  79 | Train F1=0.9416 | Val F1=0.8920

Epoch 80: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.256]

Epoch  80 | Train F1=0.9431 | Val F1=0.8966

Epoch 81: 100%|██████████| 125/125 [00:08<00:00, 14.85it/s, loss=0.284]

Epoch  81 | Train F1=0.9449 | Val F1=0.8935

Epoch 82: 100%|██████████| 125/125 [00:08<00:00, 14.68it/s, loss=0.292]

Epoch  82 | Train F1=0.9444 | Val F1=0.9010

Epoch 83: 100%|██████████| 125/125 [00:08<00:00, 14.93it/s, loss=0.37]

Epoch  83 | Train F1=0.9468 | Val F1=0.8922

Epoch 84: 100%|██████████| 125/125 [00:08<00:00, 14.88it/s, loss=0.367]

Epoch  84 | Train F1=0.9431 | Val F1=0.8890

Epoch 85: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.381]

Epoch  85 | Train F1=0.9408 | Val F1=0.8929

Epoch 86: 100%|██████████| 125/125 [00:08<00:00, 15.02it/s, loss=0.245]

Epoch  86 | Train F1=0.9430 | Val F1=0.8938

Epoch 87: 100%|██████████| 125/125 [00:08<00:00, 14.54it/s, loss=0.357]

Epoch  87 | Train F1=0.9454 | Val F1=0.8917

Epoch 88: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.24]

Epoch  88 | Train F1=0.9387 | Val F1=0.8849

Epoch 89: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.202]

Epoch  89 | Train F1=0.9482 | Val F1=0.9007

Epoch 90: 100%|██████████| 125/125 [00:08<00:00, 14.94it/s, loss=0.321]

Epoch  90 | Train F1=0.9481 | Val F1=0.8975

Epoch 91: 100%|██████████| 125/125 [00:08<00:00, 14.87it/s, loss=0.308]

Epoch  91 | Train F1=0.9495 | Val F1=0.9002

Epoch 92: 100%|██████████| 125/125 [00:08<00:00, 14.91it/s, loss=0.372]

Epoch  92 | Train F1=0.9428 | Val F1=0.8892

Epoch 93: 100%|██████████| 125/125 [00:08<00:00, 14.93it/s, loss=0.276]

Epoch  93 | Train F1=0.9481 | Val F1=0.8970

Epoch 94: 100%|██████████| 125/125 [00:08<00:00, 14.94it/s, loss=0.365]

Epoch  94 | Train F1=0.9416 | Val F1=0.8969

Epoch 95: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.191]

Epoch  95 | Train F1=0.9461 | Val F1=0.8980

Epoch 96: 100%|██████████| 125/125 [00:07<00:00, 16.53it/s, loss=0.24]

Epoch  96 | Train F1=0.9498 | Val F1=0.8949

Epoch 97: 100%|██████████| 125/125 [00:07<00:00, 16.48it/s, loss=0.256]

Epoch  97 | Train F1=0.9446 | Val F1=0.8884

Epoch 98: 100%|██████████| 125/125 [00:07<00:00, 16.06it/s, loss=0.158]

Epoch  98 | Train F1=0.9494 | Val F1=0.8960

Epoch 99: 100%|██████████| 125/125 [00:07<00:00, 15.77it/s, loss=0.367]

Epoch  99 | Train F1=0.9505 | Val F1=0.8983

Epoch 100: 100%|██████████| 125/125 [00:07<00:00, 15.78it/s, loss=0.216]

Epoch 100 | Train F1=0.9520 | Val F1=0.9019

In [66]:
test_loss, test_f1 = evaluate(
    enc,
    cla,
    test_loader,
    nn.CrossEntropyLoss(),
    device
)

print(test_loss)
print(test_f1)

0.3545351684903582
0.9056072235107422

In [69]:
px.line(history["val_f1"], title="Val F1 Score", labels={"index": "Epoch", "value": "F1 Score"})

## Experimentações

In [31]:
pasta = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\modelos\\'
adapt = np.zeros((7,7))
for i in range(7):
    for j in range(7):
        if i==j:
            continue
        enc = ChangEncoder().to(device)
        enc.load_state_dict(torch.load(pasta+posis[i]+'_adapt_encoder_'+posis[j]+'.pth', weights_only=True))
        cla = ChangClassifier().to(device)
        cla.load_state_dict(torch.load(pasta+posis[i]+'_adapt_classifier_'+posis[j]+'.pth', weights_only=True))
        inds = ycort[:,0]==j
        Xs = Xcort[inds]
        ys = ycort[inds][:,1]
        _, Xs_test, _, ys_test = train_test_split(Xs, ys, test_size=0.2, random_state=1, stratify=ys)
        Xs_test  = torch.tensor(Xs_test, dtype=torch.float32).to(device)
        ys_test  = torch.tensor(ys_test, dtype=torch.long).to(device)
        test_loader = DataLoader(TensorDataset(Xs_test, ys_test), batch_size=256, shuffle=False)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        adapt[i,j] = test_f1

In [39]:
df = pd.DataFrame((adapt*100).round(1), columns=posis, index=posis)
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          head  chest  upperarm  forearm  waist  thigh  shin
head       0.0   60.0      56.5     49.3   53.3   51.1  41.1
chest     57.9    0.0      56.8     49.4   62.5   58.6  42.1
upperarm  60.2   70.0       0.0     37.2   30.1   70.1  68.2
forearm   47.8   43.5      48.4      0.0   47.7   45.4  53.2
waist     58.0   34.8      36.2     45.0    0.0   40.0  16.5
thigh     55.8   58.8      55.3     46.3   54.2    0.0  69.3
shin      35.3   59.9      58.8     42.2   34.1   60.0   0.0

In [40]:
labels = ["head", "chest", "upperarm", "forearm", "waist", "thigh", "shin"]

data = [
    [0, 66.5, 61.0, 43.0, 66.7, 54.5, 54.4],  # head
    [59.2, 0, 54.0, 53.7, 77.0, 48.9, 33.4],  # chest
    [53.7, 57.9, 0, 47.6, 69.8, 58.2, 62.5],  # upperarm
    [44.0, 56.2, 49.5, 0, 63.2, 46.7, 39.4],  # forearm
    [42.3, 75.7, 61.7, 53.9, 0, 62.1, 32.8],  # waist
    [55.4, 57.9, 53.9, 43.6, 53.0, 0, 56.0],  # thigh
    [34.7, 51.2, 59.9, 34.9, 36.8, 44.4, 0],  # shin
]

df2 = pd.DataFrame(data, index=labels, columns=labels)
df2

          head  chest  upperarm  forearm  waist  thigh  shin
head       0.0   66.5      61.0     43.0   66.7   54.5  54.4
chest     59.2    0.0      54.0     53.7   77.0   48.9  33.4
upperarm  53.7   57.9       0.0     47.6   69.8   58.2  62.5
forearm   44.0   56.2      49.5      0.0   63.2   46.7  39.4
waist     42.3   75.7      61.7     53.9    0.0   62.1  32.8
thigh     55.4   57.9      53.9     43.6   53.0    0.0  56.0
shin      34.7   51.2      59.9     34.9   36.8   44.4   0.0

In [42]:
df-df2

          head  chest  upperarm  forearm  waist  thigh  shin
head       0.0   -6.5      -4.5      6.3  -13.4   -3.4 -13.3
chest     -1.3    0.0       2.8     -4.3  -14.5    9.7   8.7
upperarm   6.5   12.1       0.0    -10.4  -39.7   11.9   5.7
forearm    3.8  -12.7      -1.1      0.0  -15.5   -1.3  13.8
waist     15.7  -40.9     -25.5     -8.9    0.0  -22.1 -16.3
thigh      0.4    0.9       1.4      2.7    1.2    0.0  13.3
shin       0.6    8.7      -1.1      7.3   -2.7   15.6   0.0

# Benchmarks de classificação com features

## Espectro

In [42]:
def spectral_energy(X):
    N, T, C = X.shape
    energy = np.zeros((N, T//2, C))
    for i in range(N):
        for j in range(C):
            fft = np.fft.fft(X[i,:,j])
            energy[i,:,j] = np.abs(fft[:T//2])**2/T
    return energy

In [43]:
S = spectral_energy(Xcort)
S = S.reshape(S.shape[0], -1, order='F')

In [44]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        S[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(S[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:19<00:00,  2.82s/it]

In [45]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          76    76     46        24       37     54     41    12
chest         89    31     89        35       33     42     46    26
upperarm      85    14     37        85       30     12     33    46
forearm       82    29     41        37       82     36     33    25
waist         90    32     15         5       21     90     12     1
thigh         93    34     43        35       34     24     93    21
shin          92     7     27        32       12      3     18    92

In [59]:
data = {
    'Treino': [86, 94, 89, 88, 93, 94, 92],
    'head': ['-', 28, 47, 16, 16, 39, 6],
    'chest': [60, '-', 58, 12, 22, 39, 29],
    'upperarm': [51, 32, '-', 11, 5, 45, 33],
    'forearm': [26, 25, 20, '-', 25, 5, 3],
    'waist': [14, 30, 18, 39, '-', 16, 9],
    'thigh': [37, 42, 44, 12, 15, '-', 30],
    'shin': [23, 24, 35, 9, 2, 40, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          86    -    60       51      26    14    37   23
chest         94   28     -       32      25    30    42   24
upperarm      89   47    58        -      20    18    44   35
forearm       88   16    12       11       -    39    12    9
waist         93   16    22        5      25     -    15    2
thigh         94   39    39       45       5    16     -   40
shin          92    6    29       33       3     9    30    -

## Frequência Fundamental, Energia e Valor Médio

In [60]:
Vm = np.mean(Xcort, axis=1)
Xm = Xcort - np.mean(Xcort, axis=1, keepdims=True)
En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

In [62]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        Vm[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(Vm[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  6.34it/s]

In [63]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          57    57     21        13       18     16     22    10
chest         78    13     78        12       17     25     23    11
upperarm      69    10     15        69        5     10     21    26
forearm       72    14      7         4       72     12      9     3
waist         76    11     12         2       18     76     12     3
thigh         82    21     23        19        5      9     82    13
shin          83     9     23        20        3     18     14    83

In [64]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        En[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(En[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:00<00:00, 10.03it/s]

In [65]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          44    44     38        42       38     37     30    22
chest         45    37     45        39       37     39     28    17
upperarm      47    43     41        47       42     39     36    25
forearm       44    39     41        43       44     40     35    29
waist         44    39     42        40       40     44     34    24
thigh         46    32     35        38       35     35     46    37
shin          44    18     20        27       25     19     40    44

In [68]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        f0est[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(f0est[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  6.72it/s]

In [69]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          61    61     60        60       57     57     60    61
chest         60    61     60        61       61     58     61    60
upperarm      61    62     61        61       61     59     60    63
forearm       63    60     62        61       63     60     61    62
waist         63    60     61        61       60     63     61    58
thigh         63    62     64        60       61     62     63    62
shin          64    59     62        58       60     60     61    64

In [11]:
feats = np.concatenate((Vm, En, f0est), axis=1)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  4.24it/s]

In [12]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          78    78     56        53       41     38     49    41
chest         84    50     84        47       48     44     32    21
upperarm      82    45     61        82       34     41     52    39
forearm       81    34     32        27       81     39     40    33
waist         85    47     54        41       51     85     41    29
thigh         82    46     48        45       33     47     82    50
shin          81    28     48        45       25     34     53    81

In [9]:
feats = np.concatenate((En, f0est), axis=1)
scaler = StandardScaler()
scaler.fit(feats)
feats = scaler.transform(feats)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  6.82it/s]

In [10]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          65    65     58        61       56     51     46    41
chest         66    57     66        53       50     55     37    24
upperarm      67    60     60        67       60     56     50    42
forearm       64    57     60        62       64     55     51    45
waist         64    53     58        55       50     64     48    36
thigh         67    49     52        53       48     53     67    55
shin          67    36     42        44       42     38     59    67

In [203]:
data = {
    'Treino': [84, 90, 88, 84, 91, 90, 91],
    'head': ['-', 46, 46, 30, 38, 41, 18],
    'chest': [52, '-', 64, 32, 29, 34, 34],
    'upperarm': [51, 43, '-', 39, 20, 39, 39],
    'forearm': [25, 38, 29, '-', 27, 33, 28],
    'waist': [29, 37, 18, 24, '-', 39, 21],
    'thigh': [44, 46, 62, 35, 28, '-', 38],
    'shin': [22, 35, 46, 28, 17, 51, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          84    -    52       51      25    29    44   22
chest         90   46     -       43      38    37    46   35
upperarm      88   46    64        -      29    18    62   46
forearm       84   30    32       39       -    24    35   28
waist         91   38    29       20      27     -    28   17
thigh         90   41    34       39      33    39     -   51
shin          91   18    34       39      28    21    38    -

## Modelo harmônico

In [ ]:
# for l in range(L):
#     A = coefs[l,:]
#     B = coefs[l+L,:]
#     M = np.vstack((A, B)).T
#     G = M.T.dot(M)
#     w, v = np.linalg.eig(G)
#     w = np.sort(w)[::-1]
#     sige = np.sqrt(w)
#     El[l] = np.sqrt(w.sum())

In [6]:
L = 4
hAmps = []
for i, janela in tqdm(enumerate(Xm)):
    f0 = f0est[i]
    arg = np.outer(np.arange(J)/fs, np.arange(1,L+1)*2*np.pi*f0)
    C = np.cos(arg)
    S = np.sin(arg)
    theta = np.hstack((C, S))
    coefs = np.linalg.pinv(theta).dot(janela)
    hAmps.append(np.sqrt((coefs[:L,:]**2 + coefs[L:,:]**2).sum(axis=1)))
hAmps = np.array(hAmps)

144647it [00:11, 12172.25it/s]

In [17]:
fig = go.Figure()
act1 = 0
act2 = 4
for p in range(7):
    inds = (ycort[:,1]==act1) & (ycort[:,0]==p)
    fig.add_trace(go.Scatter(x=hAmps[inds,0], y=hAmps[inds,1], mode='markers', name=actis[act1] + ' '+ posis[p]))
    inds = (ycort[:,1]==act2) & (ycort[:,0]==p)
    fig.add_trace(go.Scatter(x=hAmps[inds,0], y=hAmps[inds,1], mode='markers', name=actis[act2] + ' '+ posis[p]))
fig.show()

In [44]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  5.00it/s]

In [9]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          62    62     51        54       52     45     41    35
chest         63    51     63        51       47     53     39    32
upperarm      63    53     55        63       56     49     46    43
forearm       62    54     54        57       62     48     47    44
waist         59    49     55        50       48     59     48    38
thigh         60    42     47        48       44     47     60    52
shin          62    28     33        33       34     32     51    62

In [53]:
i, j = 0, 1
inds = ycort[:,0]==i
X_train, X_test, y_train, y_test = train_test_split(
    hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
inds = ycort[:,0]==j
X_train, X_test, y_train, y_test = train_test_split(hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
y_pred = neigh.predict(X_test)
z = confusion_matrix(y_test, y_pred)
fig = px.imshow(z, x=actis, y=actis, text_auto=True, labels=dict(x="Estimado", y="Referência", color="Quantidade"),
    width=700, height=500, color_continuous_scale='Blues', title="Treino: {}, Teste: {}".format(posis[i], posis[j]))
fig.update_yaxes(autorange="reversed")
fig.show()

In [ ]:
feats = np.concatenate((hAmps, En, f0est), axis=1)
# scaler = StandardScaler()
# scaler.fit(feats)
# feats = scaler.transform(feats)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:02<00:00,  2.71it/s]

In [56]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          69    69     58        61       56     53     47    38
chest         70    61     70        57       51     58     39    23
upperarm      71    63     62        71       61     57     50    41
forearm       66    58     60        66       66     53     53    44
waist         69    55     61        58       52     69     47    30
thigh         71    50     54        55       50     52     71    56
shin          70    32     36        41       40     33     58    70

In [67]:
feats = np.concatenate((hAmps/np.max(hAmps, axis=1, keepdims=True), En, f0est), axis=1)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ycort[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ycort[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

  0%|          | 0/7 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:01<00:00,  3.69it/s]

In [68]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          68    68     55        58       51     51     46    35
chest         68    56     68        56       45     58     37    23
upperarm      68    58     62        68       57     59     49    36
forearm       66    58     58        62       66     53     51    41
waist         69    52     59        54       46     69     47    25
thigh         68    46     49        49       47     49     68    51
shin          71    30     35        37       35     33     52    71

In [69]:
posis

['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']

In [70]:
i, j = 0, 3
inds = ycort[:,0]==i
X_train, X_test, y_train, y_test = train_test_split(
    hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
inds = ycort[:,0]==j
X_train, X_test, y_train, y_test = train_test_split(hAmps[inds], ycort[inds,1], test_size=0.2, random_state=1, stratify=ycort[inds,1])
y_pred = neigh.predict(X_test)
z = confusion_matrix(y_test, y_pred)
fig = px.imshow(z, x=actis, y=actis, text_auto=True, labels=dict(x="Estimado", y="Referência", color="Quantidade"),
    width=700, height=500, color_continuous_scale='Blues', title="Treino: {}, Teste: {}".format(posis[i], posis[j]))
fig.update_yaxes(autorange="reversed")
fig.show()