# Inicio

In [ ]:
pip install torchmetrics

In [2]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor
import torch.optim as optim
from torchmetrics.functional.classification import multiclass_f1_score
from sklearn.metrics import f1_score

import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import copy
from copy import deepcopy
from tqdm import tqdm
import time
import os
from scipy.signal import butter, sosfiltfilt
from scipy.spatial import distance
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device

In [4]:
actis = ['climbingdown', 'climbingup', 'jumping', 'lying', 'running', 'sitting', 'standing', 'walking']
posis = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
users = ['proband' + x for x in np.arange(1,16).astype(str)]

In [5]:
data = np.load('/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/notebooks/Xycort.npz')
Xcort = data['Xcort']
ycort = data['ycort']
J = 150
fs = 50
data = np.load('/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/notebooks/f0est.npz')
f0est = data['f0est']
Vm = np.mean(Xcort, axis=1)
Xm = Xcort - np.mean(Xcort, axis=1, keepdims=True)
En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

In [ ]:
# data = np.load('/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/notebooks/Xydata.npz')
# Xdata = data['Xdata']
# ydata = data['ydata']

# Modelo chang

In [6]:
class ChangEncoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv1d(in_channels=3, out_channels=16, kernel_size=3)
        self.inst1 = nn.InstanceNorm1d(16, affine=True)
        self.drop1 = nn.Dropout(p=0.2)

        self.conv2 = nn.Conv1d(in_channels=16, out_channels=16, kernel_size=3)
        self.inst2 = nn.InstanceNorm1d(16, affine=True)
        self.drop2 = nn.Dropout(p=0.2)

        self.conv3 = nn.Conv1d(in_channels=16, out_channels=32, kernel_size=5, stride=4)
        self.inst3 = nn.InstanceNorm1d(32, affine=True)
        self.drop3 = nn.Dropout(p=0.2)

        self.conv4 = nn.Conv1d(in_channels=32, out_channels=32, kernel_size=3, stride=1)
        self.inst4 = nn.InstanceNorm1d(32, affine=True)
        self.drop4 = nn.Dropout(p=0.2)

        self.conv5 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=5, stride=4)
        self.inst5 = nn.InstanceNorm1d(64, affine=True)
        self.drop5 = nn.Dropout(p=0.2)

        self.conv6 = nn.Conv1d(in_channels=64, out_channels=100, kernel_size=5, stride=1)

        self.relu = nn.LeakyReLU(0.3)
        self.glap = nn.AvgPool1d(kernel_size=4)

    def forward(self, x):
        # (N,T,C) -> (N,C,T)
        x = x.transpose(1, 2)
        x = self.conv1(x)
        x = self.relu(x)
        x = self.inst1(x)
        x = self.drop1(x)

        x = self.conv2(x)
        x = self.relu(x)
        x = self.inst2(x)
        x = self.drop2(x)

        x = self.conv3(x)
        x = self.relu(x)
        x = self.inst3(x)
        x = self.drop3(x)

        x = self.conv4(x)
        x = self.relu(x)
        x = self.inst4(x)
        x = self.drop4(x)

        x = self.conv5(x)
        x = self.relu(x)
        x = self.inst5(x)
        x = self.drop5(x)

        x = self.conv6(x)
        x = self.relu(x)

        x = self.glap(x)
        x = x.flatten(start_dim=1)

        logits = x
        return logits

In [7]:
class ChangClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.densa = nn.Linear(in_features=100, out_features=8)

    def forward(self, x):
        logits = self.densa(x)
        return logits

# Funções de Treinamento

In [9]:
inds = ycort[:,0]==0
X = Xcort[inds]
y = ycort[inds][:,1]
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

X_train = torch.tensor(X_train, dtype=torch.float32)
X_val   = torch.tensor(X_val, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.long)
y_val   = torch.tensor(y_val, dtype=torch.long)
y_test  = torch.tensor(y_test, dtype=torch.long)

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
val_loader = DataLoader(TensorDataset(X_val, y_val), batch_size=256, shuffle=False, pin_memory=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)

In [10]:
@torch.no_grad()
def evaluate(encoder, classifier, loader, loss_fn, device):
    encoder.eval()
    classifier.eval()
    total_loss = 0
    total_samples = 0
    y_true = []
    y_pred = []

    for X, y in loader:
        X = X.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        logits = classifier(encoder(X))
        loss = loss_fn(logits, y)
        total_loss += loss.item() * len(y)
        total_samples += len(y)
        pred = torch.argmax(logits, dim=1)
        y_true.append(y)
        y_pred.append(pred)

    y_true = torch.cat(y_true)
    y_pred = torch.cat(y_pred)
    f1 = multiclass_f1_score(y_pred, y_true, num_classes=8, average="macro").item()

    return total_loss / total_samples, f1

In [15]:
def train_model(train_loader, val_loader, device, n_epochs):
    encoder = ChangEncoder().to(device)
    classifier = ChangClassifier().to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=1e-3)
    history = {
        "train_loss": [],
        "val_loss": [],
        "train_f1": [],
        "val_f1": []
    }
    best_f1 = -1
    best_encoder = None
    best_classifier = None

    for epoch in range(n_epochs):
        encoder.train()
        classifier.train()
        running_loss = 0
        n_samples = 0
        bar = tqdm(train_loader)

        for X, y in bar:
            X = X.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            optimizer.zero_grad()
            logits = classifier(encoder(X))
            loss = loss_fn(logits, y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * len(y)
            n_samples += len(y)
            bar.set_description(f"Epoch {epoch+1}")
            bar.set_postfix(loss=loss.item())

        train_loss, train_f1 = evaluate(
            encoder,
            classifier,
            train_loader,
            loss_fn,
            device
        )

        val_loss, val_f1 = evaluate(
            encoder,
            classifier,
            val_loader,
            loss_fn,
            device
        )

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_f1"].append(train_f1)
        history["val_f1"].append(val_f1)

        print(
            f"Epoch {epoch+1:3d} | "
            f"Train F1={train_f1:.4f} | "
            f"Val F1={val_f1:.4f}"
        )

        if val_f1 > best_f1:
            best_f1 = val_f1
            best_encoder = deepcopy(encoder)
            best_classifier = deepcopy(classifier)

    return best_encoder, best_classifier, history

# Teste baseline

In [12]:
# Resultados de referência
data = {
    'Treino': [86, 94, 89, 88, 93, 94, 92],
    'head': ['-', 28, 47, 16, 16, 39, 6],
    'chest': [60, '-', 58, 12, 22, 39, 29],
    'upperarm': [51, 32, '-', 11, 5, 45, 33],
    'forearm': [26, 25, 20, '-', 25, 5, 3],
    'waist': [14, 30, 18, 39, '-', 16, 9],
    'thigh': [37, 42, 44, 12, 15, '-', 30],
    'shin': [23, 24, 35, 9, 2, 40, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          86    -    60       51      26    14    37   23
chest         94   28     -       32      25    30    42   24
upperarm      89   47    58        -      20    18    44   35
forearm       88   16    12       11       -    39    12    9
waist         93   16    22        5      25     -    15    2
thigh         94   39    39       45       5    16     -   40
shin          92    6    29       33       3     9    30    -

## Baseline 0: Chang

In [13]:
pasta = '/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/modelos/'
baselinef1 = np.zeros((7,7))
for i, pos in enumerate(posis):
    inds = ycort[:,0]==i
    X = Xcort[inds]
    y = ycort[inds][:,1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
    X_train = torch.tensor(X_train, dtype=torch.float32)
    X_test  = torch.tensor(X_test, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.long)
    y_test  = torch.tensor(y_test, dtype=torch.long)
    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
    test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
    enc, cla, history = train_model(train_loader, test_loader, device, n_epochs=100)
    nome = 'baseline_encoder_'+pos+'.pth'
    torch.save(enc.state_dict(), pasta+nome)
    nome = 'baseline_classifier_'+pos+'.pth'
    torch.save(cla.state_dict(), pasta+nome)
    for j in range(7):
        inds = ycort[:,0]==j
        X = Xcort[inds]
        y = ycort[inds][:,1]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
        X_test  = torch.tensor(X_test, dtype=torch.float32)
        y_test  = torch.tensor(y_test, dtype=torch.long)
        test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        baselinef1[i,j] = test_f1

Epoch 1: 100%|██████████| 133/133 [00:02<00:00, 47.10it/s, loss=0.783]

Epoch   1 | Train F1=0.5875 | Val F1=0.5881

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 106.07it/s, loss=0.819]

Epoch   2 | Train F1=0.6826 | Val F1=0.6644

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 112.44it/s, loss=0.561]

Epoch   3 | Train F1=0.7282 | Val F1=0.7268

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 114.36it/s, loss=0.438]

Epoch   4 | Train F1=0.7432 | Val F1=0.7281

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 113.87it/s, loss=0.459]

Epoch   5 | Train F1=0.7681 | Val F1=0.7507

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 112.68it/s, loss=0.467]

Epoch   6 | Train F1=0.7863 | Val F1=0.7714

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 106.79it/s, loss=0.458]

Epoch   7 | Train F1=0.8127 | Val F1=0.7942

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 92.70it/s, loss=0.806]

Epoch   8 | Train F1=0.8161 | Val F1=0.7968

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 89.06it/s, loss=0.394]

Epoch   9 | Train F1=0.8513 | Val F1=0.8307

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 106.36it/s, loss=0.596]

Epoch  10 | Train F1=0.8405 | Val F1=0.8219

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 110.41it/s, loss=0.515]

Epoch  11 | Train F1=0.8499 | Val F1=0.8368

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 106.97it/s, loss=0.401]

Epoch  12 | Train F1=0.8843 | Val F1=0.8643

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 66.73it/s, loss=0.267]

Epoch  13 | Train F1=0.8830 | Val F1=0.8645

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 110.55it/s, loss=0.399]

Epoch  14 | Train F1=0.8853 | Val F1=0.8699

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 91.00it/s, loss=0.224]

Epoch  15 | Train F1=0.8949 | Val F1=0.8758

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 92.78it/s, loss=0.298]

Epoch  16 | Train F1=0.8974 | Val F1=0.8765

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 93.21it/s, loss=0.424]

Epoch  17 | Train F1=0.8817 | Val F1=0.8576

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 103.08it/s, loss=0.431]

Epoch  18 | Train F1=0.9021 | Val F1=0.8864

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 111.09it/s, loss=0.522]

Epoch  19 | Train F1=0.9061 | Val F1=0.8844

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 107.42it/s, loss=0.351]

Epoch  20 | Train F1=0.9128 | Val F1=0.8920

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 107.91it/s, loss=0.232]

Epoch  21 | Train F1=0.9169 | Val F1=0.8959

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 105.85it/s, loss=0.207]

Epoch  22 | Train F1=0.9263 | Val F1=0.9067

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 86.12it/s, loss=0.185]

Epoch  23 | Train F1=0.9253 | Val F1=0.9056

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 88.93it/s, loss=0.152]

Epoch  24 | Train F1=0.9202 | Val F1=0.9019

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 104.34it/s, loss=0.35]

Epoch  25 | Train F1=0.9333 | Val F1=0.9106

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 110.67it/s, loss=0.432]

Epoch  26 | Train F1=0.9276 | Val F1=0.9077

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 108.96it/s, loss=0.554]

Epoch  27 | Train F1=0.9288 | Val F1=0.9067

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 104.96it/s, loss=0.291]

Epoch  28 | Train F1=0.9288 | Val F1=0.9076

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 102.65it/s, loss=0.28]

Epoch  29 | Train F1=0.9376 | Val F1=0.9129

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 109.73it/s, loss=0.546]

Epoch  30 | Train F1=0.9393 | Val F1=0.9222

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 79.76it/s, loss=0.291]

Epoch  31 | Train F1=0.9361 | Val F1=0.9156

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 85.31it/s, loss=0.592]

Epoch  32 | Train F1=0.9288 | Val F1=0.9071

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 106.06it/s, loss=0.208]

Epoch  33 | Train F1=0.9385 | Val F1=0.9191

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 102.50it/s, loss=0.228]

Epoch  34 | Train F1=0.9411 | Val F1=0.9164

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 101.75it/s, loss=0.29]

Epoch  35 | Train F1=0.9368 | Val F1=0.9195

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 101.70it/s, loss=0.396]

Epoch  36 | Train F1=0.9370 | Val F1=0.9155

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 102.29it/s, loss=0.253]

Epoch  37 | Train F1=0.9431 | Val F1=0.9240

Epoch 38: 100%|██████████| 133/133 [00:02<00:00, 62.62it/s, loss=0.189]

Epoch  38 | Train F1=0.9461 | Val F1=0.9187

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 92.45it/s, loss=0.189]

Epoch  39 | Train F1=0.9377 | Val F1=0.9133

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 89.29it/s, loss=0.318]

Epoch  40 | Train F1=0.9424 | Val F1=0.9148

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 102.58it/s, loss=0.476]

Epoch  41 | Train F1=0.9415 | Val F1=0.9158

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 102.59it/s, loss=0.164]

Epoch  42 | Train F1=0.9442 | Val F1=0.9220

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 98.69it/s, loss=0.208]

Epoch  43 | Train F1=0.9459 | Val F1=0.9230

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 99.05it/s, loss=0.184]

Epoch  44 | Train F1=0.9470 | Val F1=0.9201

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 104.29it/s, loss=0.248]

Epoch  45 | Train F1=0.9426 | Val F1=0.9191

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 84.02it/s, loss=0.238]

Epoch  46 | Train F1=0.9491 | Val F1=0.9221

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 90.98it/s, loss=0.121]

Epoch  47 | Train F1=0.9443 | Val F1=0.9221

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 90.15it/s, loss=0.384]

Epoch  48 | Train F1=0.9488 | Val F1=0.9250

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 101.33it/s, loss=0.242]

Epoch  49 | Train F1=0.9484 | Val F1=0.9232

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 99.03it/s, loss=0.122]

Epoch  50 | Train F1=0.9513 | Val F1=0.9232

Epoch 51: 100%|██████████| 133/133 [00:01<00:00, 104.34it/s, loss=0.238]

Epoch  51 | Train F1=0.9486 | Val F1=0.9202

Epoch 52: 100%|██████████| 133/133 [00:01<00:00, 95.31it/s, loss=0.237]

Epoch  52 | Train F1=0.9414 | Val F1=0.9134

Epoch 53: 100%|██████████| 133/133 [00:01<00:00, 90.23it/s, loss=0.141]

Epoch  53 | Train F1=0.9506 | Val F1=0.9221

Epoch 54: 100%|██████████| 133/133 [00:01<00:00, 80.50it/s, loss=0.173]

Epoch  54 | Train F1=0.9479 | Val F1=0.9198

Epoch 55: 100%|██████████| 133/133 [00:01<00:00, 79.57it/s, loss=0.325]

Epoch  55 | Train F1=0.9512 | Val F1=0.9245

Epoch 56: 100%|██████████| 133/133 [00:01<00:00, 99.92it/s, loss=0.301]

Epoch  56 | Train F1=0.9554 | Val F1=0.9278

Epoch 57: 100%|██████████| 133/133 [00:01<00:00, 100.87it/s, loss=0.231]

Epoch  57 | Train F1=0.9460 | Val F1=0.9209

Epoch 58: 100%|██████████| 133/133 [00:01<00:00, 103.58it/s, loss=0.255]

Epoch  58 | Train F1=0.9475 | Val F1=0.9227

Epoch 59: 100%|██████████| 133/133 [00:01<00:00, 100.87it/s, loss=0.394]

Epoch  59 | Train F1=0.9500 | Val F1=0.9200

Epoch 60: 100%|██████████| 133/133 [00:01<00:00, 98.68it/s, loss=0.254]

Epoch  60 | Train F1=0.9471 | Val F1=0.9173

Epoch 61: 100%|██████████| 133/133 [00:01<00:00, 91.28it/s, loss=0.191]

Epoch  61 | Train F1=0.9548 | Val F1=0.9248

Epoch 62: 100%|██████████| 133/133 [00:01<00:00, 86.94it/s, loss=0.155]

Epoch  62 | Train F1=0.9442 | Val F1=0.9133

Epoch 63: 100%|██████████| 133/133 [00:01<00:00, 77.48it/s, loss=0.141]

Epoch  63 | Train F1=0.9542 | Val F1=0.9199

Epoch 64: 100%|██████████| 133/133 [00:01<00:00, 100.98it/s, loss=0.0784]

Epoch  64 | Train F1=0.9533 | Val F1=0.9219

Epoch 65: 100%|██████████| 133/133 [00:01<00:00, 103.09it/s, loss=0.406]

Epoch  65 | Train F1=0.9416 | Val F1=0.9151

Epoch 66: 100%|██████████| 133/133 [00:01<00:00, 99.62it/s, loss=0.18]

Epoch  66 | Train F1=0.9538 | Val F1=0.9267

Epoch 67: 100%|██████████| 133/133 [00:01<00:00, 102.94it/s, loss=0.281]

Epoch  67 | Train F1=0.9501 | Val F1=0.9210

Epoch 68: 100%|██████████| 133/133 [00:01<00:00, 98.45it/s, loss=0.229]

Epoch  68 | Train F1=0.9566 | Val F1=0.9248

Epoch 69: 100%|██████████| 133/133 [00:01<00:00, 86.61it/s, loss=0.192]

Epoch  69 | Train F1=0.9521 | Val F1=0.9198

Epoch 70: 100%|██████████| 133/133 [00:01<00:00, 81.36it/s, loss=0.144]

Epoch  70 | Train F1=0.9534 | Val F1=0.9203

Epoch 71: 100%|██████████| 133/133 [00:01<00:00, 81.31it/s, loss=0.304]

Epoch  71 | Train F1=0.9575 | Val F1=0.9241

Epoch 72: 100%|██████████| 133/133 [00:01<00:00, 96.56it/s, loss=0.381]

Epoch  72 | Train F1=0.9569 | Val F1=0.9179

Epoch 73: 100%|██████████| 133/133 [00:01<00:00, 97.69it/s, loss=0.191]

Epoch  73 | Train F1=0.9573 | Val F1=0.9281

Epoch 74: 100%|██████████| 133/133 [00:01<00:00, 93.81it/s, loss=0.123]

Epoch  74 | Train F1=0.9574 | Val F1=0.9271

Epoch 75: 100%|██████████| 133/133 [00:01<00:00, 92.41it/s, loss=0.257]

Epoch  75 | Train F1=0.9568 | Val F1=0.9245

Epoch 76: 100%|██████████| 133/133 [00:01<00:00, 95.45it/s, loss=0.221]

Epoch  76 | Train F1=0.9507 | Val F1=0.9183

Epoch 77: 100%|██████████| 133/133 [00:01<00:00, 81.15it/s, loss=0.236]

Epoch  77 | Train F1=0.9560 | Val F1=0.9223

Epoch 78: 100%|██████████| 133/133 [00:01<00:00, 91.10it/s, loss=0.173]

Epoch  78 | Train F1=0.9602 | Val F1=0.9295

Epoch 79: 100%|██████████| 133/133 [00:01<00:00, 87.19it/s, loss=0.243]

Epoch  79 | Train F1=0.9595 | Val F1=0.9275

Epoch 80: 100%|██████████| 133/133 [00:01<00:00, 98.12it/s, loss=0.138]

Epoch  80 | Train F1=0.9554 | Val F1=0.9246

Epoch 81: 100%|██████████| 133/133 [00:01<00:00, 93.22it/s, loss=0.279]

Epoch  81 | Train F1=0.9619 | Val F1=0.9289

Epoch 82: 100%|██████████| 133/133 [00:01<00:00, 96.21it/s, loss=0.224]

Epoch  82 | Train F1=0.9606 | Val F1=0.9267

Epoch 83: 100%|██████████| 133/133 [00:01<00:00, 98.57it/s, loss=0.177]

Epoch  83 | Train F1=0.9599 | Val F1=0.9278

Epoch 84: 100%|██████████| 133/133 [00:01<00:00, 90.15it/s, loss=0.217]

Epoch  84 | Train F1=0.9554 | Val F1=0.9228

Epoch 85: 100%|██████████| 133/133 [00:01<00:00, 77.37it/s, loss=0.19]

Epoch  85 | Train F1=0.9628 | Val F1=0.9316

Epoch 86: 100%|██████████| 133/133 [00:01<00:00, 79.08it/s, loss=0.341]

Epoch  86 | Train F1=0.9578 | Val F1=0.9242

Epoch 87: 100%|██████████| 133/133 [00:01<00:00, 93.54it/s, loss=0.207]

Epoch  87 | Train F1=0.9631 | Val F1=0.9313

Epoch 88: 100%|██████████| 133/133 [00:01<00:00, 92.96it/s, loss=0.149]

Epoch  88 | Train F1=0.9674 | Val F1=0.9301

Epoch 89: 100%|██████████| 133/133 [00:01<00:00, 100.53it/s, loss=0.232]

Epoch  89 | Train F1=0.9559 | Val F1=0.9261

Epoch 90: 100%|██████████| 133/133 [00:01<00:00, 100.53it/s, loss=0.218]

Epoch  90 | Train F1=0.9573 | Val F1=0.9229

Epoch 91: 100%|██████████| 133/133 [00:01<00:00, 98.95it/s, loss=0.166]

Epoch  91 | Train F1=0.9578 | Val F1=0.9237

Epoch 92: 100%|██████████| 133/133 [00:01<00:00, 83.56it/s, loss=0.339]

Epoch  92 | Train F1=0.9583 | Val F1=0.9251

Epoch 93: 100%|██████████| 133/133 [00:01<00:00, 78.20it/s, loss=0.203]

Epoch  93 | Train F1=0.9600 | Val F1=0.9285

Epoch 94: 100%|██████████| 133/133 [00:01<00:00, 80.78it/s, loss=0.29]

Epoch  94 | Train F1=0.9579 | Val F1=0.9178

Epoch 95: 100%|██████████| 133/133 [00:01<00:00, 96.70it/s, loss=0.158]

Epoch  95 | Train F1=0.9585 | Val F1=0.9246

Epoch 96: 100%|██████████| 133/133 [00:01<00:00, 96.40it/s, loss=0.282]

Epoch  96 | Train F1=0.9647 | Val F1=0.9305

Epoch 97: 100%|██████████| 133/133 [00:01<00:00, 96.64it/s, loss=0.242]

Epoch  97 | Train F1=0.9638 | Val F1=0.9290

Epoch 98: 100%|██████████| 133/133 [00:01<00:00, 97.27it/s, loss=0.115]

Epoch  98 | Train F1=0.9572 | Val F1=0.9242

Epoch 99: 100%|██████████| 133/133 [00:01<00:00, 97.94it/s, loss=0.147]

Epoch  99 | Train F1=0.9632 | Val F1=0.9285

Epoch 100: 100%|██████████| 133/133 [00:01<00:00, 85.30it/s, loss=0.239]

Epoch 100 | Train F1=0.9610 | Val F1=0.9258

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 88.74it/s, loss=1.22]

Epoch   1 | Train F1=0.3826 | Val F1=0.3836

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 96.94it/s, loss=0.981]

Epoch   2 | Train F1=0.5960 | Val F1=0.5772

Epoch 3: 100%|██████████| 132/132 [00:01<00:00, 94.26it/s, loss=1.01]

Epoch   3 | Train F1=0.6561 | Val F1=0.6406

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 92.73it/s, loss=0.726]

Epoch   4 | Train F1=0.6673 | Val F1=0.6555

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 91.92it/s, loss=0.637]

Epoch   5 | Train F1=0.7185 | Val F1=0.7020

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 86.74it/s, loss=0.623]

Epoch   6 | Train F1=0.7755 | Val F1=0.7570

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 82.53it/s, loss=0.587]

Epoch   7 | Train F1=0.7941 | Val F1=0.7774

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 83.61it/s, loss=0.676]

Epoch   8 | Train F1=0.7934 | Val F1=0.7729

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 95.22it/s, loss=0.535]

Epoch   9 | Train F1=0.8108 | Val F1=0.8013

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 89.58it/s, loss=0.558]

Epoch  10 | Train F1=0.8325 | Val F1=0.8118

Epoch 11: 100%|██████████| 132/132 [00:01<00:00, 91.08it/s, loss=0.556]

Epoch  11 | Train F1=0.8477 | Val F1=0.8340

Epoch 12: 100%|██████████| 132/132 [00:01<00:00, 90.97it/s, loss=0.603]

Epoch  12 | Train F1=0.8455 | Val F1=0.8326

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 85.62it/s, loss=0.456]

Epoch  13 | Train F1=0.8510 | Val F1=0.8346

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 80.33it/s, loss=0.481]

Epoch  14 | Train F1=0.8465 | Val F1=0.8289

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 86.32it/s, loss=0.376]

Epoch  15 | Train F1=0.8593 | Val F1=0.8396

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 84.82it/s, loss=0.563]

Epoch  16 | Train F1=0.8639 | Val F1=0.8438

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 92.48it/s, loss=0.417]

Epoch  17 | Train F1=0.8653 | Val F1=0.8445

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 91.86it/s, loss=0.569]

Epoch  18 | Train F1=0.8735 | Val F1=0.8502

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 92.27it/s, loss=0.483]

Epoch  19 | Train F1=0.8683 | Val F1=0.8453

Epoch 20: 100%|██████████| 132/132 [00:01<00:00, 88.02it/s, loss=0.45]

Epoch  20 | Train F1=0.8810 | Val F1=0.8498

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 80.96it/s, loss=0.475]

Epoch  21 | Train F1=0.8733 | Val F1=0.8442

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 79.05it/s, loss=0.466]

Epoch  22 | Train F1=0.8762 | Val F1=0.8483

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 79.50it/s, loss=0.407]

Epoch  23 | Train F1=0.8803 | Val F1=0.8518

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 88.64it/s, loss=0.438]

Epoch  24 | Train F1=0.8889 | Val F1=0.8609

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 93.69it/s, loss=0.413]

Epoch  25 | Train F1=0.8936 | Val F1=0.8640

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 88.92it/s, loss=0.455]

Epoch  26 | Train F1=0.8894 | Val F1=0.8510

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 94.09it/s, loss=0.307]

Epoch  27 | Train F1=0.8916 | Val F1=0.8546

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 92.81it/s, loss=0.453]

Epoch  28 | Train F1=0.8934 | Val F1=0.8571

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 84.09it/s, loss=0.446]

Epoch  29 | Train F1=0.8889 | Val F1=0.8571

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 77.11it/s, loss=0.378]

Epoch  30 | Train F1=0.8984 | Val F1=0.8607

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 75.93it/s, loss=0.434]

Epoch  31 | Train F1=0.9001 | Val F1=0.8656

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 85.83it/s, loss=0.425]

Epoch  32 | Train F1=0.8947 | Val F1=0.8612

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 88.79it/s, loss=0.355]

Epoch  33 | Train F1=0.8995 | Val F1=0.8607

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 88.04it/s, loss=0.483]

Epoch  34 | Train F1=0.9068 | Val F1=0.8728

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 88.38it/s, loss=0.238]

Epoch  35 | Train F1=0.9052 | Val F1=0.8700

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 87.52it/s, loss=0.436]

Epoch  36 | Train F1=0.9024 | Val F1=0.8657

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 87.13it/s, loss=0.429]

Epoch  37 | Train F1=0.9079 | Val F1=0.8692

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 76.81it/s, loss=0.483]

Epoch  38 | Train F1=0.9116 | Val F1=0.8703

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 75.17it/s, loss=0.416]

Epoch  39 | Train F1=0.9137 | Val F1=0.8766

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 87.14it/s, loss=0.472]

Epoch  40 | Train F1=0.9023 | Val F1=0.8616

Epoch 41: 100%|██████████| 132/132 [00:01<00:00, 84.53it/s, loss=0.442]

Epoch  41 | Train F1=0.9084 | Val F1=0.8696

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 83.67it/s, loss=0.333]

Epoch  42 | Train F1=0.9120 | Val F1=0.8681

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 88.12it/s, loss=0.388]

Epoch  43 | Train F1=0.9101 | Val F1=0.8686

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 80.82it/s, loss=0.301]

Epoch  44 | Train F1=0.9111 | Val F1=0.8689

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 77.13it/s, loss=0.402]

Epoch  45 | Train F1=0.9156 | Val F1=0.8695

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 87.10it/s, loss=0.374]

Epoch  46 | Train F1=0.9184 | Val F1=0.8703

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 77.86it/s, loss=0.416]

Epoch  47 | Train F1=0.9159 | Val F1=0.8718

Epoch 48: 100%|██████████| 132/132 [00:01<00:00, 86.15it/s, loss=0.315]

Epoch  48 | Train F1=0.9202 | Val F1=0.8762

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 86.37it/s, loss=0.349]

Epoch  49 | Train F1=0.9189 | Val F1=0.8706

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 90.33it/s, loss=0.351]

Epoch  50 | Train F1=0.9228 | Val F1=0.8701

Epoch 51: 100%|██████████| 132/132 [00:01<00:00, 91.17it/s, loss=0.33]

Epoch  51 | Train F1=0.9235 | Val F1=0.8767

Epoch 52: 100%|██████████| 132/132 [00:01<00:00, 80.25it/s, loss=0.39]

Epoch  52 | Train F1=0.9228 | Val F1=0.8792

Epoch 53: 100%|██████████| 132/132 [00:01<00:00, 74.45it/s, loss=0.239]

Epoch  53 | Train F1=0.9255 | Val F1=0.8760

Epoch 54: 100%|██████████| 132/132 [00:01<00:00, 85.26it/s, loss=0.39]

Epoch  54 | Train F1=0.9233 | Val F1=0.8734

Epoch 55: 100%|██████████| 132/132 [00:01<00:00, 87.73it/s, loss=0.265]

Epoch  55 | Train F1=0.9278 | Val F1=0.8772

Epoch 56: 100%|██████████| 132/132 [00:01<00:00, 92.90it/s, loss=0.243]

Epoch  56 | Train F1=0.9251 | Val F1=0.8719

Epoch 57: 100%|██████████| 132/132 [00:01<00:00, 89.62it/s, loss=0.294]

Epoch  57 | Train F1=0.9297 | Val F1=0.8765

Epoch 58: 100%|██████████| 132/132 [00:01<00:00, 87.85it/s, loss=0.404]

Epoch  58 | Train F1=0.9278 | Val F1=0.8753

Epoch 59: 100%|██████████| 132/132 [00:01<00:00, 89.40it/s, loss=0.287]

Epoch  59 | Train F1=0.9263 | Val F1=0.8750

Epoch 60: 100%|██████████| 132/132 [00:01<00:00, 75.49it/s, loss=0.348]

Epoch  60 | Train F1=0.9274 | Val F1=0.8745

Epoch 61: 100%|██████████| 132/132 [00:01<00:00, 85.79it/s, loss=0.349]

Epoch  61 | Train F1=0.9272 | Val F1=0.8805

Epoch 62: 100%|██████████| 132/132 [00:01<00:00, 84.82it/s, loss=0.353]

Epoch  62 | Train F1=0.9323 | Val F1=0.8743

Epoch 63: 100%|██████████| 132/132 [00:01<00:00, 77.04it/s, loss=0.368]

Epoch  63 | Train F1=0.9321 | Val F1=0.8809

Epoch 64: 100%|██████████| 132/132 [00:01<00:00, 87.20it/s, loss=0.447]

Epoch  64 | Train F1=0.9311 | Val F1=0.8752

Epoch 65: 100%|██████████| 132/132 [00:01<00:00, 85.44it/s, loss=0.41]

Epoch  65 | Train F1=0.9349 | Val F1=0.8770

Epoch 66: 100%|██████████| 132/132 [00:01<00:00, 85.28it/s, loss=0.246]

Epoch  66 | Train F1=0.9328 | Val F1=0.8762

Epoch 67: 100%|██████████| 132/132 [00:01<00:00, 86.26it/s, loss=0.352]

Epoch  67 | Train F1=0.9344 | Val F1=0.8766

Epoch 68: 100%|██████████| 132/132 [00:01<00:00, 86.82it/s, loss=0.301]

Epoch  68 | Train F1=0.9369 | Val F1=0.8759

Epoch 69: 100%|██████████| 132/132 [00:01<00:00, 82.86it/s, loss=0.293]

Epoch  69 | Train F1=0.9370 | Val F1=0.8775

Epoch 70: 100%|██████████| 132/132 [00:01<00:00, 88.05it/s, loss=0.337]

Epoch  70 | Train F1=0.9344 | Val F1=0.8768

Epoch 71: 100%|██████████| 132/132 [00:01<00:00, 82.45it/s, loss=0.265]

Epoch  71 | Train F1=0.9389 | Val F1=0.8801

Epoch 72: 100%|██████████| 132/132 [00:01<00:00, 85.44it/s, loss=0.396]

Epoch  72 | Train F1=0.9380 | Val F1=0.8802

Epoch 73: 100%|██████████| 132/132 [00:01<00:00, 83.09it/s, loss=0.271]

Epoch  73 | Train F1=0.9392 | Val F1=0.8766

Epoch 74: 100%|██████████| 132/132 [00:01<00:00, 83.99it/s, loss=0.244]

Epoch  74 | Train F1=0.9380 | Val F1=0.8706

Epoch 75: 100%|██████████| 132/132 [00:01<00:00, 83.83it/s, loss=0.321]

Epoch  75 | Train F1=0.9374 | Val F1=0.8715

Epoch 76: 100%|██████████| 132/132 [00:01<00:00, 82.10it/s, loss=0.284]

Epoch  76 | Train F1=0.9403 | Val F1=0.8756

Epoch 77: 100%|██████████| 132/132 [00:01<00:00, 76.70it/s, loss=0.19]

Epoch  77 | Train F1=0.9417 | Val F1=0.8770

Epoch 78: 100%|██████████| 132/132 [00:01<00:00, 77.27it/s, loss=0.445]

Epoch  78 | Train F1=0.9390 | Val F1=0.8760

Epoch 79: 100%|██████████| 132/132 [00:01<00:00, 77.10it/s, loss=0.571]

Epoch  79 | Train F1=0.9413 | Val F1=0.8796

Epoch 80: 100%|██████████| 132/132 [00:01<00:00, 88.76it/s, loss=0.244]

Epoch  80 | Train F1=0.9409 | Val F1=0.8761

Epoch 81: 100%|██████████| 132/132 [00:01<00:00, 88.04it/s, loss=0.32]

Epoch  81 | Train F1=0.9434 | Val F1=0.8851

Epoch 82: 100%|██████████| 132/132 [00:01<00:00, 85.87it/s, loss=0.246]

Epoch  82 | Train F1=0.9382 | Val F1=0.8676

Epoch 83: 100%|██████████| 132/132 [00:01<00:00, 86.61it/s, loss=0.391]

Epoch  83 | Train F1=0.9401 | Val F1=0.8775

Epoch 84: 100%|██████████| 132/132 [00:01<00:00, 80.36it/s, loss=0.28]

Epoch  84 | Train F1=0.9458 | Val F1=0.8828

Epoch 85: 100%|██████████| 132/132 [00:01<00:00, 77.09it/s, loss=0.284]

Epoch  85 | Train F1=0.9491 | Val F1=0.8777

Epoch 86: 100%|██████████| 132/132 [00:01<00:00, 68.15it/s, loss=0.238]

Epoch  86 | Train F1=0.9458 | Val F1=0.8783

Epoch 87: 100%|██████████| 132/132 [00:01<00:00, 84.56it/s, loss=0.257]

Epoch  87 | Train F1=0.9432 | Val F1=0.8789

Epoch 88: 100%|██████████| 132/132 [00:01<00:00, 84.41it/s, loss=0.423]

Epoch  88 | Train F1=0.9457 | Val F1=0.8789

Epoch 89: 100%|██████████| 132/132 [00:01<00:00, 83.10it/s, loss=0.531]

Epoch  89 | Train F1=0.9479 | Val F1=0.8837

Epoch 90: 100%|██████████| 132/132 [00:01<00:00, 81.83it/s, loss=0.238]

Epoch  90 | Train F1=0.9480 | Val F1=0.8822

Epoch 91: 100%|██████████| 132/132 [00:01<00:00, 85.91it/s, loss=0.379]

Epoch  91 | Train F1=0.9490 | Val F1=0.8823

Epoch 92: 100%|██████████| 132/132 [00:01<00:00, 81.61it/s, loss=0.299]

Epoch  92 | Train F1=0.9451 | Val F1=0.8720

Epoch 93: 100%|██████████| 132/132 [00:01<00:00, 74.08it/s, loss=0.392]

Epoch  93 | Train F1=0.9502 | Val F1=0.8843

Epoch 94: 100%|██████████| 132/132 [00:01<00:00, 68.81it/s, loss=0.205]

Epoch  94 | Train F1=0.9506 | Val F1=0.8830

Epoch 95: 100%|██████████| 132/132 [00:01<00:00, 83.15it/s, loss=0.316]

Epoch  95 | Train F1=0.9508 | Val F1=0.8797

Epoch 96: 100%|██████████| 132/132 [00:01<00:00, 82.02it/s, loss=0.247]

Epoch  96 | Train F1=0.9508 | Val F1=0.8808

Epoch 97: 100%|██████████| 132/132 [00:01<00:00, 86.04it/s, loss=0.267]

Epoch  97 | Train F1=0.9494 | Val F1=0.8798

Epoch 98: 100%|██████████| 132/132 [00:01<00:00, 86.77it/s, loss=0.326]

Epoch  98 | Train F1=0.9510 | Val F1=0.8806

Epoch 99: 100%|██████████| 132/132 [00:01<00:00, 81.29it/s, loss=0.395]

Epoch  99 | Train F1=0.9511 | Val F1=0.8789

Epoch 100: 100%|██████████| 132/132 [00:01<00:00, 79.11it/s, loss=0.343]

Epoch 100 | Train F1=0.9536 | Val F1=0.8814

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 83.75it/s, loss=1.03]

Epoch   1 | Train F1=0.5007 | Val F1=0.4998

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 87.58it/s, loss=0.68]

Epoch   2 | Train F1=0.5892 | Val F1=0.5836

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 85.16it/s, loss=0.75]

Epoch   3 | Train F1=0.6026 | Val F1=0.5902

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 85.52it/s, loss=0.925]

Epoch   4 | Train F1=0.6313 | Val F1=0.6019

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 85.24it/s, loss=0.747]

Epoch   5 | Train F1=0.6811 | Val F1=0.6616

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 81.68it/s, loss=0.59]

Epoch   6 | Train F1=0.7243 | Val F1=0.7001

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 78.35it/s, loss=0.464]

Epoch   7 | Train F1=0.7632 | Val F1=0.7338

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 79.36it/s, loss=0.683]

Epoch   8 | Train F1=0.7876 | Val F1=0.7684

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 88.96it/s, loss=0.557]

Epoch   9 | Train F1=0.8051 | Val F1=0.7877

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 89.21it/s, loss=0.599]

Epoch  10 | Train F1=0.8081 | Val F1=0.7945

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 87.55it/s, loss=0.493]

Epoch  11 | Train F1=0.8196 | Val F1=0.7924

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 87.07it/s, loss=0.439]

Epoch  12 | Train F1=0.8285 | Val F1=0.8052

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 77.44it/s, loss=0.496]

Epoch  13 | Train F1=0.8413 | Val F1=0.8109

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 78.07it/s, loss=0.358]

Epoch  14 | Train F1=0.8436 | Val F1=0.8195

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 76.17it/s, loss=0.421]

Epoch  15 | Train F1=0.8433 | Val F1=0.8113

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 86.47it/s, loss=0.421]

Epoch  16 | Train F1=0.8551 | Val F1=0.8240

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 88.50it/s, loss=0.462]

Epoch  17 | Train F1=0.8525 | Val F1=0.8228

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 86.71it/s, loss=0.481]

Epoch  18 | Train F1=0.8569 | Val F1=0.8223

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 86.60it/s, loss=0.532]

Epoch  19 | Train F1=0.8559 | Val F1=0.8196

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 89.37it/s, loss=0.439]

Epoch  20 | Train F1=0.8528 | Val F1=0.8194

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 73.38it/s, loss=0.421]

Epoch  21 | Train F1=0.8636 | Val F1=0.8286

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 89.36it/s, loss=0.39]

Epoch  22 | Train F1=0.8599 | Val F1=0.8279

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 82.50it/s, loss=0.317]

Epoch  23 | Train F1=0.8661 | Val F1=0.8305

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 91.42it/s, loss=0.459]

Epoch  24 | Train F1=0.8695 | Val F1=0.8257

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 84.98it/s, loss=0.374]

Epoch  25 | Train F1=0.8721 | Val F1=0.8311

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 84.36it/s, loss=0.507]

Epoch  26 | Train F1=0.8787 | Val F1=0.8348

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 84.73it/s, loss=0.468]

Epoch  27 | Train F1=0.8763 | Val F1=0.8395

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 86.67it/s, loss=0.359]

Epoch  28 | Train F1=0.8701 | Val F1=0.8329

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 72.05it/s, loss=0.31]

Epoch  29 | Train F1=0.8795 | Val F1=0.8372

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 84.85it/s, loss=0.429]

Epoch  30 | Train F1=0.8691 | Val F1=0.8276

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 80.30it/s, loss=0.497]

Epoch  31 | Train F1=0.8795 | Val F1=0.8315

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 86.40it/s, loss=0.716]

Epoch  32 | Train F1=0.8825 | Val F1=0.8384

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 86.25it/s, loss=0.387]

Epoch  33 | Train F1=0.8813 | Val F1=0.8379

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 86.48it/s, loss=0.4]

Epoch  34 | Train F1=0.8780 | Val F1=0.8374

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 84.85it/s, loss=0.646]

Epoch  35 | Train F1=0.8838 | Val F1=0.8371

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 79.67it/s, loss=0.414]

Epoch  36 | Train F1=0.8829 | Val F1=0.8349

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 77.71it/s, loss=0.389]

Epoch  37 | Train F1=0.8841 | Val F1=0.8340

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 85.96it/s, loss=0.333]

Epoch  38 | Train F1=0.8825 | Val F1=0.8395

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 77.29it/s, loss=0.654]

Epoch  39 | Train F1=0.8917 | Val F1=0.8476

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 86.64it/s, loss=0.387]

Epoch  40 | Train F1=0.8938 | Val F1=0.8423

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 86.52it/s, loss=0.339]

Epoch  41 | Train F1=0.8943 | Val F1=0.8438

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 85.14it/s, loss=0.335]

Epoch  42 | Train F1=0.8935 | Val F1=0.8448

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 87.75it/s, loss=0.319]

Epoch  43 | Train F1=0.8959 | Val F1=0.8465

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 73.68it/s, loss=0.398]

Epoch  44 | Train F1=0.8964 | Val F1=0.8486

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 80.59it/s, loss=0.337]

Epoch  45 | Train F1=0.8904 | Val F1=0.8435

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 85.59it/s, loss=0.27]

Epoch  46 | Train F1=0.8958 | Val F1=0.8474

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 78.14it/s, loss=0.493]

Epoch  47 | Train F1=0.8970 | Val F1=0.8428

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 82.39it/s, loss=0.318]

Epoch  48 | Train F1=0.8967 | Val F1=0.8449

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 85.27it/s, loss=0.367]

Epoch  49 | Train F1=0.9027 | Val F1=0.8479

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 85.15it/s, loss=0.485]

Epoch  50 | Train F1=0.8961 | Val F1=0.8411

Epoch 51: 100%|██████████| 133/133 [00:01<00:00, 83.48it/s, loss=0.285]

Epoch  51 | Train F1=0.8890 | Val F1=0.8411

Epoch 52: 100%|██████████| 133/133 [00:01<00:00, 80.42it/s, loss=0.224]

Epoch  52 | Train F1=0.9023 | Val F1=0.8510

Epoch 53: 100%|██████████| 133/133 [00:01<00:00, 80.07it/s, loss=0.342]

Epoch  53 | Train F1=0.9035 | Val F1=0.8464

Epoch 54: 100%|██████████| 133/133 [00:01<00:00, 88.91it/s, loss=0.269]

Epoch  54 | Train F1=0.9047 | Val F1=0.8501

Epoch 55: 100%|██████████| 133/133 [00:01<00:00, 74.63it/s, loss=0.318]

Epoch  55 | Train F1=0.9052 | Val F1=0.8494

Epoch 56: 100%|██████████| 133/133 [00:01<00:00, 87.25it/s, loss=0.337]

Epoch  56 | Train F1=0.9009 | Val F1=0.8496

Epoch 57: 100%|██████████| 133/133 [00:01<00:00, 84.58it/s, loss=0.323]

Epoch  57 | Train F1=0.9043 | Val F1=0.8493

Epoch 58: 100%|██████████| 133/133 [00:01<00:00, 83.22it/s, loss=0.284]

Epoch  58 | Train F1=0.9029 | Val F1=0.8462

Epoch 59: 100%|██████████| 133/133 [00:01<00:00, 88.66it/s, loss=0.328]

Epoch  59 | Train F1=0.9058 | Val F1=0.8457

Epoch 60: 100%|██████████| 133/133 [00:01<00:00, 80.15it/s, loss=0.289]

Epoch  60 | Train F1=0.9077 | Val F1=0.8462

Epoch 61: 100%|██████████| 133/133 [00:01<00:00, 80.16it/s, loss=0.187]

Epoch  61 | Train F1=0.9048 | Val F1=0.8499

Epoch 62: 100%|██████████| 133/133 [00:01<00:00, 78.44it/s, loss=0.537]

Epoch  62 | Train F1=0.9114 | Val F1=0.8501

Epoch 63: 100%|██████████| 133/133 [00:01<00:00, 77.68it/s, loss=0.421]

Epoch  63 | Train F1=0.9023 | Val F1=0.8434

Epoch 64: 100%|██████████| 133/133 [00:01<00:00, 84.79it/s, loss=0.6]

Epoch  64 | Train F1=0.9121 | Val F1=0.8583

Epoch 65: 100%|██████████| 133/133 [00:01<00:00, 89.79it/s, loss=0.367]

Epoch  65 | Train F1=0.9076 | Val F1=0.8440

Epoch 66: 100%|██████████| 133/133 [00:01<00:00, 82.96it/s, loss=0.248]

Epoch  66 | Train F1=0.9112 | Val F1=0.8467

Epoch 67: 100%|██████████| 133/133 [00:01<00:00, 88.89it/s, loss=0.207]

Epoch  67 | Train F1=0.9159 | Val F1=0.8488

Epoch 68: 100%|██████████| 133/133 [00:01<00:00, 75.32it/s, loss=0.268]

Epoch  68 | Train F1=0.9133 | Val F1=0.8543

Epoch 69: 100%|██████████| 133/133 [00:01<00:00, 82.44it/s, loss=0.312]

Epoch  69 | Train F1=0.9167 | Val F1=0.8522

Epoch 70: 100%|██████████| 133/133 [00:01<00:00, 87.35it/s, loss=0.434]

Epoch  70 | Train F1=0.9157 | Val F1=0.8539

Epoch 71: 100%|██████████| 133/133 [00:01<00:00, 80.07it/s, loss=0.39]

Epoch  71 | Train F1=0.9186 | Val F1=0.8568

Epoch 72: 100%|██████████| 133/133 [00:01<00:00, 82.61it/s, loss=0.256]

Epoch  72 | Train F1=0.9138 | Val F1=0.8510

Epoch 73: 100%|██████████| 133/133 [00:01<00:00, 89.21it/s, loss=0.347]

Epoch  73 | Train F1=0.9221 | Val F1=0.8567

Epoch 74: 100%|██████████| 133/133 [00:01<00:00, 92.07it/s, loss=0.398]

Epoch  74 | Train F1=0.9150 | Val F1=0.8519

Epoch 75: 100%|██████████| 133/133 [00:01<00:00, 83.90it/s, loss=0.417]

Epoch  75 | Train F1=0.9195 | Val F1=0.8521

Epoch 76: 100%|██████████| 133/133 [00:01<00:00, 76.98it/s, loss=0.255]

Epoch  76 | Train F1=0.9191 | Val F1=0.8515

Epoch 77: 100%|██████████| 133/133 [00:02<00:00, 61.46it/s, loss=0.297]

Epoch  77 | Train F1=0.9178 | Val F1=0.8560

Epoch 78: 100%|██████████| 133/133 [00:01<00:00, 81.57it/s, loss=0.656]

Epoch  78 | Train F1=0.9221 | Val F1=0.8560

Epoch 79: 100%|██████████| 133/133 [00:01<00:00, 87.94it/s, loss=0.348]

Epoch  79 | Train F1=0.9162 | Val F1=0.8504

Epoch 80: 100%|██████████| 133/133 [00:01<00:00, 84.18it/s, loss=0.314]

Epoch  80 | Train F1=0.9225 | Val F1=0.8571

Epoch 81: 100%|██████████| 133/133 [00:01<00:00, 87.38it/s, loss=0.253]

Epoch  81 | Train F1=0.9182 | Val F1=0.8513

Epoch 82: 100%|██████████| 133/133 [00:01<00:00, 84.90it/s, loss=0.359]

Epoch  82 | Train F1=0.9234 | Val F1=0.8532

Epoch 83: 100%|██████████| 133/133 [00:01<00:00, 86.02it/s, loss=0.468]

Epoch  83 | Train F1=0.9207 | Val F1=0.8515

Epoch 84: 100%|██████████| 133/133 [00:01<00:00, 85.96it/s, loss=0.37]

Epoch  84 | Train F1=0.9245 | Val F1=0.8565

Epoch 85: 100%|██████████| 133/133 [00:01<00:00, 84.75it/s, loss=0.383]

Epoch  85 | Train F1=0.9233 | Val F1=0.8527

Epoch 86: 100%|██████████| 133/133 [00:01<00:00, 74.55it/s, loss=0.372]

Epoch  86 | Train F1=0.9248 | Val F1=0.8557

Epoch 87: 100%|██████████| 133/133 [00:01<00:00, 87.57it/s, loss=0.341]

Epoch  87 | Train F1=0.9190 | Val F1=0.8528

Epoch 88: 100%|██████████| 133/133 [00:01<00:00, 85.73it/s, loss=0.187]

Epoch  88 | Train F1=0.9217 | Val F1=0.8565

Epoch 89: 100%|██████████| 133/133 [00:01<00:00, 84.99it/s, loss=0.406]

Epoch  89 | Train F1=0.9294 | Val F1=0.8570

Epoch 90: 100%|██████████| 133/133 [00:01<00:00, 87.04it/s, loss=0.211]

Epoch  90 | Train F1=0.9234 | Val F1=0.8547

Epoch 91: 100%|██████████| 133/133 [00:01<00:00, 83.70it/s, loss=0.317]

Epoch  91 | Train F1=0.9238 | Val F1=0.8516

Epoch 92: 100%|██████████| 133/133 [00:01<00:00, 83.33it/s, loss=0.352]

Epoch  92 | Train F1=0.9272 | Val F1=0.8554

Epoch 93: 100%|██████████| 133/133 [00:01<00:00, 82.66it/s, loss=0.226]

Epoch  93 | Train F1=0.9232 | Val F1=0.8476

Epoch 94: 100%|██████████| 133/133 [00:01<00:00, 76.24it/s, loss=0.357]

Epoch  94 | Train F1=0.9240 | Val F1=0.8465

Epoch 95: 100%|██████████| 133/133 [00:01<00:00, 86.79it/s, loss=0.378]

Epoch  95 | Train F1=0.9289 | Val F1=0.8548

Epoch 96: 100%|██████████| 133/133 [00:01<00:00, 91.35it/s, loss=0.171]

Epoch  96 | Train F1=0.9279 | Val F1=0.8502

Epoch 97: 100%|██████████| 133/133 [00:01<00:00, 83.79it/s, loss=0.235]

Epoch  97 | Train F1=0.9306 | Val F1=0.8545

Epoch 98: 100%|██████████| 133/133 [00:01<00:00, 88.30it/s, loss=0.264]

Epoch  98 | Train F1=0.9307 | Val F1=0.8575

Epoch 99: 100%|██████████| 133/133 [00:01<00:00, 81.18it/s, loss=0.275]

Epoch  99 | Train F1=0.9289 | Val F1=0.8540

Epoch 100: 100%|██████████| 133/133 [00:01<00:00, 77.91it/s, loss=0.268]

Epoch 100 | Train F1=0.9276 | Val F1=0.8526

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 82.92it/s, loss=0.877]

Epoch   1 | Train F1=0.5266 | Val F1=0.5247

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 83.37it/s, loss=0.606]

Epoch   2 | Train F1=0.7782 | Val F1=0.7673

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 86.82it/s, loss=0.731]

Epoch   3 | Train F1=0.8256 | Val F1=0.8155

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 83.75it/s, loss=0.49]

Epoch   4 | Train F1=0.8610 | Val F1=0.8452

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 81.84it/s, loss=0.476]

Epoch   5 | Train F1=0.9003 | Val F1=0.8875

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 79.21it/s, loss=0.56]

Epoch   6 | Train F1=0.9130 | Val F1=0.8982

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 77.99it/s, loss=0.309]

Epoch   7 | Train F1=0.9129 | Val F1=0.8996

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 72.33it/s, loss=0.539]

Epoch   8 | Train F1=0.9202 | Val F1=0.9057

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 87.64it/s, loss=0.42]

Epoch   9 | Train F1=0.9225 | Val F1=0.9052

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 83.25it/s, loss=0.247]

Epoch  10 | Train F1=0.9279 | Val F1=0.9132

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 82.23it/s, loss=0.543]

Epoch  11 | Train F1=0.9300 | Val F1=0.9097

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 82.23it/s, loss=0.26]

Epoch  12 | Train F1=0.9332 | Val F1=0.9135

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 73.66it/s, loss=0.258]

Epoch  13 | Train F1=0.9376 | Val F1=0.9198

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 84.14it/s, loss=0.406]

Epoch  14 | Train F1=0.9394 | Val F1=0.9192

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 73.91it/s, loss=0.171]

Epoch  15 | Train F1=0.9372 | Val F1=0.9160

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 85.85it/s, loss=0.292]

Epoch  16 | Train F1=0.9381 | Val F1=0.9176

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 83.41it/s, loss=0.243]

Epoch  17 | Train F1=0.9430 | Val F1=0.9210

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 82.30it/s, loss=0.439]

Epoch  18 | Train F1=0.9437 | Val F1=0.9236

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 83.10it/s, loss=0.336]

Epoch  19 | Train F1=0.9407 | Val F1=0.9181

Epoch 20: 100%|██████████| 133/133 [00:02<00:00, 60.39it/s, loss=0.147]

Epoch  20 | Train F1=0.9481 | Val F1=0.9256

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 85.27it/s, loss=0.33]

Epoch  21 | Train F1=0.9457 | Val F1=0.9242

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 73.91it/s, loss=0.17]

Epoch  22 | Train F1=0.9471 | Val F1=0.9231

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 84.62it/s, loss=0.0619]

Epoch  23 | Train F1=0.9456 | Val F1=0.9221

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 83.89it/s, loss=0.238]

Epoch  24 | Train F1=0.9484 | Val F1=0.9249

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 85.64it/s, loss=0.296]

Epoch  25 | Train F1=0.9490 | Val F1=0.9263

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 80.88it/s, loss=0.387]

Epoch  26 | Train F1=0.9484 | Val F1=0.9265

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 73.64it/s, loss=0.296]

Epoch  27 | Train F1=0.9505 | Val F1=0.9284

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 76.88it/s, loss=0.335]

Epoch  28 | Train F1=0.9531 | Val F1=0.9295

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 80.27it/s, loss=0.185]

Epoch  29 | Train F1=0.9495 | Val F1=0.9265

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 77.64it/s, loss=0.14]

Epoch  30 | Train F1=0.9560 | Val F1=0.9296

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 83.84it/s, loss=0.327]

Epoch  31 | Train F1=0.9545 | Val F1=0.9299

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 86.70it/s, loss=0.208]

Epoch  32 | Train F1=0.9549 | Val F1=0.9286

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 82.92it/s, loss=0.321]

Epoch  33 | Train F1=0.9540 | Val F1=0.9286

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 91.44it/s, loss=0.172]

Epoch  34 | Train F1=0.9587 | Val F1=0.9312

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 86.25it/s, loss=0.193]

Epoch  35 | Train F1=0.9566 | Val F1=0.9294

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 72.05it/s, loss=0.441]

Epoch  36 | Train F1=0.9586 | Val F1=0.9309

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 81.50it/s, loss=0.197]

Epoch  37 | Train F1=0.9555 | Val F1=0.9289

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 76.88it/s, loss=0.0964]

Epoch  38 | Train F1=0.9586 | Val F1=0.9311

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 85.33it/s, loss=0.13]

Epoch  39 | Train F1=0.9577 | Val F1=0.9307

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 85.36it/s, loss=0.288]

Epoch  40 | Train F1=0.9542 | Val F1=0.9292

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 88.65it/s, loss=0.145]

Epoch  41 | Train F1=0.9575 | Val F1=0.9317

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 80.09it/s, loss=0.177]

Epoch  42 | Train F1=0.9602 | Val F1=0.9301

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 86.04it/s, loss=0.136]

Epoch  43 | Train F1=0.9584 | Val F1=0.9288

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 85.73it/s, loss=0.165]

Epoch  44 | Train F1=0.9594 | Val F1=0.9294

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 73.39it/s, loss=0.12]

Epoch  45 | Train F1=0.9599 | Val F1=0.9283

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 89.20it/s, loss=0.155]

Epoch  46 | Train F1=0.9587 | Val F1=0.9290

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 82.86it/s, loss=0.336]

Epoch  47 | Train F1=0.9623 | Val F1=0.9323

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 85.38it/s, loss=0.0936]

Epoch  48 | Train F1=0.9614 | Val F1=0.9294

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 82.62it/s, loss=0.113]

Epoch  49 | Train F1=0.9631 | Val F1=0.9330

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 75.86it/s, loss=0.0862]

Epoch  50 | Train F1=0.9630 | Val F1=0.9277

Epoch 51: 100%|██████████| 133/133 [00:01<00:00, 79.93it/s, loss=0.212]

Epoch  51 | Train F1=0.9602 | Val F1=0.9264

Epoch 52: 100%|██████████| 133/133 [00:01<00:00, 87.93it/s, loss=0.413]

Epoch  52 | Train F1=0.9631 | Val F1=0.9288

Epoch 53: 100%|██████████| 133/133 [00:01<00:00, 71.88it/s, loss=0.186]

Epoch  53 | Train F1=0.9662 | Val F1=0.9329

Epoch 54: 100%|██████████| 133/133 [00:01<00:00, 87.51it/s, loss=0.13]

Epoch  54 | Train F1=0.9638 | Val F1=0.9315

Epoch 55: 100%|██████████| 133/133 [00:01<00:00, 83.59it/s, loss=0.204]

Epoch  55 | Train F1=0.9664 | Val F1=0.9336

Epoch 56: 100%|██████████| 133/133 [00:01<00:00, 85.58it/s, loss=0.17]

Epoch  56 | Train F1=0.9664 | Val F1=0.9320

Epoch 57: 100%|██████████| 133/133 [00:01<00:00, 86.23it/s, loss=0.136]

Epoch  57 | Train F1=0.9658 | Val F1=0.9291

Epoch 58: 100%|██████████| 133/133 [00:01<00:00, 68.26it/s, loss=0.329]

Epoch  58 | Train F1=0.9664 | Val F1=0.9317

Epoch 59: 100%|██████████| 133/133 [00:01<00:00, 70.72it/s, loss=0.088]

Epoch  59 | Train F1=0.9607 | Val F1=0.9282

Epoch 60: 100%|██████████| 133/133 [00:01<00:00, 86.41it/s, loss=0.126]

Epoch  60 | Train F1=0.9656 | Val F1=0.9341

Epoch 61: 100%|██████████| 133/133 [00:01<00:00, 82.75it/s, loss=0.266]

Epoch  61 | Train F1=0.9710 | Val F1=0.9346

Epoch 62: 100%|██████████| 133/133 [00:01<00:00, 89.25it/s, loss=0.198]

Epoch  62 | Train F1=0.9681 | Val F1=0.9323

Epoch 63: 100%|██████████| 133/133 [00:01<00:00, 86.76it/s, loss=0.291]

Epoch  63 | Train F1=0.9705 | Val F1=0.9327

Epoch 64: 100%|██████████| 133/133 [00:01<00:00, 83.78it/s, loss=0.153]

Epoch  64 | Train F1=0.9690 | Val F1=0.9322

Epoch 65: 100%|██████████| 133/133 [00:01<00:00, 73.19it/s, loss=0.0899]

Epoch  65 | Train F1=0.9667 | Val F1=0.9307

Epoch 66: 100%|██████████| 133/133 [00:01<00:00, 77.26it/s, loss=0.146]

Epoch  66 | Train F1=0.9723 | Val F1=0.9336

Epoch 67: 100%|██████████| 133/133 [00:01<00:00, 85.19it/s, loss=0.183]

Epoch  67 | Train F1=0.9668 | Val F1=0.9330

Epoch 68: 100%|██████████| 133/133 [00:01<00:00, 70.02it/s, loss=0.109]

Epoch  68 | Train F1=0.9695 | Val F1=0.9326

Epoch 69: 100%|██████████| 133/133 [00:01<00:00, 82.54it/s, loss=0.0744]

Epoch  69 | Train F1=0.9730 | Val F1=0.9339

Epoch 70: 100%|██████████| 133/133 [00:01<00:00, 85.88it/s, loss=0.13]

Epoch  70 | Train F1=0.9722 | Val F1=0.9350

Epoch 71: 100%|██████████| 133/133 [00:01<00:00, 87.27it/s, loss=0.231]

Epoch  71 | Train F1=0.9663 | Val F1=0.9292

Epoch 72: 100%|██████████| 133/133 [00:01<00:00, 85.35it/s, loss=0.182]

Epoch  72 | Train F1=0.9715 | Val F1=0.9319

Epoch 73: 100%|██████████| 133/133 [00:01<00:00, 74.38it/s, loss=0.289]

Epoch  73 | Train F1=0.9699 | Val F1=0.9317

Epoch 74: 100%|██████████| 133/133 [00:01<00:00, 85.99it/s, loss=0.188]

Epoch  74 | Train F1=0.9714 | Val F1=0.9329

Epoch 75: 100%|██████████| 133/133 [00:01<00:00, 71.11it/s, loss=0.184]

Epoch  75 | Train F1=0.9746 | Val F1=0.9378

Epoch 76: 100%|██████████| 133/133 [00:01<00:00, 81.95it/s, loss=0.0983]

Epoch  76 | Train F1=0.9717 | Val F1=0.9326

Epoch 77: 100%|██████████| 133/133 [00:01<00:00, 82.37it/s, loss=0.284]

Epoch  77 | Train F1=0.9730 | Val F1=0.9342

Epoch 78: 100%|██████████| 133/133 [00:01<00:00, 85.09it/s, loss=0.483]

Epoch  78 | Train F1=0.9747 | Val F1=0.9330

Epoch 79: 100%|██████████| 133/133 [00:01<00:00, 89.14it/s, loss=0.0986]

Epoch  79 | Train F1=0.9723 | Val F1=0.9329

Epoch 80: 100%|██████████| 133/133 [00:01<00:00, 83.74it/s, loss=0.266]

Epoch  80 | Train F1=0.9718 | Val F1=0.9318

Epoch 81: 100%|██████████| 133/133 [00:01<00:00, 72.20it/s, loss=0.128]

Epoch  81 | Train F1=0.9755 | Val F1=0.9357

Epoch 82: 100%|██████████| 133/133 [00:01<00:00, 86.04it/s, loss=0.291]

Epoch  82 | Train F1=0.9723 | Val F1=0.9306

Epoch 83: 100%|██████████| 133/133 [00:01<00:00, 71.03it/s, loss=0.0918]

Epoch  83 | Train F1=0.9720 | Val F1=0.9305

Epoch 84: 100%|██████████| 133/133 [00:01<00:00, 85.26it/s, loss=0.105]

Epoch  84 | Train F1=0.9741 | Val F1=0.9319

Epoch 85: 100%|██████████| 133/133 [00:01<00:00, 87.36it/s, loss=0.152]

Epoch  85 | Train F1=0.9733 | Val F1=0.9338

Epoch 86: 100%|██████████| 133/133 [00:01<00:00, 90.49it/s, loss=0.206]

Epoch  86 | Train F1=0.9790 | Val F1=0.9396

Epoch 87: 100%|██████████| 133/133 [00:01<00:00, 91.95it/s, loss=0.159]

Epoch  87 | Train F1=0.9740 | Val F1=0.9340

Epoch 88: 100%|██████████| 133/133 [00:01<00:00, 79.20it/s, loss=0.309]

Epoch  88 | Train F1=0.9742 | Val F1=0.9319

Epoch 89: 100%|██████████| 133/133 [00:01<00:00, 86.96it/s, loss=0.119]

Epoch  89 | Train F1=0.9749 | Val F1=0.9317

Epoch 90: 100%|██████████| 133/133 [00:01<00:00, 81.60it/s, loss=0.191]

Epoch  90 | Train F1=0.9753 | Val F1=0.9352

Epoch 91: 100%|██████████| 133/133 [00:01<00:00, 85.15it/s, loss=0.178]

Epoch  91 | Train F1=0.9721 | Val F1=0.9317

Epoch 92: 100%|██████████| 133/133 [00:01<00:00, 83.37it/s, loss=0.164]

Epoch  92 | Train F1=0.9760 | Val F1=0.9276

Epoch 93: 100%|██████████| 133/133 [00:01<00:00, 83.13it/s, loss=0.148]

Epoch  93 | Train F1=0.9731 | Val F1=0.9302

Epoch 94: 100%|██████████| 133/133 [00:01<00:00, 91.23it/s, loss=0.204]

Epoch  94 | Train F1=0.9796 | Val F1=0.9351

Epoch 95: 100%|██████████| 133/133 [00:01<00:00, 89.07it/s, loss=0.0916]

Epoch  95 | Train F1=0.9739 | Val F1=0.9348

Epoch 96: 100%|██████████| 133/133 [00:01<00:00, 85.63it/s, loss=0.153]

Epoch  96 | Train F1=0.9777 | Val F1=0.9394

Epoch 97: 100%|██████████| 133/133 [00:01<00:00, 73.14it/s, loss=0.0468]

Epoch  97 | Train F1=0.9744 | Val F1=0.9310

Epoch 98: 100%|██████████| 133/133 [00:01<00:00, 91.04it/s, loss=0.168]

Epoch  98 | Train F1=0.9777 | Val F1=0.9366

Epoch 99: 100%|██████████| 133/133 [00:01<00:00, 74.48it/s, loss=0.1]

Epoch  99 | Train F1=0.9741 | Val F1=0.9349

Epoch 100: 100%|██████████| 133/133 [00:01<00:00, 83.69it/s, loss=0.103]

Epoch 100 | Train F1=0.9787 | Val F1=0.9346

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 83.21it/s, loss=1.2]

Epoch   1 | Train F1=0.4396 | Val F1=0.4324

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 81.96it/s, loss=0.67]

Epoch   2 | Train F1=0.6281 | Val F1=0.6233

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 84.01it/s, loss=0.913]

Epoch   3 | Train F1=0.7314 | Val F1=0.7289

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 81.99it/s, loss=0.499]

Epoch   4 | Train F1=0.7797 | Val F1=0.7690

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 76.36it/s, loss=0.725]

Epoch   5 | Train F1=0.8017 | Val F1=0.7851

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 79.10it/s, loss=0.577]

Epoch   6 | Train F1=0.8309 | Val F1=0.8193

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 91.25it/s, loss=0.415]

Epoch   7 | Train F1=0.8273 | Val F1=0.8188

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 87.07it/s, loss=0.441]

Epoch   8 | Train F1=0.8412 | Val F1=0.8303

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 85.45it/s, loss=0.328]

Epoch   9 | Train F1=0.8581 | Val F1=0.8437

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 87.23it/s, loss=0.359]

Epoch  10 | Train F1=0.8772 | Val F1=0.8656

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 78.26it/s, loss=0.284]

Epoch  11 | Train F1=0.8780 | Val F1=0.8601

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 72.68it/s, loss=0.701]

Epoch  12 | Train F1=0.8885 | Val F1=0.8747

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 85.62it/s, loss=0.273]

Epoch  13 | Train F1=0.8985 | Val F1=0.8814

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 75.77it/s, loss=0.243]

Epoch  14 | Train F1=0.8994 | Val F1=0.8840

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 85.53it/s, loss=0.336]

Epoch  15 | Train F1=0.9047 | Val F1=0.8855

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 91.02it/s, loss=0.326]

Epoch  16 | Train F1=0.9033 | Val F1=0.8901

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 86.46it/s, loss=0.295]

Epoch  17 | Train F1=0.9127 | Val F1=0.8979

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 80.79it/s, loss=0.291]

Epoch  18 | Train F1=0.9117 | Val F1=0.8958

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 74.59it/s, loss=0.514]

Epoch  19 | Train F1=0.9196 | Val F1=0.9030

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 78.21it/s, loss=0.291]

Epoch  20 | Train F1=0.9270 | Val F1=0.9116

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 81.92it/s, loss=0.19]

Epoch  21 | Train F1=0.9252 | Val F1=0.9052

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 87.18it/s, loss=0.277]

Epoch  22 | Train F1=0.9325 | Val F1=0.9144

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 83.79it/s, loss=0.328]

Epoch  23 | Train F1=0.9286 | Val F1=0.9100

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 88.27it/s, loss=0.243]

Epoch  24 | Train F1=0.9325 | Val F1=0.9082

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 82.55it/s, loss=0.124]

Epoch  25 | Train F1=0.9331 | Val F1=0.9098

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 78.75it/s, loss=0.409]

Epoch  26 | Train F1=0.9319 | Val F1=0.9103

Epoch 27: 100%|██████████| 133/133 [00:02<00:00, 62.24it/s, loss=0.247]

Epoch  27 | Train F1=0.9345 | Val F1=0.9156

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 87.23it/s, loss=0.3]

Epoch  28 | Train F1=0.9382 | Val F1=0.9157

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 76.93it/s, loss=0.235]

Epoch  29 | Train F1=0.9333 | Val F1=0.9065

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 82.88it/s, loss=0.304]

Epoch  30 | Train F1=0.9370 | Val F1=0.9115

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 77.01it/s, loss=0.129]

Epoch  31 | Train F1=0.9388 | Val F1=0.9147

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 72.05it/s, loss=0.557]

Epoch  32 | Train F1=0.9339 | Val F1=0.9114

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 76.76it/s, loss=0.282]

Epoch  33 | Train F1=0.9419 | Val F1=0.9222

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 75.91it/s, loss=0.284]

Epoch  34 | Train F1=0.9397 | Val F1=0.9128

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 78.25it/s, loss=0.18]

Epoch  35 | Train F1=0.9424 | Val F1=0.9159

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 74.17it/s, loss=0.303]

Epoch  36 | Train F1=0.9421 | Val F1=0.9177

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 84.72it/s, loss=0.289]

Epoch  37 | Train F1=0.9427 | Val F1=0.9204

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 90.94it/s, loss=0.339]

Epoch  38 | Train F1=0.9457 | Val F1=0.9204

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 87.25it/s, loss=0.317]

Epoch  39 | Train F1=0.9481 | Val F1=0.9177

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 88.56it/s, loss=0.207]

Epoch  40 | Train F1=0.9510 | Val F1=0.9231

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 78.88it/s, loss=0.303]

Epoch  41 | Train F1=0.9502 | Val F1=0.9244

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 82.21it/s, loss=0.45]

Epoch  42 | Train F1=0.9534 | Val F1=0.9280

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 80.65it/s, loss=0.0899]

Epoch  43 | Train F1=0.9501 | Val F1=0.9261

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 79.63it/s, loss=0.269]

Epoch  44 | Train F1=0.9541 | Val F1=0.9248

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 91.23it/s, loss=0.336]

Epoch  45 | Train F1=0.9526 | Val F1=0.9211

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 91.54it/s, loss=0.195]

Epoch  46 | Train F1=0.9567 | Val F1=0.9271

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 89.79it/s, loss=0.309]

Epoch  47 | Train F1=0.9538 | Val F1=0.9216

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 81.59it/s, loss=0.303]

Epoch  48 | Train F1=0.9557 | Val F1=0.9198

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 81.61it/s, loss=0.15]

Epoch  49 | Train F1=0.9509 | Val F1=0.9202

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 75.05it/s, loss=0.271]

Epoch  50 | Train F1=0.9554 | Val F1=0.9253

Epoch 51: 100%|██████████| 133/133 [00:01<00:00, 70.89it/s, loss=0.292]

Epoch  51 | Train F1=0.9535 | Val F1=0.9197

Epoch 52: 100%|██████████| 133/133 [00:01<00:00, 82.98it/s, loss=0.279]

Epoch  52 | Train F1=0.9570 | Val F1=0.9223

Epoch 53: 100%|██████████| 133/133 [00:01<00:00, 93.11it/s, loss=0.34]

Epoch  53 | Train F1=0.9515 | Val F1=0.9197

Epoch 54: 100%|██████████| 133/133 [00:01<00:00, 86.89it/s, loss=0.331]

Epoch  54 | Train F1=0.9504 | Val F1=0.9203

Epoch 55: 100%|██████████| 133/133 [00:01<00:00, 84.07it/s, loss=0.409]

Epoch  55 | Train F1=0.9599 | Val F1=0.9252

Epoch 56: 100%|██████████| 133/133 [00:01<00:00, 88.67it/s, loss=0.188]

Epoch  56 | Train F1=0.9563 | Val F1=0.9257

Epoch 57: 100%|██████████| 133/133 [00:01<00:00, 85.17it/s, loss=0.213]

Epoch  57 | Train F1=0.9617 | Val F1=0.9270

Epoch 58: 100%|██████████| 133/133 [00:01<00:00, 78.45it/s, loss=0.196]

Epoch  58 | Train F1=0.9592 | Val F1=0.9247

Epoch 59: 100%|██████████| 133/133 [00:01<00:00, 94.10it/s, loss=0.191]

Epoch  59 | Train F1=0.9592 | Val F1=0.9260

Epoch 60: 100%|██████████| 133/133 [00:01<00:00, 74.02it/s, loss=0.0982]

Epoch  60 | Train F1=0.9620 | Val F1=0.9281

Epoch 61: 100%|██████████| 133/133 [00:01<00:00, 82.23it/s, loss=0.197]

Epoch  61 | Train F1=0.9596 | Val F1=0.9259

Epoch 62: 100%|██████████| 133/133 [00:01<00:00, 82.62it/s, loss=0.597]

Epoch  62 | Train F1=0.9636 | Val F1=0.9313

Epoch 63: 100%|██████████| 133/133 [00:01<00:00, 86.36it/s, loss=0.538]

Epoch  63 | Train F1=0.9660 | Val F1=0.9265

Epoch 64: 100%|██████████| 133/133 [00:01<00:00, 81.38it/s, loss=0.189]

Epoch  64 | Train F1=0.9628 | Val F1=0.9264

Epoch 65: 100%|██████████| 133/133 [00:01<00:00, 77.09it/s, loss=0.184]

Epoch  65 | Train F1=0.9605 | Val F1=0.9231

Epoch 66: 100%|██████████| 133/133 [00:01<00:00, 67.85it/s, loss=0.425]

Epoch  66 | Train F1=0.9622 | Val F1=0.9255

Epoch 67: 100%|██████████| 133/133 [00:01<00:00, 81.71it/s, loss=0.226]

Epoch  67 | Train F1=0.9625 | Val F1=0.9262

Epoch 68: 100%|██████████| 133/133 [00:01<00:00, 88.35it/s, loss=0.174]

Epoch  68 | Train F1=0.9651 | Val F1=0.9326

Epoch 69: 100%|██████████| 133/133 [00:01<00:00, 86.31it/s, loss=0.167]

Epoch  69 | Train F1=0.9657 | Val F1=0.9280

Epoch 70: 100%|██████████| 133/133 [00:01<00:00, 88.61it/s, loss=0.226]

Epoch  70 | Train F1=0.9671 | Val F1=0.9311

Epoch 71: 100%|██████████| 133/133 [00:01<00:00, 88.29it/s, loss=0.189]

Epoch  71 | Train F1=0.9671 | Val F1=0.9300

Epoch 72: 100%|██████████| 133/133 [00:01<00:00, 84.96it/s, loss=0.501]

Epoch  72 | Train F1=0.9622 | Val F1=0.9280

Epoch 73: 100%|██████████| 133/133 [00:01<00:00, 73.73it/s, loss=0.131]

Epoch  73 | Train F1=0.9648 | Val F1=0.9300

Epoch 74: 100%|██████████| 133/133 [00:01<00:00, 85.02it/s, loss=0.1]

Epoch  74 | Train F1=0.9641 | Val F1=0.9265

Epoch 75: 100%|██████████| 133/133 [00:01<00:00, 73.61it/s, loss=0.267]

Epoch  75 | Train F1=0.9622 | Val F1=0.9244

Epoch 76: 100%|██████████| 133/133 [00:01<00:00, 92.37it/s, loss=0.336]

Epoch  76 | Train F1=0.9680 | Val F1=0.9278

Epoch 77: 100%|██████████| 133/133 [00:01<00:00, 89.59it/s, loss=0.295]

Epoch  77 | Train F1=0.9645 | Val F1=0.9226

Epoch 78: 100%|██████████| 133/133 [00:01<00:00, 88.24it/s, loss=0.218]

Epoch  78 | Train F1=0.9675 | Val F1=0.9328

Epoch 79: 100%|██████████| 133/133 [00:01<00:00, 76.10it/s, loss=0.239]

Epoch  79 | Train F1=0.9694 | Val F1=0.9341

Epoch 80: 100%|██████████| 133/133 [00:01<00:00, 71.85it/s, loss=0.258]

Epoch  80 | Train F1=0.9673 | Val F1=0.9298

Epoch 81: 100%|██████████| 133/133 [00:01<00:00, 78.17it/s, loss=0.0934]

Epoch  81 | Train F1=0.9674 | Val F1=0.9293

Epoch 82: 100%|██████████| 133/133 [00:01<00:00, 93.94it/s, loss=0.231]

Epoch  82 | Train F1=0.9691 | Val F1=0.9296

Epoch 83: 100%|██████████| 133/133 [00:01<00:00, 77.74it/s, loss=0.134]

Epoch  83 | Train F1=0.9671 | Val F1=0.9276

Epoch 84: 100%|██████████| 133/133 [00:01<00:00, 87.91it/s, loss=0.207]

Epoch  84 | Train F1=0.9683 | Val F1=0.9313

Epoch 85: 100%|██████████| 133/133 [00:01<00:00, 88.81it/s, loss=0.209]

Epoch  85 | Train F1=0.9662 | Val F1=0.9293

Epoch 86: 100%|██████████| 133/133 [00:01<00:00, 83.40it/s, loss=0.379]

Epoch  86 | Train F1=0.9719 | Val F1=0.9335

Epoch 87: 100%|██████████| 133/133 [00:01<00:00, 92.12it/s, loss=0.191]

Epoch  87 | Train F1=0.9723 | Val F1=0.9301

Epoch 88: 100%|██████████| 133/133 [00:01<00:00, 82.00it/s, loss=0.337]

Epoch  88 | Train F1=0.9701 | Val F1=0.9248

Epoch 89: 100%|██████████| 133/133 [00:01<00:00, 79.24it/s, loss=0.274]

Epoch  89 | Train F1=0.9694 | Val F1=0.9285

Epoch 90: 100%|██████████| 133/133 [00:01<00:00, 82.63it/s, loss=0.215]

Epoch  90 | Train F1=0.9739 | Val F1=0.9295

Epoch 91: 100%|██████████| 133/133 [00:01<00:00, 70.81it/s, loss=0.285]

Epoch  91 | Train F1=0.9731 | Val F1=0.9363

Epoch 92: 100%|██████████| 133/133 [00:01<00:00, 82.20it/s, loss=0.178]

Epoch  92 | Train F1=0.9730 | Val F1=0.9327

Epoch 93: 100%|██████████| 133/133 [00:01<00:00, 81.65it/s, loss=0.232]

Epoch  93 | Train F1=0.9673 | Val F1=0.9325

Epoch 94: 100%|██████████| 133/133 [00:01<00:00, 84.50it/s, loss=0.083]

Epoch  94 | Train F1=0.9741 | Val F1=0.9373

Epoch 95: 100%|██████████| 133/133 [00:01<00:00, 85.57it/s, loss=0.0826]

Epoch  95 | Train F1=0.9728 | Val F1=0.9333

Epoch 96: 100%|██████████| 133/133 [00:01<00:00, 77.56it/s, loss=0.0811]

Epoch  96 | Train F1=0.9736 | Val F1=0.9301

Epoch 97: 100%|██████████| 133/133 [00:01<00:00, 84.16it/s, loss=0.441]

Epoch  97 | Train F1=0.9704 | Val F1=0.9270

Epoch 98: 100%|██████████| 133/133 [00:01<00:00, 83.18it/s, loss=0.13]

Epoch  98 | Train F1=0.9723 | Val F1=0.9305

Epoch 99: 100%|██████████| 133/133 [00:01<00:00, 77.99it/s, loss=0.232]

Epoch  99 | Train F1=0.9711 | Val F1=0.9309

Epoch 100: 100%|██████████| 133/133 [00:01<00:00, 84.59it/s, loss=0.218]

Epoch 100 | Train F1=0.9757 | Val F1=0.9295

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 86.10it/s, loss=0.942]

Epoch   1 | Train F1=0.4596 | Val F1=0.4489

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 67.99it/s, loss=0.752]

Epoch   2 | Train F1=0.5878 | Val F1=0.5749

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 70.51it/s, loss=0.791]

Epoch   3 | Train F1=0.6512 | Val F1=0.6424

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 83.47it/s, loss=0.667]

Epoch   4 | Train F1=0.7262 | Val F1=0.7046

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 77.09it/s, loss=0.586]

Epoch   5 | Train F1=0.7862 | Val F1=0.7639

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 84.79it/s, loss=0.403]

Epoch   6 | Train F1=0.8228 | Val F1=0.8047

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 89.71it/s, loss=0.446]

Epoch   7 | Train F1=0.8397 | Val F1=0.8297

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 89.98it/s, loss=0.448]

Epoch   8 | Train F1=0.8546 | Val F1=0.8404

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 91.68it/s, loss=0.252]

Epoch   9 | Train F1=0.8592 | Val F1=0.8446

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 84.68it/s, loss=0.29]

Epoch  10 | Train F1=0.8625 | Val F1=0.8492

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 72.17it/s, loss=0.438]

Epoch  11 | Train F1=0.8819 | Val F1=0.8626

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 76.41it/s, loss=0.262]

Epoch  12 | Train F1=0.8879 | Val F1=0.8712

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 75.10it/s, loss=0.353]

Epoch  13 | Train F1=0.8966 | Val F1=0.8825

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 84.72it/s, loss=0.519]

Epoch  14 | Train F1=0.8972 | Val F1=0.8745

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 89.68it/s, loss=0.448]

Epoch  15 | Train F1=0.9032 | Val F1=0.8867

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 86.79it/s, loss=0.433]

Epoch  16 | Train F1=0.9046 | Val F1=0.8830

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 85.41it/s, loss=0.295]

Epoch  17 | Train F1=0.9108 | Val F1=0.8861

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 93.74it/s, loss=0.458]

Epoch  18 | Train F1=0.9109 | Val F1=0.8916

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 88.63it/s, loss=0.321]

Epoch  19 | Train F1=0.9095 | Val F1=0.8910

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 89.01it/s, loss=0.364]

Epoch  20 | Train F1=0.9140 | Val F1=0.8971

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 84.94it/s, loss=0.342]

Epoch  21 | Train F1=0.9132 | Val F1=0.8894

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 87.49it/s, loss=0.257]

Epoch  22 | Train F1=0.9209 | Val F1=0.8973

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 83.44it/s, loss=0.3]

Epoch  23 | Train F1=0.9230 | Val F1=0.8976

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 81.90it/s, loss=0.255]

Epoch  24 | Train F1=0.9248 | Val F1=0.9000

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 81.21it/s, loss=0.288]

Epoch  25 | Train F1=0.9234 | Val F1=0.8947

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 92.83it/s, loss=0.292]

Epoch  26 | Train F1=0.9184 | Val F1=0.8921

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 78.06it/s, loss=0.514]

Epoch  27 | Train F1=0.9238 | Val F1=0.8955

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 83.68it/s, loss=0.2]

Epoch  28 | Train F1=0.9279 | Val F1=0.8988

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 68.55it/s, loss=0.38]

Epoch  29 | Train F1=0.9251 | Val F1=0.8973

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 87.99it/s, loss=0.212]

Epoch  30 | Train F1=0.9298 | Val F1=0.9005

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 90.70it/s, loss=0.329]

Epoch  31 | Train F1=0.9293 | Val F1=0.9011

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 85.36it/s, loss=0.254]

Epoch  32 | Train F1=0.9333 | Val F1=0.9014

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 82.75it/s, loss=0.305]

Epoch  33 | Train F1=0.9324 | Val F1=0.9054

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 72.67it/s, loss=0.318]

Epoch  34 | Train F1=0.9318 | Val F1=0.9038

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 73.88it/s, loss=0.205]

Epoch  35 | Train F1=0.9292 | Val F1=0.8990

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 73.89it/s, loss=0.287]

Epoch  36 | Train F1=0.9347 | Val F1=0.9013

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 85.75it/s, loss=0.266]

Epoch  37 | Train F1=0.9373 | Val F1=0.9080

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 84.94it/s, loss=0.481]

Epoch  38 | Train F1=0.9357 | Val F1=0.9023

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 89.28it/s, loss=0.302]

Epoch  39 | Train F1=0.9367 | Val F1=0.9058

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 83.54it/s, loss=0.299]

Epoch  40 | Train F1=0.9345 | Val F1=0.9025

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 75.78it/s, loss=0.375]

Epoch  41 | Train F1=0.9381 | Val F1=0.9027

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 66.60it/s, loss=0.177]

Epoch  42 | Train F1=0.9428 | Val F1=0.9060

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 74.99it/s, loss=0.13]

Epoch  43 | Train F1=0.9410 | Val F1=0.9060

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 86.07it/s, loss=0.333]

Epoch  44 | Train F1=0.9388 | Val F1=0.9040

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 83.82it/s, loss=0.345]

Epoch  45 | Train F1=0.9430 | Val F1=0.9026

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 85.66it/s, loss=0.381]

Epoch  46 | Train F1=0.9440 | Val F1=0.9086

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 88.07it/s, loss=0.354]

Epoch  47 | Train F1=0.9460 | Val F1=0.9100

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 79.76it/s, loss=0.292]

Epoch  48 | Train F1=0.9459 | Val F1=0.9082

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 75.85it/s, loss=0.269]

Epoch  49 | Train F1=0.9479 | Val F1=0.9031

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 89.60it/s, loss=0.25]

Epoch  50 | Train F1=0.9477 | Val F1=0.9114

Epoch 51: 100%|██████████| 133/133 [00:01<00:00, 74.39it/s, loss=0.243]

Epoch  51 | Train F1=0.9491 | Val F1=0.9120

Epoch 52: 100%|██████████| 133/133 [00:01<00:00, 87.47it/s, loss=0.12]

Epoch  52 | Train F1=0.9469 | Val F1=0.9064

Epoch 53: 100%|██████████| 133/133 [00:01<00:00, 86.97it/s, loss=0.269]

Epoch  53 | Train F1=0.9489 | Val F1=0.9118

Epoch 54: 100%|██████████| 133/133 [00:01<00:00, 85.37it/s, loss=0.331]

Epoch  54 | Train F1=0.9502 | Val F1=0.9088

Epoch 55: 100%|██████████| 133/133 [00:01<00:00, 92.38it/s, loss=0.347]

Epoch  55 | Train F1=0.9475 | Val F1=0.9066

Epoch 56: 100%|██████████| 133/133 [00:01<00:00, 85.02it/s, loss=0.162]

Epoch  56 | Train F1=0.9503 | Val F1=0.9119

Epoch 57: 100%|██████████| 133/133 [00:01<00:00, 73.26it/s, loss=0.396]

Epoch  57 | Train F1=0.9501 | Val F1=0.9085

Epoch 58: 100%|██████████| 133/133 [00:01<00:00, 95.52it/s, loss=0.239]

Epoch  58 | Train F1=0.9524 | Val F1=0.9115

Epoch 59: 100%|██████████| 133/133 [00:01<00:00, 83.67it/s, loss=0.237]

Epoch  59 | Train F1=0.9501 | Val F1=0.9087

Epoch 60: 100%|██████████| 133/133 [00:01<00:00, 94.53it/s, loss=0.25]

Epoch  60 | Train F1=0.9553 | Val F1=0.9122

Epoch 61: 100%|██████████| 133/133 [00:01<00:00, 94.12it/s, loss=0.286]

Epoch  61 | Train F1=0.9521 | Val F1=0.9120

Epoch 62: 100%|██████████| 133/133 [00:01<00:00, 98.20it/s, loss=0.247]

Epoch  62 | Train F1=0.9472 | Val F1=0.9012

Epoch 63: 100%|██████████| 133/133 [00:01<00:00, 90.41it/s, loss=0.143]

Epoch  63 | Train F1=0.9509 | Val F1=0.9082

Epoch 64: 100%|██████████| 133/133 [00:01<00:00, 72.86it/s, loss=0.0909]

Epoch  64 | Train F1=0.9506 | Val F1=0.9060

Epoch 65: 100%|██████████| 133/133 [00:01<00:00, 88.46it/s, loss=0.37]

Epoch  65 | Train F1=0.9528 | Val F1=0.9083

Epoch 66: 100%|██████████| 133/133 [00:01<00:00, 90.07it/s, loss=0.162]

Epoch  66 | Train F1=0.9566 | Val F1=0.9082

Epoch 67: 100%|██████████| 133/133 [00:01<00:00, 85.02it/s, loss=0.331]

Epoch  67 | Train F1=0.9512 | Val F1=0.9064

Epoch 68: 100%|██████████| 133/133 [00:01<00:00, 89.78it/s, loss=0.143]

Epoch  68 | Train F1=0.9584 | Val F1=0.9139

Epoch 69: 100%|██████████| 133/133 [00:01<00:00, 94.85it/s, loss=0.36]

Epoch  69 | Train F1=0.9573 | Val F1=0.9093

Epoch 70: 100%|██████████| 133/133 [00:01<00:00, 90.40it/s, loss=0.197]

Epoch  70 | Train F1=0.9606 | Val F1=0.9126

Epoch 71: 100%|██████████| 133/133 [00:01<00:00, 82.66it/s, loss=0.18]

Epoch  71 | Train F1=0.9613 | Val F1=0.9129

Epoch 72: 100%|██████████| 133/133 [00:01<00:00, 83.60it/s, loss=0.181]

Epoch  72 | Train F1=0.9602 | Val F1=0.9134

Epoch 73: 100%|██████████| 133/133 [00:01<00:00, 83.01it/s, loss=0.304]

Epoch  73 | Train F1=0.9579 | Val F1=0.9087

Epoch 74: 100%|██████████| 133/133 [00:01<00:00, 86.94it/s, loss=0.106]

Epoch  74 | Train F1=0.9561 | Val F1=0.9092

Epoch 75: 100%|██████████| 133/133 [00:01<00:00, 78.91it/s, loss=0.267]

Epoch  75 | Train F1=0.9618 | Val F1=0.9127

Epoch 76: 100%|██████████| 133/133 [00:01<00:00, 83.27it/s, loss=0.51]

Epoch  76 | Train F1=0.9619 | Val F1=0.9087

Epoch 77: 100%|██████████| 133/133 [00:01<00:00, 94.71it/s, loss=0.157]

Epoch  77 | Train F1=0.9611 | Val F1=0.9124

Epoch 78: 100%|██████████| 133/133 [00:01<00:00, 92.21it/s, loss=0.178]

Epoch  78 | Train F1=0.9630 | Val F1=0.9155

Epoch 79: 100%|██████████| 133/133 [00:01<00:00, 85.23it/s, loss=0.221]

Epoch  79 | Train F1=0.9573 | Val F1=0.9074

Epoch 80: 100%|██████████| 133/133 [00:01<00:00, 81.43it/s, loss=0.182]

Epoch  80 | Train F1=0.9540 | Val F1=0.8992

Epoch 81: 100%|██████████| 133/133 [00:01<00:00, 67.41it/s, loss=0.227]

Epoch  81 | Train F1=0.9507 | Val F1=0.9087

Epoch 82: 100%|██████████| 133/133 [00:01<00:00, 76.08it/s, loss=0.228]

Epoch  82 | Train F1=0.9574 | Val F1=0.9107

Epoch 83: 100%|██████████| 133/133 [00:01<00:00, 77.85it/s, loss=0.141]

Epoch  83 | Train F1=0.9629 | Val F1=0.9109

Epoch 84: 100%|██████████| 133/133 [00:01<00:00, 90.46it/s, loss=0.247]

Epoch  84 | Train F1=0.9624 | Val F1=0.9113

Epoch 85: 100%|██████████| 133/133 [00:01<00:00, 90.24it/s, loss=0.185]

Epoch  85 | Train F1=0.9641 | Val F1=0.9128

Epoch 86: 100%|██████████| 133/133 [00:01<00:00, 92.36it/s, loss=0.36]

Epoch  86 | Train F1=0.9663 | Val F1=0.9134

Epoch 87: 100%|██████████| 133/133 [00:01<00:00, 87.57it/s, loss=0.239]

Epoch  87 | Train F1=0.9640 | Val F1=0.9120

Epoch 88: 100%|██████████| 133/133 [00:01<00:00, 80.72it/s, loss=0.302]

Epoch  88 | Train F1=0.9635 | Val F1=0.9084

Epoch 89: 100%|██████████| 133/133 [00:01<00:00, 83.22it/s, loss=0.189]

Epoch  89 | Train F1=0.9639 | Val F1=0.9118

Epoch 90: 100%|██████████| 133/133 [00:01<00:00, 92.23it/s, loss=0.123]

Epoch  90 | Train F1=0.9649 | Val F1=0.9113

Epoch 91: 100%|██████████| 133/133 [00:01<00:00, 76.85it/s, loss=0.138]

Epoch  91 | Train F1=0.9645 | Val F1=0.9068

Epoch 92: 100%|██████████| 133/133 [00:01<00:00, 91.56it/s, loss=0.322]

Epoch  92 | Train F1=0.9702 | Val F1=0.9128

Epoch 93: 100%|██████████| 133/133 [00:01<00:00, 89.92it/s, loss=0.125]

Epoch  93 | Train F1=0.9683 | Val F1=0.9169

Epoch 94: 100%|██████████| 133/133 [00:01<00:00, 95.00it/s, loss=0.146]

Epoch  94 | Train F1=0.9661 | Val F1=0.9175

Epoch 95: 100%|██████████| 133/133 [00:01<00:00, 94.13it/s, loss=0.25]

Epoch  95 | Train F1=0.9650 | Val F1=0.9139

Epoch 96: 100%|██████████| 133/133 [00:01<00:00, 86.13it/s, loss=0.235]

Epoch  96 | Train F1=0.9656 | Val F1=0.9100

Epoch 97: 100%|██████████| 133/133 [00:01<00:00, 88.71it/s, loss=0.147]

Epoch  97 | Train F1=0.9687 | Val F1=0.9115

Epoch 98: 100%|██████████| 133/133 [00:01<00:00, 84.61it/s, loss=0.158]

Epoch  98 | Train F1=0.9714 | Val F1=0.9161

Epoch 99: 100%|██████████| 133/133 [00:01<00:00, 69.01it/s, loss=0.17]

Epoch  99 | Train F1=0.9661 | Val F1=0.9128

Epoch 100: 100%|██████████| 133/133 [00:01<00:00, 90.15it/s, loss=0.288]

Epoch 100 | Train F1=0.9703 | Val F1=0.9133

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 84.85it/s, loss=1.08]

Epoch   1 | Train F1=0.5757 | Val F1=0.5832

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 94.11it/s, loss=0.778]

Epoch   2 | Train F1=0.7091 | Val F1=0.7134

Epoch 3: 100%|██████████| 132/132 [00:02<00:00, 65.67it/s, loss=0.618]

Epoch   3 | Train F1=0.7142 | Val F1=0.7155

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 77.94it/s, loss=0.613]

Epoch   4 | Train F1=0.7942 | Val F1=0.7940

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 86.98it/s, loss=0.408]

Epoch   5 | Train F1=0.8105 | Val F1=0.8144

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 89.46it/s, loss=0.424]

Epoch   6 | Train F1=0.8407 | Val F1=0.8458

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 89.69it/s, loss=0.417]

Epoch   7 | Train F1=0.8546 | Val F1=0.8612

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 84.56it/s, loss=0.529]

Epoch   8 | Train F1=0.8544 | Val F1=0.8650

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 86.06it/s, loss=0.43]

Epoch   9 | Train F1=0.8740 | Val F1=0.8726

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 91.94it/s, loss=0.38]

Epoch  10 | Train F1=0.8901 | Val F1=0.8912

Epoch 11: 100%|██████████| 132/132 [00:01<00:00, 70.31it/s, loss=0.357]

Epoch  11 | Train F1=0.8884 | Val F1=0.8832

Epoch 12: 100%|██████████| 132/132 [00:02<00:00, 61.14it/s, loss=0.56]

Epoch  12 | Train F1=0.8946 | Val F1=0.8927

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 86.78it/s, loss=0.239]

Epoch  13 | Train F1=0.9045 | Val F1=0.8982

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 85.69it/s, loss=0.321]

Epoch  14 | Train F1=0.9035 | Val F1=0.8977

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 92.60it/s, loss=0.336]

Epoch  15 | Train F1=0.9098 | Val F1=0.9055

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 90.27it/s, loss=0.187]

Epoch  16 | Train F1=0.9131 | Val F1=0.9062

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 86.95it/s, loss=0.316]

Epoch  17 | Train F1=0.9184 | Val F1=0.9081

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 82.99it/s, loss=0.387]

Epoch  18 | Train F1=0.9153 | Val F1=0.9117

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 94.55it/s, loss=0.386]

Epoch  19 | Train F1=0.9245 | Val F1=0.9128

Epoch 20: 100%|██████████| 132/132 [00:01<00:00, 82.07it/s, loss=0.515]

Epoch  20 | Train F1=0.9302 | Val F1=0.9188

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 93.66it/s, loss=0.29]

Epoch  21 | Train F1=0.9301 | Val F1=0.9206

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 94.94it/s, loss=0.369]

Epoch  22 | Train F1=0.9334 | Val F1=0.9219

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 96.03it/s, loss=0.333]

Epoch  23 | Train F1=0.9332 | Val F1=0.9183

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 87.48it/s, loss=0.33]

Epoch  24 | Train F1=0.9356 | Val F1=0.9208

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 82.67it/s, loss=0.202]

Epoch  25 | Train F1=0.9333 | Val F1=0.9214

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 90.85it/s, loss=0.356]

Epoch  26 | Train F1=0.9401 | Val F1=0.9258

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 67.38it/s, loss=0.282]

Epoch  27 | Train F1=0.9428 | Val F1=0.9239

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 87.02it/s, loss=0.303]

Epoch  28 | Train F1=0.9435 | Val F1=0.9311

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 80.41it/s, loss=0.193]

Epoch  29 | Train F1=0.9408 | Val F1=0.9246

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 88.90it/s, loss=0.278]

Epoch  30 | Train F1=0.9413 | Val F1=0.9256

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 86.40it/s, loss=0.246]

Epoch  31 | Train F1=0.9447 | Val F1=0.9260

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 91.73it/s, loss=0.194]

Epoch  32 | Train F1=0.9438 | Val F1=0.9287

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 86.24it/s, loss=0.249]

Epoch  33 | Train F1=0.9407 | Val F1=0.9255

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 90.51it/s, loss=0.317]

Epoch  34 | Train F1=0.9414 | Val F1=0.9238

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 85.30it/s, loss=0.243]

Epoch  35 | Train F1=0.9441 | Val F1=0.9267

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 67.92it/s, loss=0.288]

Epoch  36 | Train F1=0.9444 | Val F1=0.9283

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 92.64it/s, loss=0.247]

Epoch  37 | Train F1=0.9482 | Val F1=0.9301

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 93.36it/s, loss=0.332]

Epoch  38 | Train F1=0.9449 | Val F1=0.9301

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 91.65it/s, loss=0.168]

Epoch  39 | Train F1=0.9465 | Val F1=0.9279

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 85.12it/s, loss=0.239]

Epoch  40 | Train F1=0.9456 | Val F1=0.9271

Epoch 41: 100%|██████████| 132/132 [00:01<00:00, 86.46it/s, loss=0.224]

Epoch  41 | Train F1=0.9487 | Val F1=0.9289

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 76.89it/s, loss=0.207]

Epoch  42 | Train F1=0.9495 | Val F1=0.9272

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 90.37it/s, loss=0.199]

Epoch  43 | Train F1=0.9463 | Val F1=0.9271

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 77.73it/s, loss=0.238]

Epoch  44 | Train F1=0.9456 | Val F1=0.9275

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 91.52it/s, loss=0.0865]

Epoch  45 | Train F1=0.9504 | Val F1=0.9245

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 87.23it/s, loss=0.143]

Epoch  46 | Train F1=0.9465 | Val F1=0.9257

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 91.11it/s, loss=0.319]

Epoch  47 | Train F1=0.9490 | Val F1=0.9257

Epoch 48: 100%|██████████| 132/132 [00:01<00:00, 93.47it/s, loss=0.214]

Epoch  48 | Train F1=0.9527 | Val F1=0.9325

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 80.14it/s, loss=0.256]

Epoch  49 | Train F1=0.9512 | Val F1=0.9265

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 66.06it/s, loss=0.209]

Epoch  50 | Train F1=0.9511 | Val F1=0.9259

Epoch 51: 100%|██████████| 132/132 [00:02<00:00, 64.75it/s, loss=0.14]

Epoch  51 | Train F1=0.9505 | Val F1=0.9304

Epoch 52: 100%|██████████| 132/132 [00:01<00:00, 83.96it/s, loss=0.498]

Epoch  52 | Train F1=0.9537 | Val F1=0.9310

Epoch 53: 100%|██████████| 132/132 [00:01<00:00, 94.48it/s, loss=0.189]

Epoch  53 | Train F1=0.9545 | Val F1=0.9336

Epoch 54: 100%|██████████| 132/132 [00:01<00:00, 82.78it/s, loss=0.22]

Epoch  54 | Train F1=0.9552 | Val F1=0.9331

Epoch 55: 100%|██████████| 132/132 [00:01<00:00, 83.40it/s, loss=0.369]

Epoch  55 | Train F1=0.9515 | Val F1=0.9287

Epoch 56: 100%|██████████| 132/132 [00:01<00:00, 79.44it/s, loss=0.183]

Epoch  56 | Train F1=0.9547 | Val F1=0.9316

Epoch 57: 100%|██████████| 132/132 [00:01<00:00, 84.38it/s, loss=0.101]

Epoch  57 | Train F1=0.9573 | Val F1=0.9326

Epoch 58: 100%|██████████| 132/132 [00:01<00:00, 71.49it/s, loss=0.148]

Epoch  58 | Train F1=0.9558 | Val F1=0.9344

Epoch 59: 100%|██████████| 132/132 [00:01<00:00, 87.30it/s, loss=0.111]

Epoch  59 | Train F1=0.9575 | Val F1=0.9338

Epoch 60: 100%|██████████| 132/132 [00:01<00:00, 81.66it/s, loss=0.338]

Epoch  60 | Train F1=0.9584 | Val F1=0.9329

Epoch 61: 100%|██████████| 132/132 [00:01<00:00, 88.67it/s, loss=0.226]

Epoch  61 | Train F1=0.9589 | Val F1=0.9352

Epoch 62: 100%|██████████| 132/132 [00:01<00:00, 89.36it/s, loss=0.0886]

Epoch  62 | Train F1=0.9586 | Val F1=0.9320

Epoch 63: 100%|██████████| 132/132 [00:01<00:00, 91.15it/s, loss=0.173]

Epoch  63 | Train F1=0.9581 | Val F1=0.9348

Epoch 64: 100%|██████████| 132/132 [00:01<00:00, 79.74it/s, loss=0.298]

Epoch  64 | Train F1=0.9609 | Val F1=0.9348

Epoch 65: 100%|██████████| 132/132 [00:01<00:00, 78.28it/s, loss=0.228]

Epoch  65 | Train F1=0.9614 | Val F1=0.9326

Epoch 66: 100%|██████████| 132/132 [00:02<00:00, 65.77it/s, loss=0.204]

Epoch  66 | Train F1=0.9571 | Val F1=0.9287

Epoch 67: 100%|██████████| 132/132 [00:01<00:00, 79.76it/s, loss=0.236]

Epoch  67 | Train F1=0.9559 | Val F1=0.9319

Epoch 68: 100%|██████████| 132/132 [00:01<00:00, 89.46it/s, loss=0.215]

Epoch  68 | Train F1=0.9570 | Val F1=0.9318

Epoch 69: 100%|██████████| 132/132 [00:01<00:00, 94.51it/s, loss=0.224]

Epoch  69 | Train F1=0.9581 | Val F1=0.9324

Epoch 70: 100%|██████████| 132/132 [00:01<00:00, 88.35it/s, loss=0.268]

Epoch  70 | Train F1=0.9594 | Val F1=0.9312

Epoch 71: 100%|██████████| 132/132 [00:01<00:00, 83.12it/s, loss=0.119]

Epoch  71 | Train F1=0.9573 | Val F1=0.9281

Epoch 72: 100%|██████████| 132/132 [00:01<00:00, 84.05it/s, loss=0.183]

Epoch  72 | Train F1=0.9616 | Val F1=0.9336

Epoch 73: 100%|██████████| 132/132 [00:01<00:00, 83.01it/s, loss=0.149]

Epoch  73 | Train F1=0.9505 | Val F1=0.9209

Epoch 74: 100%|██████████| 132/132 [00:01<00:00, 83.75it/s, loss=0.089]

Epoch  74 | Train F1=0.9573 | Val F1=0.9308

Epoch 75: 100%|██████████| 132/132 [00:01<00:00, 83.33it/s, loss=0.255]

Epoch  75 | Train F1=0.9599 | Val F1=0.9343

Epoch 76: 100%|██████████| 132/132 [00:01<00:00, 90.83it/s, loss=0.0994]

Epoch  76 | Train F1=0.9631 | Val F1=0.9320

Epoch 77: 100%|██████████| 132/132 [00:01<00:00, 90.51it/s, loss=0.204]

Epoch  77 | Train F1=0.9626 | Val F1=0.9328

Epoch 78: 100%|██████████| 132/132 [00:01<00:00, 92.84it/s, loss=0.228]

Epoch  78 | Train F1=0.9609 | Val F1=0.9358

Epoch 79: 100%|██████████| 132/132 [00:01<00:00, 87.21it/s, loss=0.17]

Epoch  79 | Train F1=0.9652 | Val F1=0.9371

Epoch 80: 100%|██████████| 132/132 [00:01<00:00, 86.82it/s, loss=0.249]

Epoch  80 | Train F1=0.9628 | Val F1=0.9341

Epoch 81: 100%|██████████| 132/132 [00:01<00:00, 87.94it/s, loss=0.281]

Epoch  81 | Train F1=0.9644 | Val F1=0.9353

Epoch 82: 100%|██████████| 132/132 [00:02<00:00, 60.41it/s, loss=0.147]

Epoch  82 | Train F1=0.9674 | Val F1=0.9343

Epoch 83: 100%|██████████| 132/132 [00:02<00:00, 65.25it/s, loss=0.264]

Epoch  83 | Train F1=0.9612 | Val F1=0.9309

Epoch 84: 100%|██████████| 132/132 [00:01<00:00, 89.40it/s, loss=0.218]

Epoch  84 | Train F1=0.9638 | Val F1=0.9347

Epoch 85: 100%|██████████| 132/132 [00:01<00:00, 86.78it/s, loss=0.092]

Epoch  85 | Train F1=0.9623 | Val F1=0.9337

Epoch 86: 100%|██████████| 132/132 [00:01<00:00, 82.33it/s, loss=0.0969]

Epoch  86 | Train F1=0.9673 | Val F1=0.9358

Epoch 87: 100%|██████████| 132/132 [00:01<00:00, 90.31it/s, loss=0.156]

Epoch  87 | Train F1=0.9633 | Val F1=0.9349

Epoch 88: 100%|██████████| 132/132 [00:01<00:00, 80.11it/s, loss=0.136]

Epoch  88 | Train F1=0.9691 | Val F1=0.9387

Epoch 89: 100%|██████████| 132/132 [00:01<00:00, 78.27it/s, loss=0.226]

Epoch  89 | Train F1=0.9701 | Val F1=0.9373

Epoch 90: 100%|██████████| 132/132 [00:02<00:00, 58.99it/s, loss=0.226]

Epoch  90 | Train F1=0.9584 | Val F1=0.9307

Epoch 91: 100%|██████████| 132/132 [00:01<00:00, 89.92it/s, loss=0.245]

Epoch  91 | Train F1=0.9665 | Val F1=0.9322

Epoch 92: 100%|██████████| 132/132 [00:01<00:00, 91.12it/s, loss=0.256]

Epoch  92 | Train F1=0.9613 | Val F1=0.9325

Epoch 93: 100%|██████████| 132/132 [00:01<00:00, 86.88it/s, loss=0.176]

Epoch  93 | Train F1=0.9636 | Val F1=0.9310

Epoch 94: 100%|██████████| 132/132 [00:01<00:00, 89.19it/s, loss=0.373]

Epoch  94 | Train F1=0.9679 | Val F1=0.9369

Epoch 95: 100%|██████████| 132/132 [00:01<00:00, 81.54it/s, loss=0.23]

Epoch  95 | Train F1=0.9682 | Val F1=0.9347

Epoch 96: 100%|██████████| 132/132 [00:01<00:00, 67.62it/s, loss=0.233]

Epoch  96 | Train F1=0.9623 | Val F1=0.9326

Epoch 97: 100%|██████████| 132/132 [00:01<00:00, 89.19it/s, loss=0.102]

Epoch  97 | Train F1=0.9709 | Val F1=0.9379

Epoch 98: 100%|██████████| 132/132 [00:01<00:00, 78.74it/s, loss=0.222]

Epoch  98 | Train F1=0.9714 | Val F1=0.9350

Epoch 99: 100%|██████████| 132/132 [00:01<00:00, 89.23it/s, loss=0.112]

Epoch  99 | Train F1=0.9651 | Val F1=0.9292

Epoch 100: 100%|██████████| 132/132 [00:01<00:00, 93.97it/s, loss=0.133]

Epoch 100 | Train F1=0.9673 | Val F1=0.9343

In [14]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
for i in range(7):
    df.iloc[i,i+1] = '-'
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'

          Treino head chest upperarm forearm waist thigh shin
head          85    -    52       47      32    39    45   27
chest         93   40     -       40      36    42    48   29
upperarm      91   49    64        -      26    16    62   52
forearm       88   33    35       43       -    33    38   38
waist         93   44    31       19      25     -    29   13
thigh         93   42    42       46      40    35     -   51
shin          93   14    36       39      28    12    37    -

In [ ]:
data = {
    'Treino': [84, 90, 88, 84, 91, 90, 91],
    'head': ['-', 46, 46, 30, 38, 41, 18],
    'chest': [52, '-', 64, 32, 29, 34, 34],
    'upperarm': [51, 43, '-', 39, 20, 39, 39],
    'forearm': [25, 38, 29, '-', 27, 33, 28],
    'waist': [29, 37, 18, 24, '-', 39, 21],
    'thigh': [44, 46, 62, 35, 28, '-', 38],
    'shin': [22, 35, 46, 28, 17, 51, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          84    -    52       51      25    29    44   22
chest         90   46     -       43      38    37    46   35
upperarm      88   46    64        -      29    18    62   46
forearm       84   30    32       39       -    24    35   28
waist         91   38    29       20      27     -    28   17
thigh         90   41    34       39      33    39     -   51
shin          91   18    34       39      28    21    38    -

## Baseline 1: filtro passa-altas

In [ ]:
sos = butter(N=6, Wn=0.3, btype='hp', fs=50, output='sos')
Xf = np.swapaxes(sosfiltfilt(sos, np.swapaxes(Xcort, 1, 2)), 1, 2)

In [ ]:
pasta = '/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/modelos/'
baselinef1 = np.zeros((7,7))
for i, pos in enumerate(posis):
    inds = ycort[:,0]==i
    X = Xf[inds]
    y = ycort[inds][:,1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
    X_train = torch.tensor(X_train, dtype=torch.float32)
    X_test  = torch.tensor(X_test, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.long)
    y_test  = torch.tensor(y_test, dtype=torch.long)
    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
    test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
    enc, cla, history = train_model(train_loader, test_loader, device, n_epochs=100)
    nome = 'baseline_hp_encoder_'+pos+'.pth'
    torch.save(enc.state_dict(), pasta+nome)
    nome = 'baseline_hp_classifier_'+pos+'.pth'
    torch.save(cla.state_dict(), pasta+nome)
    for j in range(7):
        inds = ycort[:,0]==j
        X = Xf[inds]
        y = ycort[inds][:,1]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
        X_test  = torch.tensor(X_test, dtype=torch.float32)
        y_test  = torch.tensor(y_test, dtype=torch.long)
        test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        baselinef1[i,j] = test_f1

In [ ]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
for i in range(7):
    df.iloc[i,i+1] = '-'
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])

In [ ]:
data = {
    'Treino': [84, 90, 88, 84, 91, 90, 91],
    'head': ['-', 46, 46, 30, 38, 41, 18],
    'chest': [52, '-', 64, 32, 29, 34, 34],
    'upperarm': [51, 43, '-', 39, 20, 39, 39],
    'forearm': [25, 38, 29, '-', 27, 33, 28],
    'waist': [29, 37, 18, 24, '-', 39, 21],
    'thigh': [44, 46, 62, 35, 28, '-', 38],
    'shin': [22, 35, 46, 28, 17, 51, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df0 = pd.DataFrame(data, index=index_labels)

print(df)
print(df0)

          Treino head chest upperarm forearm waist thigh shin
head          82    -    44       46      32    34    38   20
chest         84   51     -       52      39    32    48   37
upperarm      85   46    61        -      32    17    56   43
forearm       81   41    43       46       -    31    37   39
waist         86   43    28       21      25     -    27   18
thigh         84   43    37       43      36    35     -   49
shin          87   22    26       38      28    15    29    -
          Treino head chest upperarm forearm waist thigh shin
head          84    -    52       51      25    29    44   22
chest         90   46     -       43      38    37    46   35
upperarm      88   46    64        -      29    18    62   46
forearm       84   30    32       39       -    24    35   28
waist         91   38    29       20      27     -    28   17
thigh         90   41    34       39      33    39     -   51
shin          91   18    34       39      28    21    38    -

## Baseline 2: filtro passa-baixas 10 Hz

In [16]:
sos = butter(N=6, Wn=10, btype='lp', fs=50, output='sos')
Xf = np.swapaxes(sosfiltfilt(sos, np.swapaxes(Xcort, 1, 2)), 1, 2)

In [17]:
pasta = '/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/modelos/'
baselinef1 = np.zeros((7,7))
for i, pos in enumerate(posis):
    inds = ycort[:,0]==i
    X = Xf[inds]
    y = ycort[inds][:,1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
    X_train = torch.tensor(X_train, dtype=torch.float32)
    X_test  = torch.tensor(X_test, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.long)
    y_test  = torch.tensor(y_test, dtype=torch.long)
    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
    test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
    enc, cla, history = train_model(train_loader, test_loader, device, n_epochs=50)
    nome = 'baseline_lp_encoder_'+pos+'.pth'
    torch.save(enc.state_dict(), pasta+nome)
    nome = 'baseline_lp_classifier_'+pos+'.pth'
    torch.save(cla.state_dict(), pasta+nome)
    for j in range(7):
        inds = ycort[:,0]==j
        X = Xf[inds]
        y = ycort[inds][:,1]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
        X_test  = torch.tensor(X_test, dtype=torch.float32)
        y_test  = torch.tensor(y_test, dtype=torch.long)
        test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        baselinef1[i,j] = test_f1

Epoch 1: 100%|██████████| 133/133 [00:02<00:00, 53.91it/s, loss=1.16]

Epoch   1 | Train F1=0.5173 | Val F1=0.5113

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 69.45it/s, loss=0.654]

Epoch   2 | Train F1=0.6239 | Val F1=0.6255

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 110.63it/s, loss=0.73]

Epoch   3 | Train F1=0.7145 | Val F1=0.6908

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 111.27it/s, loss=0.559]

Epoch   4 | Train F1=0.7302 | Val F1=0.7077

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 89.62it/s, loss=0.664]

Epoch   5 | Train F1=0.7579 | Val F1=0.7361

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 92.55it/s, loss=0.556]

Epoch   6 | Train F1=0.7774 | Val F1=0.7620

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 114.13it/s, loss=0.457]

Epoch   7 | Train F1=0.7822 | Val F1=0.7636

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 109.57it/s, loss=0.449]

Epoch   8 | Train F1=0.8187 | Val F1=0.8088

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 110.13it/s, loss=0.45]

Epoch   9 | Train F1=0.8599 | Val F1=0.8479

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 112.93it/s, loss=0.476]

Epoch  10 | Train F1=0.8413 | Val F1=0.8218

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 112.67it/s, loss=0.535]

Epoch  11 | Train F1=0.8730 | Val F1=0.8573

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 111.63it/s, loss=0.616]

Epoch  12 | Train F1=0.8952 | Val F1=0.8779

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 85.80it/s, loss=0.405]

Epoch  13 | Train F1=0.8822 | Val F1=0.8631

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 93.63it/s, loss=0.255]

Epoch  14 | Train F1=0.8966 | Val F1=0.8856

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 101.99it/s, loss=0.388]

Epoch  15 | Train F1=0.9065 | Val F1=0.8896

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 109.68it/s, loss=0.422]

Epoch  16 | Train F1=0.9085 | Val F1=0.8848

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 110.44it/s, loss=0.29]

Epoch  17 | Train F1=0.9081 | Val F1=0.8915

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 111.44it/s, loss=0.495]

Epoch  18 | Train F1=0.9072 | Val F1=0.8874

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 110.62it/s, loss=0.468]

Epoch  19 | Train F1=0.9180 | Val F1=0.8943

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 111.37it/s, loss=0.252]

Epoch  20 | Train F1=0.9165 | Val F1=0.8926

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 88.40it/s, loss=0.358]

Epoch  21 | Train F1=0.9238 | Val F1=0.9027

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 90.05it/s, loss=0.323]

Epoch  22 | Train F1=0.9144 | Val F1=0.8928

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 107.43it/s, loss=0.389]

Epoch  23 | Train F1=0.9138 | Val F1=0.8901

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 111.28it/s, loss=0.3]

Epoch  24 | Train F1=0.9186 | Val F1=0.8935

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 109.11it/s, loss=0.354]

Epoch  25 | Train F1=0.9205 | Val F1=0.8904

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 108.78it/s, loss=0.46]

Epoch  26 | Train F1=0.9260 | Val F1=0.9005

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 109.11it/s, loss=0.203]

Epoch  27 | Train F1=0.9285 | Val F1=0.9032

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 108.01it/s, loss=0.12]

Epoch  28 | Train F1=0.9317 | Val F1=0.9048

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 85.99it/s, loss=0.476]

Epoch  29 | Train F1=0.9291 | Val F1=0.9031

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 88.25it/s, loss=0.66]

Epoch  30 | Train F1=0.9311 | Val F1=0.9064

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 106.92it/s, loss=0.389]

Epoch  31 | Train F1=0.9322 | Val F1=0.9019

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 107.09it/s, loss=0.245]

Epoch  32 | Train F1=0.9407 | Val F1=0.9087

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 79.26it/s, loss=0.466]

Epoch  33 | Train F1=0.9333 | Val F1=0.9103

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 108.14it/s, loss=0.42]

Epoch  34 | Train F1=0.9362 | Val F1=0.9098

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 105.81it/s, loss=0.407]

Epoch  35 | Train F1=0.9332 | Val F1=0.9061

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 96.23it/s, loss=0.182]

Epoch  36 | Train F1=0.9414 | Val F1=0.9118

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 91.32it/s, loss=0.279]

Epoch  37 | Train F1=0.9394 | Val F1=0.9076

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 88.85it/s, loss=0.223]

Epoch  38 | Train F1=0.9296 | Val F1=0.9034

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 108.34it/s, loss=0.198]

Epoch  39 | Train F1=0.9432 | Val F1=0.9117

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 108.55it/s, loss=0.192]

Epoch  40 | Train F1=0.9421 | Val F1=0.9117

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 108.40it/s, loss=0.632]

Epoch  41 | Train F1=0.9415 | Val F1=0.9163

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 109.09it/s, loss=0.232]

Epoch  42 | Train F1=0.9416 | Val F1=0.9135

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 106.22it/s, loss=0.278]

Epoch  43 | Train F1=0.9404 | Val F1=0.9119

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 93.63it/s, loss=0.145]

Epoch  44 | Train F1=0.9466 | Val F1=0.9161

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 87.68it/s, loss=0.232]

Epoch  45 | Train F1=0.9465 | Val F1=0.9196

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 85.50it/s, loss=0.346]

Epoch  46 | Train F1=0.9498 | Val F1=0.9201

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 99.49it/s, loss=0.286]

Epoch  47 | Train F1=0.9495 | Val F1=0.9189

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 101.59it/s, loss=0.222]

Epoch  48 | Train F1=0.9518 | Val F1=0.9241

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 100.23it/s, loss=0.215]

Epoch  49 | Train F1=0.9399 | Val F1=0.9138

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 109.55it/s, loss=0.259]

Epoch  50 | Train F1=0.9484 | Val F1=0.9197

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 88.53it/s, loss=1.28]

Epoch   1 | Train F1=0.4008 | Val F1=0.3909

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 81.69it/s, loss=0.976]

Epoch   2 | Train F1=0.5555 | Val F1=0.5437

Epoch 3: 100%|██████████| 132/132 [00:01<00:00, 103.43it/s, loss=0.867]

Epoch   3 | Train F1=0.6697 | Val F1=0.6452

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 105.81it/s, loss=0.698]

Epoch   4 | Train F1=0.7335 | Val F1=0.7265

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 107.89it/s, loss=0.608]

Epoch   5 | Train F1=0.7857 | Val F1=0.7733

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 105.49it/s, loss=0.703]

Epoch   6 | Train F1=0.7924 | Val F1=0.7733

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 104.97it/s, loss=0.762]

Epoch   7 | Train F1=0.8220 | Val F1=0.8031

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 92.83it/s, loss=0.607]

Epoch   8 | Train F1=0.8311 | Val F1=0.8093

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 86.40it/s, loss=0.552]

Epoch   9 | Train F1=0.8378 | Val F1=0.8156

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 86.05it/s, loss=0.406]

Epoch  10 | Train F1=0.8507 | Val F1=0.8314

Epoch 11: 100%|██████████| 132/132 [00:01<00:00, 104.08it/s, loss=0.41]

Epoch  11 | Train F1=0.8543 | Val F1=0.8303

Epoch 12: 100%|██████████| 132/132 [00:01<00:00, 100.86it/s, loss=0.552]

Epoch  12 | Train F1=0.8538 | Val F1=0.8394

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 99.72it/s, loss=0.415]

Epoch  13 | Train F1=0.8724 | Val F1=0.8500

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 100.17it/s, loss=0.481]

Epoch  14 | Train F1=0.8742 | Val F1=0.8510

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 104.84it/s, loss=0.476]

Epoch  15 | Train F1=0.8758 | Val F1=0.8521

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 89.14it/s, loss=0.451]

Epoch  16 | Train F1=0.8768 | Val F1=0.8467

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 80.86it/s, loss=0.418]

Epoch  17 | Train F1=0.8848 | Val F1=0.8591

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 85.20it/s, loss=0.474]

Epoch  18 | Train F1=0.8892 | Val F1=0.8593

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 100.99it/s, loss=0.35]

Epoch  19 | Train F1=0.8872 | Val F1=0.8564

Epoch 20: 100%|██████████| 132/132 [00:01<00:00, 77.60it/s, loss=0.384]

Epoch  20 | Train F1=0.8918 | Val F1=0.8640

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 76.14it/s, loss=0.447]

Epoch  21 | Train F1=0.8970 | Val F1=0.8686

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 102.39it/s, loss=0.498]

Epoch  22 | Train F1=0.8937 | Val F1=0.8681

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 96.37it/s, loss=0.393]

Epoch  23 | Train F1=0.8978 | Val F1=0.8625

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 83.40it/s, loss=0.462]

Epoch  24 | Train F1=0.8971 | Val F1=0.8647

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 84.53it/s, loss=0.37]

Epoch  25 | Train F1=0.8988 | Val F1=0.8672

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 100.99it/s, loss=0.32]

Epoch  26 | Train F1=0.9002 | Val F1=0.8634

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 99.86it/s, loss=0.462]

Epoch  27 | Train F1=0.9046 | Val F1=0.8691

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 92.44it/s, loss=0.441]

Epoch  28 | Train F1=0.9033 | Val F1=0.8649

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 102.39it/s, loss=0.492]

Epoch  29 | Train F1=0.9074 | Val F1=0.8687

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 98.01it/s, loss=0.534]

Epoch  30 | Train F1=0.9093 | Val F1=0.8729

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 93.36it/s, loss=0.403]

Epoch  31 | Train F1=0.9049 | Val F1=0.8658

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 85.31it/s, loss=0.416]

Epoch  32 | Train F1=0.9094 | Val F1=0.8694

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 80.67it/s, loss=0.477]

Epoch  33 | Train F1=0.9113 | Val F1=0.8711

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 101.87it/s, loss=0.32]

Epoch  34 | Train F1=0.9161 | Val F1=0.8755

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 99.58it/s, loss=0.449]

Epoch  35 | Train F1=0.9158 | Val F1=0.8785

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 100.34it/s, loss=0.506]

Epoch  36 | Train F1=0.9194 | Val F1=0.8769

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 100.28it/s, loss=0.378]

Epoch  37 | Train F1=0.9186 | Val F1=0.8740

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 102.36it/s, loss=0.377]

Epoch  38 | Train F1=0.9204 | Val F1=0.8751

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 88.47it/s, loss=0.293]

Epoch  39 | Train F1=0.9146 | Val F1=0.8703

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 83.64it/s, loss=0.351]

Epoch  40 | Train F1=0.9204 | Val F1=0.8722

Epoch 41: 100%|██████████| 132/132 [00:01<00:00, 77.42it/s, loss=0.39]

Epoch  41 | Train F1=0.9211 | Val F1=0.8717

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 99.76it/s, loss=0.485]

Epoch  42 | Train F1=0.9211 | Val F1=0.8761

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 103.04it/s, loss=0.254]

Epoch  43 | Train F1=0.9243 | Val F1=0.8732

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 100.18it/s, loss=0.352]

Epoch  44 | Train F1=0.9261 | Val F1=0.8764

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 99.08it/s, loss=0.293]

Epoch  45 | Train F1=0.9221 | Val F1=0.8791

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 100.15it/s, loss=0.373]

Epoch  46 | Train F1=0.9255 | Val F1=0.8792

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 84.75it/s, loss=0.367]

Epoch  47 | Train F1=0.9208 | Val F1=0.8759

Epoch 48: 100%|██████████| 132/132 [00:01<00:00, 79.45it/s, loss=0.299]

Epoch  48 | Train F1=0.9263 | Val F1=0.8748

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 80.26it/s, loss=0.381]

Epoch  49 | Train F1=0.9307 | Val F1=0.8802

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 96.68it/s, loss=0.199]

Epoch  50 | Train F1=0.9288 | Val F1=0.8821

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 98.23it/s, loss=1.12]

Epoch   1 | Train F1=0.4667 | Val F1=0.4694

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 74.12it/s, loss=1.02]

Epoch   2 | Train F1=0.5454 | Val F1=0.5446

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 87.62it/s, loss=0.692]

Epoch   3 | Train F1=0.6388 | Val F1=0.6263

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 80.16it/s, loss=0.643]

Epoch   4 | Train F1=0.6914 | Val F1=0.6856

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 81.30it/s, loss=0.663]

Epoch   5 | Train F1=0.7288 | Val F1=0.7199

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 93.45it/s, loss=0.593]

Epoch   6 | Train F1=0.7467 | Val F1=0.7230

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 97.46it/s, loss=0.681]

Epoch   7 | Train F1=0.7551 | Val F1=0.7360

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 97.91it/s, loss=0.625]

Epoch   8 | Train F1=0.7548 | Val F1=0.7395

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 98.71it/s, loss=0.664]

Epoch   9 | Train F1=0.7862 | Val F1=0.7691

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 97.10it/s, loss=0.607]

Epoch  10 | Train F1=0.8017 | Val F1=0.7822

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 78.83it/s, loss=0.619]

Epoch  11 | Train F1=0.8004 | Val F1=0.7772

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 84.36it/s, loss=0.443]

Epoch  12 | Train F1=0.8016 | Val F1=0.7752

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 76.00it/s, loss=0.52]

Epoch  13 | Train F1=0.8078 | Val F1=0.7852

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 100.48it/s, loss=0.462]

Epoch  14 | Train F1=0.8085 | Val F1=0.7789

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 95.30it/s, loss=0.646]

Epoch  15 | Train F1=0.8063 | Val F1=0.7838

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 98.02it/s, loss=0.447]

Epoch  16 | Train F1=0.8337 | Val F1=0.8045

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 98.18it/s, loss=0.58]

Epoch  17 | Train F1=0.8235 | Val F1=0.7944

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 95.08it/s, loss=0.487]

Epoch  18 | Train F1=0.8279 | Val F1=0.8066

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 76.96it/s, loss=0.733]

Epoch  19 | Train F1=0.8397 | Val F1=0.8104

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 86.86it/s, loss=0.498]

Epoch  20 | Train F1=0.8418 | Val F1=0.8193

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 84.13it/s, loss=0.437]

Epoch  21 | Train F1=0.8339 | Val F1=0.8027

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 94.83it/s, loss=0.374]

Epoch  22 | Train F1=0.8444 | Val F1=0.8120

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 94.05it/s, loss=0.42]

Epoch  23 | Train F1=0.8408 | Val F1=0.8099

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 93.74it/s, loss=0.453]

Epoch  24 | Train F1=0.8390 | Val F1=0.8167

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 92.54it/s, loss=0.557]

Epoch  25 | Train F1=0.8558 | Val F1=0.8234

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 90.91it/s, loss=0.225]

Epoch  26 | Train F1=0.8496 | Val F1=0.8204

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 82.48it/s, loss=0.368]

Epoch  27 | Train F1=0.8314 | Val F1=0.8018

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 83.80it/s, loss=0.316]

Epoch  28 | Train F1=0.8545 | Val F1=0.8207

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 92.73it/s, loss=0.52]

Epoch  29 | Train F1=0.8547 | Val F1=0.8229

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 99.39it/s, loss=0.36]

Epoch  30 | Train F1=0.8635 | Val F1=0.8360

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 98.07it/s, loss=0.252]

Epoch  31 | Train F1=0.8671 | Val F1=0.8303

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 95.39it/s, loss=0.375]

Epoch  32 | Train F1=0.8568 | Val F1=0.8233

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 93.80it/s, loss=0.335]

Epoch  33 | Train F1=0.8729 | Val F1=0.8334

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 83.35it/s, loss=0.52]

Epoch  34 | Train F1=0.8602 | Val F1=0.8191

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 78.07it/s, loss=0.402]

Epoch  35 | Train F1=0.8675 | Val F1=0.8322

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 75.55it/s, loss=0.351]

Epoch  36 | Train F1=0.8610 | Val F1=0.8248

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 95.32it/s, loss=0.526]

Epoch  37 | Train F1=0.8721 | Val F1=0.8377

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 96.60it/s, loss=0.297]

Epoch  38 | Train F1=0.8679 | Val F1=0.8286

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 96.61it/s, loss=0.449]

Epoch  39 | Train F1=0.8681 | Val F1=0.8274

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 95.90it/s, loss=0.371]

Epoch  40 | Train F1=0.8705 | Val F1=0.8330

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 91.66it/s, loss=0.457]

Epoch  41 | Train F1=0.8724 | Val F1=0.8330

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 75.68it/s, loss=0.318]

Epoch  42 | Train F1=0.8664 | Val F1=0.8368

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 82.09it/s, loss=0.404]

Epoch  43 | Train F1=0.8744 | Val F1=0.8346

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 77.80it/s, loss=0.52]

Epoch  44 | Train F1=0.8825 | Val F1=0.8407

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 95.01it/s, loss=0.334]

Epoch  45 | Train F1=0.8723 | Val F1=0.8266

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 91.42it/s, loss=0.412]

Epoch  46 | Train F1=0.8920 | Val F1=0.8497

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 91.68it/s, loss=0.358]

Epoch  47 | Train F1=0.8824 | Val F1=0.8456

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 89.90it/s, loss=0.325]

Epoch  48 | Train F1=0.8692 | Val F1=0.8336

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 85.80it/s, loss=0.317]

Epoch  49 | Train F1=0.8854 | Val F1=0.8423

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 81.01it/s, loss=0.27]

Epoch  50 | Train F1=0.8881 | Val F1=0.8395

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 85.29it/s, loss=1.11]

Epoch   1 | Train F1=0.5062 | Val F1=0.5118

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 93.53it/s, loss=0.595]

Epoch   2 | Train F1=0.7165 | Val F1=0.7175

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 91.69it/s, loss=0.498]

Epoch   3 | Train F1=0.8434 | Val F1=0.8307

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 88.08it/s, loss=0.595]

Epoch   4 | Train F1=0.8852 | Val F1=0.8746

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 83.69it/s, loss=0.604]

Epoch   5 | Train F1=0.8968 | Val F1=0.8874

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 83.66it/s, loss=0.34]

Epoch   6 | Train F1=0.8981 | Val F1=0.8897

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 84.03it/s, loss=0.395]

Epoch   7 | Train F1=0.9092 | Val F1=0.8974

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 85.98it/s, loss=0.241]

Epoch   8 | Train F1=0.9159 | Val F1=0.9026

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 89.25it/s, loss=0.444]

Epoch   9 | Train F1=0.9216 | Val F1=0.9064

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 90.49it/s, loss=0.321]

Epoch  10 | Train F1=0.9279 | Val F1=0.9090

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 91.73it/s, loss=0.265]

Epoch  11 | Train F1=0.9249 | Val F1=0.9088

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 87.43it/s, loss=0.294]

Epoch  12 | Train F1=0.9305 | Val F1=0.9156

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 82.72it/s, loss=0.403]

Epoch  13 | Train F1=0.9258 | Val F1=0.9058

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 81.43it/s, loss=0.234]

Epoch  14 | Train F1=0.9289 | Val F1=0.9094

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 78.91it/s, loss=0.232]

Epoch  15 | Train F1=0.9367 | Val F1=0.9155

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 90.55it/s, loss=0.334]

Epoch  16 | Train F1=0.9364 | Val F1=0.9126

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 90.06it/s, loss=0.21]

Epoch  17 | Train F1=0.9416 | Val F1=0.9187

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 91.60it/s, loss=0.232]

Epoch  18 | Train F1=0.9442 | Val F1=0.9185

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 87.34it/s, loss=0.246]

Epoch  19 | Train F1=0.9395 | Val F1=0.9143

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 93.06it/s, loss=0.313]

Epoch  20 | Train F1=0.9389 | Val F1=0.9162

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 78.76it/s, loss=0.194]

Epoch  21 | Train F1=0.9428 | Val F1=0.9186

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 77.23it/s, loss=0.269]

Epoch  22 | Train F1=0.9465 | Val F1=0.9218

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 78.54it/s, loss=0.3]

Epoch  23 | Train F1=0.9434 | Val F1=0.9219

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 90.43it/s, loss=0.323]

Epoch  24 | Train F1=0.9485 | Val F1=0.9218

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 92.18it/s, loss=0.249]

Epoch  25 | Train F1=0.9492 | Val F1=0.9212

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 88.90it/s, loss=0.221]

Epoch  26 | Train F1=0.9501 | Val F1=0.9261

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 91.78it/s, loss=0.258]

Epoch  27 | Train F1=0.9524 | Val F1=0.9231

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 93.21it/s, loss=0.337]

Epoch  28 | Train F1=0.9542 | Val F1=0.9237

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 91.45it/s, loss=0.225]

Epoch  29 | Train F1=0.9486 | Val F1=0.9226

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 83.70it/s, loss=0.113]

Epoch  30 | Train F1=0.9468 | Val F1=0.9201

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 71.88it/s, loss=0.275]

Epoch  31 | Train F1=0.9526 | Val F1=0.9244

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 95.53it/s, loss=0.213]

Epoch  32 | Train F1=0.9550 | Val F1=0.9256

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 88.40it/s, loss=0.0589]

Epoch  33 | Train F1=0.9570 | Val F1=0.9279

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 89.71it/s, loss=0.318]

Epoch  34 | Train F1=0.9568 | Val F1=0.9287

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 88.08it/s, loss=0.175]

Epoch  35 | Train F1=0.9532 | Val F1=0.9264

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 92.09it/s, loss=0.323]

Epoch  36 | Train F1=0.9556 | Val F1=0.9251

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 86.68it/s, loss=0.165]

Epoch  37 | Train F1=0.9539 | Val F1=0.9240

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 73.62it/s, loss=0.197]

Epoch  38 | Train F1=0.9565 | Val F1=0.9289

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 80.54it/s, loss=0.21]

Epoch  39 | Train F1=0.9589 | Val F1=0.9307

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 91.06it/s, loss=0.233]

Epoch  40 | Train F1=0.9573 | Val F1=0.9301

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 91.85it/s, loss=0.206]

Epoch  41 | Train F1=0.9606 | Val F1=0.9291

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 90.67it/s, loss=0.123]

Epoch  42 | Train F1=0.9589 | Val F1=0.9308

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 92.21it/s, loss=0.319]

Epoch  43 | Train F1=0.9579 | Val F1=0.9261

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 82.34it/s, loss=0.139]

Epoch  44 | Train F1=0.9623 | Val F1=0.9311

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 78.47it/s, loss=0.11]

Epoch  45 | Train F1=0.9622 | Val F1=0.9303

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 81.22it/s, loss=0.216]

Epoch  46 | Train F1=0.9632 | Val F1=0.9318

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 88.52it/s, loss=0.126]

Epoch  47 | Train F1=0.9625 | Val F1=0.9286

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 89.73it/s, loss=0.289]

Epoch  48 | Train F1=0.9621 | Val F1=0.9298

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 89.04it/s, loss=0.158]

Epoch  49 | Train F1=0.9590 | Val F1=0.9299

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 89.80it/s, loss=0.244]

Epoch  50 | Train F1=0.9589 | Val F1=0.9238

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 85.44it/s, loss=1.03]

Epoch   1 | Train F1=0.4923 | Val F1=0.4900

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 84.85it/s, loss=0.635]

Epoch   2 | Train F1=0.6668 | Val F1=0.6538

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 77.07it/s, loss=0.425]

Epoch   3 | Train F1=0.7507 | Val F1=0.7380

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 79.83it/s, loss=0.573]

Epoch   4 | Train F1=0.7838 | Val F1=0.7644

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 88.26it/s, loss=0.39]

Epoch   5 | Train F1=0.8226 | Val F1=0.8062

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 87.61it/s, loss=0.511]

Epoch   6 | Train F1=0.8234 | Val F1=0.8053

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 89.18it/s, loss=0.491]

Epoch   7 | Train F1=0.8363 | Val F1=0.8233

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 87.84it/s, loss=0.361]

Epoch   8 | Train F1=0.8450 | Val F1=0.8309

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 85.51it/s, loss=0.419]

Epoch   9 | Train F1=0.8510 | Val F1=0.8343

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 77.26it/s, loss=0.401]

Epoch  10 | Train F1=0.8610 | Val F1=0.8386

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 89.27it/s, loss=0.496]

Epoch  11 | Train F1=0.8733 | Val F1=0.8542

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 76.75it/s, loss=0.543]

Epoch  12 | Train F1=0.8867 | Val F1=0.8660

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 89.13it/s, loss=0.389]

Epoch  13 | Train F1=0.8936 | Val F1=0.8787

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 90.80it/s, loss=0.232]

Epoch  14 | Train F1=0.8962 | Val F1=0.8797

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 89.38it/s, loss=0.369]

Epoch  15 | Train F1=0.9030 | Val F1=0.8854

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 93.11it/s, loss=0.452]

Epoch  16 | Train F1=0.9183 | Val F1=0.8991

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 83.51it/s, loss=0.338]

Epoch  17 | Train F1=0.9188 | Val F1=0.8998

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 79.05it/s, loss=0.295]

Epoch  18 | Train F1=0.9157 | Val F1=0.8962

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 89.12it/s, loss=0.229]

Epoch  19 | Train F1=0.9161 | Val F1=0.9006

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 80.36it/s, loss=0.305]

Epoch  20 | Train F1=0.9293 | Val F1=0.9102

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 88.19it/s, loss=0.567]

Epoch  21 | Train F1=0.9339 | Val F1=0.9139

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 92.00it/s, loss=0.286]

Epoch  22 | Train F1=0.9341 | Val F1=0.9153

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 92.05it/s, loss=0.307]

Epoch  23 | Train F1=0.9396 | Val F1=0.9139

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 87.44it/s, loss=0.306]

Epoch  24 | Train F1=0.9384 | Val F1=0.9143

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 80.10it/s, loss=0.385]

Epoch  25 | Train F1=0.9373 | Val F1=0.9157

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 85.38it/s, loss=0.219]

Epoch  26 | Train F1=0.9408 | Val F1=0.9159

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 90.95it/s, loss=0.578]

Epoch  27 | Train F1=0.9451 | Val F1=0.9208

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 80.61it/s, loss=0.242]

Epoch  28 | Train F1=0.9405 | Val F1=0.9187

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 89.65it/s, loss=0.332]

Epoch  29 | Train F1=0.9405 | Val F1=0.9207

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 86.53it/s, loss=0.393]

Epoch  30 | Train F1=0.9436 | Val F1=0.9201

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 90.83it/s, loss=0.687]

Epoch  31 | Train F1=0.9453 | Val F1=0.9229

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 91.32it/s, loss=0.558]

Epoch  32 | Train F1=0.9445 | Val F1=0.9221

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 85.35it/s, loss=0.222]

Epoch  33 | Train F1=0.9450 | Val F1=0.9204

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 81.33it/s, loss=0.285]

Epoch  34 | Train F1=0.9446 | Val F1=0.9190

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 72.32it/s, loss=0.222]

Epoch  35 | Train F1=0.9515 | Val F1=0.9208

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 80.20it/s, loss=0.155]

Epoch  36 | Train F1=0.9463 | Val F1=0.9236

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 90.33it/s, loss=0.223]

Epoch  37 | Train F1=0.9497 | Val F1=0.9249

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 86.41it/s, loss=0.427]

Epoch  38 | Train F1=0.9478 | Val F1=0.9226

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 87.68it/s, loss=0.296]

Epoch  39 | Train F1=0.9524 | Val F1=0.9286

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 87.35it/s, loss=0.314]

Epoch  40 | Train F1=0.9558 | Val F1=0.9270

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 80.05it/s, loss=0.279]

Epoch  41 | Train F1=0.9538 | Val F1=0.9260

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 78.12it/s, loss=0.295]

Epoch  42 | Train F1=0.9553 | Val F1=0.9271

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 86.45it/s, loss=0.31]

Epoch  43 | Train F1=0.9567 | Val F1=0.9285

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 83.46it/s, loss=0.262]

Epoch  44 | Train F1=0.9554 | Val F1=0.9269

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 85.44it/s, loss=0.146]

Epoch  45 | Train F1=0.9579 | Val F1=0.9274

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 86.07it/s, loss=0.0531]

Epoch  46 | Train F1=0.9606 | Val F1=0.9288

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 89.74it/s, loss=0.227]

Epoch  47 | Train F1=0.9546 | Val F1=0.9258

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 84.28it/s, loss=0.0609]

Epoch  48 | Train F1=0.9606 | Val F1=0.9306

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 84.64it/s, loss=0.0888]

Epoch  49 | Train F1=0.9570 | Val F1=0.9257

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 83.96it/s, loss=0.234]

Epoch  50 | Train F1=0.9621 | Val F1=0.9295

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 85.58it/s, loss=1.12]

Epoch   1 | Train F1=0.4816 | Val F1=0.4806

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 87.68it/s, loss=0.759]

Epoch   2 | Train F1=0.5681 | Val F1=0.5586

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 84.72it/s, loss=0.612]

Epoch   3 | Train F1=0.6896 | Val F1=0.6597

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 88.95it/s, loss=0.74]

Epoch   4 | Train F1=0.7733 | Val F1=0.7649

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 79.25it/s, loss=0.599]

Epoch   5 | Train F1=0.8036 | Val F1=0.7894

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 72.15it/s, loss=0.442]

Epoch   6 | Train F1=0.8273 | Val F1=0.8133

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 70.70it/s, loss=0.405]

Epoch   7 | Train F1=0.8452 | Val F1=0.8289

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 86.06it/s, loss=0.504]

Epoch   8 | Train F1=0.8502 | Val F1=0.8397

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 86.53it/s, loss=0.504]

Epoch   9 | Train F1=0.8694 | Val F1=0.8602

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 89.66it/s, loss=0.436]

Epoch  10 | Train F1=0.8764 | Val F1=0.8617

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 88.11it/s, loss=0.473]

Epoch  11 | Train F1=0.8754 | Val F1=0.8633

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 85.78it/s, loss=0.332]

Epoch  12 | Train F1=0.8862 | Val F1=0.8788

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 87.45it/s, loss=0.701]

Epoch  13 | Train F1=0.8818 | Val F1=0.8651

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 87.89it/s, loss=0.292]

Epoch  14 | Train F1=0.8930 | Val F1=0.8753

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 88.45it/s, loss=0.251]

Epoch  15 | Train F1=0.8983 | Val F1=0.8877

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 79.01it/s, loss=0.355]

Epoch  16 | Train F1=0.9002 | Val F1=0.8874

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 85.51it/s, loss=0.394]

Epoch  17 | Train F1=0.9016 | Val F1=0.8851

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 86.42it/s, loss=0.37]

Epoch  18 | Train F1=0.9045 | Val F1=0.8840

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 86.62it/s, loss=0.591]

Epoch  19 | Train F1=0.9131 | Val F1=0.8908

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 87.18it/s, loss=0.369]

Epoch  20 | Train F1=0.9028 | Val F1=0.8787

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 75.53it/s, loss=0.271]

Epoch  21 | Train F1=0.9135 | Val F1=0.8932

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 74.55it/s, loss=0.587]

Epoch  22 | Train F1=0.9094 | Val F1=0.8921

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 78.26it/s, loss=0.197]

Epoch  23 | Train F1=0.9189 | Val F1=0.8963

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 86.08it/s, loss=0.196]

Epoch  24 | Train F1=0.9233 | Val F1=0.9025

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 90.37it/s, loss=0.268]

Epoch  25 | Train F1=0.9232 | Val F1=0.8983

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 88.77it/s, loss=0.25]

Epoch  26 | Train F1=0.9229 | Val F1=0.8976

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 86.55it/s, loss=0.233]

Epoch  27 | Train F1=0.9231 | Val F1=0.8973

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 72.63it/s, loss=0.282]

Epoch  28 | Train F1=0.9238 | Val F1=0.8944

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 66.95it/s, loss=0.297]

Epoch  29 | Train F1=0.9257 | Val F1=0.8998

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 73.73it/s, loss=0.29]

Epoch  30 | Train F1=0.9301 | Val F1=0.9035

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 90.81it/s, loss=0.385]

Epoch  31 | Train F1=0.9267 | Val F1=0.8963

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 86.43it/s, loss=0.231]

Epoch  32 | Train F1=0.9351 | Val F1=0.9070

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 90.75it/s, loss=0.168]

Epoch  33 | Train F1=0.9335 | Val F1=0.9024

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 86.41it/s, loss=0.35]

Epoch  34 | Train F1=0.9360 | Val F1=0.9039

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 88.74it/s, loss=0.253]

Epoch  35 | Train F1=0.9353 | Val F1=0.9064

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 86.52it/s, loss=0.275]

Epoch  36 | Train F1=0.9320 | Val F1=0.9036

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 92.96it/s, loss=0.217]

Epoch  37 | Train F1=0.9358 | Val F1=0.9072

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 85.32it/s, loss=0.343]

Epoch  38 | Train F1=0.9398 | Val F1=0.9077

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 83.34it/s, loss=0.257]

Epoch  39 | Train F1=0.9383 | Val F1=0.9068

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 87.46it/s, loss=0.168]

Epoch  40 | Train F1=0.9408 | Val F1=0.9056

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 92.39it/s, loss=0.311]

Epoch  41 | Train F1=0.9417 | Val F1=0.9105

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 91.75it/s, loss=0.543]

Epoch  42 | Train F1=0.9393 | Val F1=0.9041

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 86.27it/s, loss=0.177]

Epoch  43 | Train F1=0.9429 | Val F1=0.9121

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 72.23it/s, loss=0.293]

Epoch  44 | Train F1=0.9411 | Val F1=0.9035

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 86.64it/s, loss=0.381]

Epoch  45 | Train F1=0.9422 | Val F1=0.9070

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 83.56it/s, loss=0.212]

Epoch  46 | Train F1=0.9438 | Val F1=0.9063

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 87.85it/s, loss=0.271]

Epoch  47 | Train F1=0.9447 | Val F1=0.9122

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 86.36it/s, loss=0.168]

Epoch  48 | Train F1=0.9432 | Val F1=0.9067

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 89.13it/s, loss=0.338]

Epoch  49 | Train F1=0.9420 | Val F1=0.9044

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 86.22it/s, loss=0.218]

Epoch  50 | Train F1=0.9494 | Val F1=0.9123

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 84.48it/s, loss=0.725]

Epoch   1 | Train F1=0.6458 | Val F1=0.6459

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 89.32it/s, loss=0.4]

Epoch   2 | Train F1=0.6553 | Val F1=0.6503

Epoch 3: 100%|██████████| 132/132 [00:01<00:00, 81.76it/s, loss=0.714]

Epoch   3 | Train F1=0.7558 | Val F1=0.7593

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 86.97it/s, loss=0.578]

Epoch   4 | Train F1=0.7678 | Val F1=0.7558

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 88.45it/s, loss=0.582]

Epoch   5 | Train F1=0.8206 | Val F1=0.8280

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 88.95it/s, loss=0.327]

Epoch   6 | Train F1=0.8367 | Val F1=0.8320

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 85.58it/s, loss=0.45]

Epoch   7 | Train F1=0.8511 | Val F1=0.8506

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 83.74it/s, loss=0.488]

Epoch   8 | Train F1=0.8655 | Val F1=0.8600

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 84.62it/s, loss=0.527]

Epoch   9 | Train F1=0.8805 | Val F1=0.8777

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 92.22it/s, loss=0.312]

Epoch  10 | Train F1=0.8939 | Val F1=0.8962

Epoch 11: 100%|██████████| 132/132 [00:01<00:00, 72.77it/s, loss=0.297]

Epoch  11 | Train F1=0.8882 | Val F1=0.8883

Epoch 12: 100%|██████████| 132/132 [00:01<00:00, 89.38it/s, loss=0.361]

Epoch  12 | Train F1=0.8983 | Val F1=0.8968

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 87.03it/s, loss=0.393]

Epoch  13 | Train F1=0.9128 | Val F1=0.9118

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 86.48it/s, loss=0.355]

Epoch  14 | Train F1=0.9119 | Val F1=0.9108

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 89.02it/s, loss=0.195]

Epoch  15 | Train F1=0.9162 | Val F1=0.9114

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 69.67it/s, loss=0.343]

Epoch  16 | Train F1=0.9122 | Val F1=0.9080

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 69.97it/s, loss=0.268]

Epoch  17 | Train F1=0.9215 | Val F1=0.9173

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 70.00it/s, loss=0.255]

Epoch  18 | Train F1=0.9221 | Val F1=0.9155

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 83.64it/s, loss=0.216]

Epoch  19 | Train F1=0.9252 | Val F1=0.9174

Epoch 20: 100%|██████████| 132/132 [00:01<00:00, 83.31it/s, loss=0.268]

Epoch  20 | Train F1=0.9212 | Val F1=0.9085

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 84.30it/s, loss=0.506]

Epoch  21 | Train F1=0.9221 | Val F1=0.9116

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 87.47it/s, loss=0.263]

Epoch  22 | Train F1=0.9304 | Val F1=0.9164

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 83.52it/s, loss=0.377]

Epoch  23 | Train F1=0.9341 | Val F1=0.9220

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 81.14it/s, loss=0.195]

Epoch  24 | Train F1=0.9336 | Val F1=0.9164

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 86.39it/s, loss=0.329]

Epoch  25 | Train F1=0.9339 | Val F1=0.9197

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 78.43it/s, loss=0.167]

Epoch  26 | Train F1=0.9331 | Val F1=0.9210

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 80.86it/s, loss=0.441]

Epoch  27 | Train F1=0.9351 | Val F1=0.9202

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 86.78it/s, loss=0.298]

Epoch  28 | Train F1=0.9325 | Val F1=0.9204

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 88.24it/s, loss=0.403]

Epoch  29 | Train F1=0.9365 | Val F1=0.9210

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 89.37it/s, loss=0.162]

Epoch  30 | Train F1=0.9413 | Val F1=0.9223

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 81.15it/s, loss=0.172]

Epoch  31 | Train F1=0.9359 | Val F1=0.9195

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 81.07it/s, loss=0.321]

Epoch  32 | Train F1=0.9387 | Val F1=0.9221

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 89.12it/s, loss=0.234]

Epoch  33 | Train F1=0.9375 | Val F1=0.9166

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 81.36it/s, loss=0.291]

Epoch  34 | Train F1=0.9397 | Val F1=0.9249

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 90.20it/s, loss=0.278]

Epoch  35 | Train F1=0.9418 | Val F1=0.9249

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 86.09it/s, loss=0.291]

Epoch  36 | Train F1=0.9427 | Val F1=0.9262

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 86.13it/s, loss=0.325]

Epoch  37 | Train F1=0.9440 | Val F1=0.9275

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 89.26it/s, loss=0.129]

Epoch  38 | Train F1=0.9444 | Val F1=0.9240

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 76.23it/s, loss=0.236]

Epoch  39 | Train F1=0.9479 | Val F1=0.9258

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 81.14it/s, loss=0.164]

Epoch  40 | Train F1=0.9407 | Val F1=0.9191

Epoch 41: 100%|██████████| 132/132 [00:01<00:00, 79.56it/s, loss=0.125]

Epoch  41 | Train F1=0.9484 | Val F1=0.9287

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 77.89it/s, loss=0.305]

Epoch  42 | Train F1=0.9407 | Val F1=0.9230

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 89.66it/s, loss=0.155]

Epoch  43 | Train F1=0.9473 | Val F1=0.9253

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 89.66it/s, loss=0.205]

Epoch  44 | Train F1=0.9441 | Val F1=0.9249

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 89.15it/s, loss=0.215]

Epoch  45 | Train F1=0.9496 | Val F1=0.9271

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 87.68it/s, loss=0.145]

Epoch  46 | Train F1=0.9507 | Val F1=0.9275

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 89.62it/s, loss=0.286]

Epoch  47 | Train F1=0.9485 | Val F1=0.9293

Epoch 48: 100%|██████████| 132/132 [00:01<00:00, 79.05it/s, loss=0.151]

Epoch  48 | Train F1=0.9523 | Val F1=0.9288

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 75.21it/s, loss=0.16]

Epoch  49 | Train F1=0.9504 | Val F1=0.9285

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 83.73it/s, loss=0.196]

Epoch  50 | Train F1=0.9527 | Val F1=0.9318

In [18]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
for i in range(7):
    df.iloc[i,i+1] = '-'
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'
/tmp/ipykernel_1020/4280109102.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[i,i+1] = '-'

          Treino head chest upperarm forearm waist thigh shin
head          84    -    56       61      33    34    40   31
chest         92   48     -       45      42    42    54   44
upperarm      91   47    59        -      30    15    57   51
forearm       88   31    30       28       -    25    31   38
waist         93   42    26       15      28     -    26   13
thigh         93   46    46       48      38    45     -   54
shin          93   24    50       52      31    24    41    -

## Baseline 3: passa-baixas 2 Hz

In [19]:
sos = butter(N=6, Wn=2, btype='lp', fs=50, output='sos')
Xf = np.swapaxes(sosfiltfilt(sos, np.swapaxes(Xcort, 1, 2)), 1, 2)

In [20]:
pasta = '/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/modelos/'
baselinef1 = np.zeros((7,7))
for i, pos in enumerate(posis):
    inds = ycort[:,0]==i
    X = Xf[inds]
    y = ycort[inds][:,1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
    X_train = torch.tensor(X_train, dtype=torch.float32)
    X_test  = torch.tensor(X_test, dtype=torch.float32)
    y_train = torch.tensor(y_train, dtype=torch.long)
    y_test  = torch.tensor(y_test, dtype=torch.long)
    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
    test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
    enc, cla, history = train_model(train_loader, test_loader, device, n_epochs=50)
    nome = 'baseline_lp2Hz_encoder_'+pos+'.pth'
    torch.save(enc.state_dict(), pasta+nome)
    nome = 'baseline_lp2Hz_classifier_'+pos+'.pth'
    torch.save(cla.state_dict(), pasta+nome)
    for j in range(7):
        inds = ycort[:,0]==j
        X = Xf[inds]
        y = ycort[inds][:,1]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)
        X_test  = torch.tensor(X_test, dtype=torch.float32)
        y_test  = torch.tensor(y_test, dtype=torch.long)
        test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)
        _, test_f1 = evaluate(enc, cla, test_loader, nn.CrossEntropyLoss(), device)
        baselinef1[i,j] = test_f1

Epoch 1: 100%|██████████| 133/133 [00:02<00:00, 63.75it/s, loss=0.76]

Epoch   1 | Train F1=0.5682 | Val F1=0.5659

Epoch 2: 100%|██████████| 133/133 [00:02<00:00, 47.84it/s, loss=0.607]

Epoch   2 | Train F1=0.6299 | Val F1=0.6280

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 77.21it/s, loss=0.68]

Epoch   3 | Train F1=0.7417 | Val F1=0.7103

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 80.50it/s, loss=0.518]

Epoch   4 | Train F1=0.7773 | Val F1=0.7610

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 79.97it/s, loss=0.572]

Epoch   5 | Train F1=0.7768 | Val F1=0.7540

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 100.61it/s, loss=0.551]

Epoch   6 | Train F1=0.8141 | Val F1=0.7888

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 95.90it/s, loss=0.584]

Epoch   7 | Train F1=0.8237 | Val F1=0.8063

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 94.65it/s, loss=0.456]

Epoch   8 | Train F1=0.8410 | Val F1=0.8157

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 90.67it/s, loss=0.459]

Epoch   9 | Train F1=0.8602 | Val F1=0.8430

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 103.49it/s, loss=0.644]

Epoch  10 | Train F1=0.8759 | Val F1=0.8529

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 102.72it/s, loss=0.364]

Epoch  11 | Train F1=0.8734 | Val F1=0.8500

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 111.24it/s, loss=0.391]

Epoch  12 | Train F1=0.8820 | Val F1=0.8576

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 111.32it/s, loss=0.319]

Epoch  13 | Train F1=0.8848 | Val F1=0.8621

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 109.54it/s, loss=0.464]

Epoch  14 | Train F1=0.8805 | Val F1=0.8583

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 91.15it/s, loss=0.374]

Epoch  15 | Train F1=0.8899 | Val F1=0.8695

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 94.74it/s, loss=0.397]

Epoch  16 | Train F1=0.8896 | Val F1=0.8648

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 98.51it/s, loss=0.342]

Epoch  17 | Train F1=0.8945 | Val F1=0.8638

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 112.56it/s, loss=0.373]

Epoch  18 | Train F1=0.9013 | Val F1=0.8791

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 113.40it/s, loss=0.251]

Epoch  19 | Train F1=0.8997 | Val F1=0.8741

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 108.87it/s, loss=0.211]

Epoch  20 | Train F1=0.9012 | Val F1=0.8764

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 111.46it/s, loss=0.344]

Epoch  21 | Train F1=0.9144 | Val F1=0.8909

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 113.04it/s, loss=0.287]

Epoch  22 | Train F1=0.9151 | Val F1=0.8916

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 94.19it/s, loss=0.174]

Epoch  23 | Train F1=0.9133 | Val F1=0.8880

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 88.68it/s, loss=0.194]

Epoch  24 | Train F1=0.9163 | Val F1=0.8901

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 90.86it/s, loss=0.317]

Epoch  25 | Train F1=0.9142 | Val F1=0.8890

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 107.18it/s, loss=0.44]

Epoch  26 | Train F1=0.9183 | Val F1=0.8930

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 101.55it/s, loss=0.471]

Epoch  27 | Train F1=0.9209 | Val F1=0.8958

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 110.09it/s, loss=0.313]

Epoch  28 | Train F1=0.9167 | Val F1=0.8954

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 106.80it/s, loss=0.627]

Epoch  29 | Train F1=0.9177 | Val F1=0.8887

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 110.76it/s, loss=0.327]

Epoch  30 | Train F1=0.9231 | Val F1=0.8963

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 93.10it/s, loss=0.436]

Epoch  31 | Train F1=0.9224 | Val F1=0.8898

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 88.04it/s, loss=0.298]

Epoch  32 | Train F1=0.9260 | Val F1=0.8967

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 93.11it/s, loss=0.419]

Epoch  33 | Train F1=0.9296 | Val F1=0.9010

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 109.34it/s, loss=0.149]

Epoch  34 | Train F1=0.9284 | Val F1=0.8935

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 109.76it/s, loss=0.233]

Epoch  35 | Train F1=0.9246 | Val F1=0.8899

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 110.67it/s, loss=0.336]

Epoch  36 | Train F1=0.9300 | Val F1=0.8981

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 108.44it/s, loss=0.179]

Epoch  37 | Train F1=0.9305 | Val F1=0.8929

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 101.43it/s, loss=0.272]

Epoch  38 | Train F1=0.9341 | Val F1=0.8985

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 91.29it/s, loss=0.352]

Epoch  39 | Train F1=0.9345 | Val F1=0.9026

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 94.12it/s, loss=0.139]

Epoch  40 | Train F1=0.9248 | Val F1=0.8913

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 91.83it/s, loss=0.448]

Epoch  41 | Train F1=0.9385 | Val F1=0.9032

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 107.85it/s, loss=0.359]

Epoch  42 | Train F1=0.9352 | Val F1=0.8989

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 101.79it/s, loss=0.158]

Epoch  43 | Train F1=0.9364 | Val F1=0.9018

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 78.30it/s, loss=0.321]

Epoch  44 | Train F1=0.9399 | Val F1=0.9061

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 104.53it/s, loss=0.36]

Epoch  45 | Train F1=0.9395 | Val F1=0.9041

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 99.59it/s, loss=0.246]

Epoch  46 | Train F1=0.9440 | Val F1=0.9098

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 82.01it/s, loss=0.126]

Epoch  47 | Train F1=0.9390 | Val F1=0.9015

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 85.24it/s, loss=0.292]

Epoch  48 | Train F1=0.9383 | Val F1=0.9036

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 77.60it/s, loss=0.313]

Epoch  49 | Train F1=0.9411 | Val F1=0.9079

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 104.76it/s, loss=0.29]

Epoch  50 | Train F1=0.9410 | Val F1=0.9072

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 102.39it/s, loss=1.03]

Epoch   1 | Train F1=0.4670 | Val F1=0.4588

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 106.68it/s, loss=0.723]

Epoch   2 | Train F1=0.6387 | Val F1=0.6181

Epoch 3: 100%|██████████| 132/132 [00:01<00:00, 86.79it/s, loss=0.77]

Epoch   3 | Train F1=0.7007 | Val F1=0.6895

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 92.08it/s, loss=0.777]

Epoch   4 | Train F1=0.7361 | Val F1=0.7194

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 86.47it/s, loss=0.712]

Epoch   5 | Train F1=0.7595 | Val F1=0.7515

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 103.56it/s, loss=0.638]

Epoch   6 | Train F1=0.7994 | Val F1=0.7794

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 96.55it/s, loss=0.557]

Epoch   7 | Train F1=0.8016 | Val F1=0.7851

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 100.16it/s, loss=0.551]

Epoch   8 | Train F1=0.8208 | Val F1=0.7994

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 104.60it/s, loss=0.39]

Epoch   9 | Train F1=0.8245 | Val F1=0.8023

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 103.38it/s, loss=0.44]

Epoch  10 | Train F1=0.8342 | Val F1=0.8162

Epoch 11: 100%|██████████| 132/132 [00:02<00:00, 55.63it/s, loss=0.491]

Epoch  11 | Train F1=0.8415 | Val F1=0.8163

Epoch 12: 100%|██████████| 132/132 [00:01<00:00, 85.20it/s, loss=0.447]

Epoch  12 | Train F1=0.8503 | Val F1=0.8220

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 104.45it/s, loss=0.458]

Epoch  13 | Train F1=0.8582 | Val F1=0.8291

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 103.95it/s, loss=0.683]

Epoch  14 | Train F1=0.8536 | Val F1=0.8272

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 101.83it/s, loss=0.436]

Epoch  15 | Train F1=0.8579 | Val F1=0.8283

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 102.74it/s, loss=0.552]

Epoch  16 | Train F1=0.8661 | Val F1=0.8403

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 101.25it/s, loss=0.474]

Epoch  17 | Train F1=0.8681 | Val F1=0.8367

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 90.40it/s, loss=0.483]

Epoch  18 | Train F1=0.8669 | Val F1=0.8402

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 84.77it/s, loss=0.471]

Epoch  19 | Train F1=0.8556 | Val F1=0.8224

Epoch 20: 100%|██████████| 132/132 [00:02<00:00, 57.91it/s, loss=0.594]

Epoch  20 | Train F1=0.8731 | Val F1=0.8403

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 99.89it/s, loss=0.52]

Epoch  21 | Train F1=0.8794 | Val F1=0.8447

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 97.66it/s, loss=0.383]

Epoch  22 | Train F1=0.8806 | Val F1=0.8442

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 97.59it/s, loss=0.537]

Epoch  23 | Train F1=0.8781 | Val F1=0.8427

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 96.92it/s, loss=0.566]

Epoch  24 | Train F1=0.8829 | Val F1=0.8500

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 101.03it/s, loss=0.354]

Epoch  25 | Train F1=0.8819 | Val F1=0.8430

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 86.70it/s, loss=0.545]

Epoch  26 | Train F1=0.8865 | Val F1=0.8515

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 88.80it/s, loss=0.367]

Epoch  27 | Train F1=0.8892 | Val F1=0.8505

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 84.38it/s, loss=0.386]

Epoch  28 | Train F1=0.8943 | Val F1=0.8539

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 104.71it/s, loss=0.409]

Epoch  29 | Train F1=0.8888 | Val F1=0.8499

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 102.05it/s, loss=0.401]

Epoch  30 | Train F1=0.8928 | Val F1=0.8489

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 102.34it/s, loss=0.394]

Epoch  31 | Train F1=0.8958 | Val F1=0.8533

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 102.16it/s, loss=0.546]

Epoch  32 | Train F1=0.8905 | Val F1=0.8489

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 102.36it/s, loss=0.328]

Epoch  33 | Train F1=0.8960 | Val F1=0.8480

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 88.26it/s, loss=0.295]

Epoch  34 | Train F1=0.8968 | Val F1=0.8534

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 85.70it/s, loss=0.303]

Epoch  35 | Train F1=0.8969 | Val F1=0.8461

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 80.33it/s, loss=0.451]

Epoch  36 | Train F1=0.9052 | Val F1=0.8546

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 90.78it/s, loss=0.366]

Epoch  37 | Train F1=0.8998 | Val F1=0.8468

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 94.29it/s, loss=0.383]

Epoch  38 | Train F1=0.9008 | Val F1=0.8529

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 100.32it/s, loss=0.412]

Epoch  39 | Train F1=0.8997 | Val F1=0.8548

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 101.81it/s, loss=0.475]

Epoch  40 | Train F1=0.9069 | Val F1=0.8607

Epoch 41: 100%|██████████| 132/132 [00:01<00:00, 96.30it/s, loss=0.527]

Epoch  41 | Train F1=0.9018 | Val F1=0.8513

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 81.34it/s, loss=0.235]

Epoch  42 | Train F1=0.9060 | Val F1=0.8569

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 83.40it/s, loss=0.34]

Epoch  43 | Train F1=0.9074 | Val F1=0.8597

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 82.29it/s, loss=0.28]

Epoch  44 | Train F1=0.9077 | Val F1=0.8586

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 96.27it/s, loss=0.373]

Epoch  45 | Train F1=0.9162 | Val F1=0.8608

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 71.30it/s, loss=0.342]

Epoch  46 | Train F1=0.9079 | Val F1=0.8508

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 98.94it/s, loss=0.46]

Epoch  47 | Train F1=0.9092 | Val F1=0.8578

Epoch 48: 100%|██████████| 132/132 [00:01<00:00, 99.25it/s, loss=0.279]

Epoch  48 | Train F1=0.9124 | Val F1=0.8543

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 79.99it/s, loss=0.329]

Epoch  49 | Train F1=0.9125 | Val F1=0.8590

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 82.09it/s, loss=0.422]

Epoch  50 | Train F1=0.9127 | Val F1=0.8608

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 90.20it/s, loss=1.12]

Epoch   1 | Train F1=0.4893 | Val F1=0.4891

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 99.81it/s, loss=0.868]

Epoch   2 | Train F1=0.6948 | Val F1=0.6924

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 97.88it/s, loss=0.611]

Epoch   3 | Train F1=0.6909 | Val F1=0.6877

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 95.77it/s, loss=0.767]

Epoch   4 | Train F1=0.7329 | Val F1=0.7291

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 93.59it/s, loss=0.713]

Epoch   5 | Train F1=0.7310 | Val F1=0.7201

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 79.56it/s, loss=0.509]

Epoch   6 | Train F1=0.7520 | Val F1=0.7399

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 81.01it/s, loss=0.605]

Epoch   7 | Train F1=0.7599 | Val F1=0.7500

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 97.16it/s, loss=0.72]

Epoch   8 | Train F1=0.7674 | Val F1=0.7501

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 99.29it/s, loss=0.733]

Epoch   9 | Train F1=0.7843 | Val F1=0.7686

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 97.99it/s, loss=0.445]

Epoch  10 | Train F1=0.7861 | Val F1=0.7671

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 96.34it/s, loss=0.551]

Epoch  11 | Train F1=0.7714 | Val F1=0.7561

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 95.81it/s, loss=0.474]

Epoch  12 | Train F1=0.7930 | Val F1=0.7723

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 83.53it/s, loss=0.522]

Epoch  13 | Train F1=0.7787 | Val F1=0.7564

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 87.08it/s, loss=0.513]

Epoch  14 | Train F1=0.7762 | Val F1=0.7609

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 83.70it/s, loss=0.603]

Epoch  15 | Train F1=0.8076 | Val F1=0.7843

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 89.13it/s, loss=0.696]

Epoch  16 | Train F1=0.7978 | Val F1=0.7751

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 93.61it/s, loss=0.49]

Epoch  17 | Train F1=0.8034 | Val F1=0.7843

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 88.47it/s, loss=0.636]

Epoch  18 | Train F1=0.8132 | Val F1=0.7857

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 91.43it/s, loss=0.571]

Epoch  19 | Train F1=0.7939 | Val F1=0.7770

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 93.45it/s, loss=0.564]

Epoch  20 | Train F1=0.8000 | Val F1=0.7746

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 78.95it/s, loss=0.373]

Epoch  21 | Train F1=0.7977 | Val F1=0.7682

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 84.85it/s, loss=0.381]

Epoch  22 | Train F1=0.8175 | Val F1=0.7933

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 79.45it/s, loss=0.64]

Epoch  23 | Train F1=0.8173 | Val F1=0.7920

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 97.59it/s, loss=0.473]

Epoch  24 | Train F1=0.8123 | Val F1=0.7862

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 94.44it/s, loss=0.48]

Epoch  25 | Train F1=0.8159 | Val F1=0.7840

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 97.83it/s, loss=0.378]

Epoch  26 | Train F1=0.8280 | Val F1=0.7957

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 90.52it/s, loss=0.423]

Epoch  27 | Train F1=0.8226 | Val F1=0.7918

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 85.19it/s, loss=0.549]

Epoch  28 | Train F1=0.8356 | Val F1=0.8022

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 75.22it/s, loss=0.588]

Epoch  29 | Train F1=0.8339 | Val F1=0.8016

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 86.27it/s, loss=0.448]

Epoch  30 | Train F1=0.8269 | Val F1=0.7907

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 83.57it/s, loss=0.415]

Epoch  31 | Train F1=0.8362 | Val F1=0.7996

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 89.01it/s, loss=0.534]

Epoch  32 | Train F1=0.8407 | Val F1=0.8049

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 93.96it/s, loss=0.32]

Epoch  33 | Train F1=0.8375 | Val F1=0.7966

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 91.67it/s, loss=0.429]

Epoch  34 | Train F1=0.8426 | Val F1=0.8024

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 96.17it/s, loss=0.5]

Epoch  35 | Train F1=0.8390 | Val F1=0.7999

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 84.81it/s, loss=0.412]

Epoch  36 | Train F1=0.8454 | Val F1=0.7984

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 83.99it/s, loss=0.72]

Epoch  37 | Train F1=0.8297 | Val F1=0.7855

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 80.37it/s, loss=0.473]

Epoch  38 | Train F1=0.8479 | Val F1=0.8005

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 83.80it/s, loss=0.355]

Epoch  39 | Train F1=0.8273 | Val F1=0.7857

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 89.54it/s, loss=0.493]

Epoch  40 | Train F1=0.8392 | Val F1=0.7934

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 98.68it/s, loss=0.323]

Epoch  41 | Train F1=0.8498 | Val F1=0.8115

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 97.96it/s, loss=0.554]

Epoch  42 | Train F1=0.8375 | Val F1=0.7979

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 93.74it/s, loss=0.487]

Epoch  43 | Train F1=0.8489 | Val F1=0.8013

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 75.31it/s, loss=0.363]

Epoch  44 | Train F1=0.8516 | Val F1=0.8081

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 80.77it/s, loss=0.495]

Epoch  45 | Train F1=0.8526 | Val F1=0.8032

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 82.40it/s, loss=0.583]

Epoch  46 | Train F1=0.8562 | Val F1=0.8011

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 91.09it/s, loss=0.503]

Epoch  47 | Train F1=0.8562 | Val F1=0.8052

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 89.68it/s, loss=0.392]

Epoch  48 | Train F1=0.8490 | Val F1=0.8042

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 92.21it/s, loss=0.571]

Epoch  49 | Train F1=0.8522 | Val F1=0.7967

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 87.60it/s, loss=0.304]

Epoch  50 | Train F1=0.8602 | Val F1=0.8064

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 88.85it/s, loss=0.778]

Epoch   1 | Train F1=0.5723 | Val F1=0.5614

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 89.52it/s, loss=0.568]

Epoch   2 | Train F1=0.7700 | Val F1=0.7296

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 72.97it/s, loss=0.456]

Epoch   3 | Train F1=0.8693 | Val F1=0.8567

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 92.82it/s, loss=0.165]

Epoch   4 | Train F1=0.8911 | Val F1=0.8803

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 87.97it/s, loss=0.34]

Epoch   5 | Train F1=0.9044 | Val F1=0.8849

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 88.80it/s, loss=0.327]

Epoch   6 | Train F1=0.9040 | Val F1=0.8899

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 90.78it/s, loss=0.501]

Epoch   7 | Train F1=0.9167 | Val F1=0.8962

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 88.17it/s, loss=0.26]

Epoch   8 | Train F1=0.9197 | Val F1=0.8989

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 84.82it/s, loss=0.383]

Epoch   9 | Train F1=0.9171 | Val F1=0.8992

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 75.82it/s, loss=0.41]

Epoch  10 | Train F1=0.9121 | Val F1=0.8895

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 86.02it/s, loss=0.258]

Epoch  11 | Train F1=0.9192 | Val F1=0.8985

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 88.09it/s, loss=0.258]

Epoch  12 | Train F1=0.9254 | Val F1=0.9007

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 94.65it/s, loss=0.241]

Epoch  13 | Train F1=0.9263 | Val F1=0.9045

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 90.62it/s, loss=0.195]

Epoch  14 | Train F1=0.9261 | Val F1=0.9064

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 91.97it/s, loss=0.158]

Epoch  15 | Train F1=0.9305 | Val F1=0.9048

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 78.94it/s, loss=0.28]

Epoch  16 | Train F1=0.9277 | Val F1=0.9053

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 81.34it/s, loss=0.18]

Epoch  17 | Train F1=0.9348 | Val F1=0.9105

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 81.66it/s, loss=0.287]

Epoch  18 | Train F1=0.9341 | Val F1=0.9062

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 91.74it/s, loss=0.349]

Epoch  19 | Train F1=0.9399 | Val F1=0.9141

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 93.68it/s, loss=0.246]

Epoch  20 | Train F1=0.9327 | Val F1=0.9109

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 89.84it/s, loss=0.342]

Epoch  21 | Train F1=0.9401 | Val F1=0.9148

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 89.65it/s, loss=0.217]

Epoch  22 | Train F1=0.9338 | Val F1=0.9083

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 91.24it/s, loss=0.107]

Epoch  23 | Train F1=0.9413 | Val F1=0.9169

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 71.26it/s, loss=0.304]

Epoch  24 | Train F1=0.9417 | Val F1=0.9133

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 73.71it/s, loss=0.338]

Epoch  25 | Train F1=0.9444 | Val F1=0.9163

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 74.80it/s, loss=0.146]

Epoch  26 | Train F1=0.9451 | Val F1=0.9156

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 88.61it/s, loss=0.233]

Epoch  27 | Train F1=0.9469 | Val F1=0.9164

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 90.08it/s, loss=0.182]

Epoch  28 | Train F1=0.9466 | Val F1=0.9189

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 86.47it/s, loss=0.156]

Epoch  29 | Train F1=0.9453 | Val F1=0.9157

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 88.96it/s, loss=0.221]

Epoch  30 | Train F1=0.9470 | Val F1=0.9205

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 79.73it/s, loss=0.231]

Epoch  31 | Train F1=0.9477 | Val F1=0.9170

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 71.49it/s, loss=0.369]

Epoch  32 | Train F1=0.9497 | Val F1=0.9167

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 69.31it/s, loss=0.321]

Epoch  33 | Train F1=0.9510 | Val F1=0.9163

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 83.20it/s, loss=0.201]

Epoch  34 | Train F1=0.9455 | Val F1=0.9116

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 84.48it/s, loss=0.202]

Epoch  35 | Train F1=0.9503 | Val F1=0.9153

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 80.00it/s, loss=0.102]

Epoch  36 | Train F1=0.9443 | Val F1=0.9132

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 87.45it/s, loss=0.282]

Epoch  37 | Train F1=0.9528 | Val F1=0.9180

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 87.94it/s, loss=0.11]

Epoch  38 | Train F1=0.9531 | Val F1=0.9193

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 83.29it/s, loss=0.238]

Epoch  39 | Train F1=0.9564 | Val F1=0.9235

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 83.71it/s, loss=0.12]

Epoch  40 | Train F1=0.9521 | Val F1=0.9222

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 81.05it/s, loss=0.153]

Epoch  41 | Train F1=0.9544 | Val F1=0.9220

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 86.89it/s, loss=0.201]

Epoch  42 | Train F1=0.9547 | Val F1=0.9251

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 89.62it/s, loss=0.396]

Epoch  43 | Train F1=0.9511 | Val F1=0.9184

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 85.74it/s, loss=0.131]

Epoch  44 | Train F1=0.9586 | Val F1=0.9215

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 83.22it/s, loss=0.138]

Epoch  45 | Train F1=0.9592 | Val F1=0.9241

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 89.10it/s, loss=0.192]

Epoch  46 | Train F1=0.9586 | Val F1=0.9267

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 68.71it/s, loss=0.15]

Epoch  47 | Train F1=0.9593 | Val F1=0.9214

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 79.44it/s, loss=0.494]

Epoch  48 | Train F1=0.9589 | Val F1=0.9216

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 77.78it/s, loss=0.266]

Epoch  49 | Train F1=0.9583 | Val F1=0.9216

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 86.03it/s, loss=0.215]

Epoch  50 | Train F1=0.9625 | Val F1=0.9260

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 87.17it/s, loss=1.03]

Epoch   1 | Train F1=0.5414 | Val F1=0.5283

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 85.38it/s, loss=0.673]

Epoch   2 | Train F1=0.6959 | Val F1=0.6756

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 69.52it/s, loss=0.639]

Epoch   3 | Train F1=0.7662 | Val F1=0.7506

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 80.88it/s, loss=0.386]

Epoch   4 | Train F1=0.7667 | Val F1=0.7542

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 72.16it/s, loss=0.702]

Epoch   5 | Train F1=0.7935 | Val F1=0.7757

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 89.10it/s, loss=0.522]

Epoch   6 | Train F1=0.8118 | Val F1=0.7933

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 89.15it/s, loss=0.411]

Epoch   7 | Train F1=0.8298 | Val F1=0.8146

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 86.58it/s, loss=0.498]

Epoch   8 | Train F1=0.8377 | Val F1=0.8209

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 87.39it/s, loss=0.444]

Epoch   9 | Train F1=0.8338 | Val F1=0.8167

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 84.70it/s, loss=0.43]

Epoch  10 | Train F1=0.8460 | Val F1=0.8314

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 74.58it/s, loss=0.457]

Epoch  11 | Train F1=0.8731 | Val F1=0.8603

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 80.74it/s, loss=0.277]

Epoch  12 | Train F1=0.8793 | Val F1=0.8644

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 84.22it/s, loss=0.403]

Epoch  13 | Train F1=0.8838 | Val F1=0.8673

Epoch 14: 100%|██████████| 133/133 [00:01<00:00, 88.19it/s, loss=0.173]

Epoch  14 | Train F1=0.8901 | Val F1=0.8748

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 86.71it/s, loss=0.278]

Epoch  15 | Train F1=0.8879 | Val F1=0.8796

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 88.49it/s, loss=0.322]

Epoch  16 | Train F1=0.8988 | Val F1=0.8815

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 87.48it/s, loss=0.506]

Epoch  17 | Train F1=0.9044 | Val F1=0.8816

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 83.04it/s, loss=0.224]

Epoch  18 | Train F1=0.9004 | Val F1=0.8756

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 83.98it/s, loss=0.315]

Epoch  19 | Train F1=0.9051 | Val F1=0.8862

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 81.09it/s, loss=0.143]

Epoch  20 | Train F1=0.9115 | Val F1=0.9002

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 77.72it/s, loss=0.488]

Epoch  21 | Train F1=0.9128 | Val F1=0.8898

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 88.91it/s, loss=0.239]

Epoch  22 | Train F1=0.9075 | Val F1=0.8885

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 85.17it/s, loss=0.383]

Epoch  23 | Train F1=0.9034 | Val F1=0.8840

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 84.60it/s, loss=0.448]

Epoch  24 | Train F1=0.9117 | Val F1=0.8978

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 83.65it/s, loss=0.527]

Epoch  25 | Train F1=0.9155 | Val F1=0.8951

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 79.43it/s, loss=0.105]

Epoch  26 | Train F1=0.9181 | Val F1=0.8960

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 82.29it/s, loss=0.443]

Epoch  27 | Train F1=0.9239 | Val F1=0.8989

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 89.66it/s, loss=0.197]

Epoch  28 | Train F1=0.9241 | Val F1=0.9004

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 75.87it/s, loss=0.356]

Epoch  29 | Train F1=0.9216 | Val F1=0.9027

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 86.14it/s, loss=0.244]

Epoch  30 | Train F1=0.9250 | Val F1=0.8968

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 87.10it/s, loss=0.461]

Epoch  31 | Train F1=0.9294 | Val F1=0.9059

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 87.27it/s, loss=0.456]

Epoch  32 | Train F1=0.9241 | Val F1=0.9037

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 87.53it/s, loss=0.35]

Epoch  33 | Train F1=0.9326 | Val F1=0.9075

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 88.72it/s, loss=0.171]

Epoch  34 | Train F1=0.9291 | Val F1=0.9062

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 88.95it/s, loss=0.327]

Epoch  35 | Train F1=0.9277 | Val F1=0.9018

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 81.95it/s, loss=0.123]

Epoch  36 | Train F1=0.9298 | Val F1=0.9010

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 80.34it/s, loss=0.328]

Epoch  37 | Train F1=0.9256 | Val F1=0.8994

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 84.44it/s, loss=0.31]

Epoch  38 | Train F1=0.9313 | Val F1=0.9049

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 87.18it/s, loss=0.146]

Epoch  39 | Train F1=0.9337 | Val F1=0.9059

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 78.24it/s, loss=0.183]

Epoch  40 | Train F1=0.9377 | Val F1=0.9083

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 84.61it/s, loss=0.163]

Epoch  41 | Train F1=0.9393 | Val F1=0.9060

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 80.42it/s, loss=0.36]

Epoch  42 | Train F1=0.9313 | Val F1=0.9046

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 71.20it/s, loss=0.568]

Epoch  43 | Train F1=0.9316 | Val F1=0.9030

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 70.65it/s, loss=0.111]

Epoch  44 | Train F1=0.9372 | Val F1=0.9052

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 81.69it/s, loss=0.329]

Epoch  45 | Train F1=0.9347 | Val F1=0.9062

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 86.62it/s, loss=0.175]

Epoch  46 | Train F1=0.9357 | Val F1=0.9008

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 85.30it/s, loss=0.0913]

Epoch  47 | Train F1=0.9360 | Val F1=0.9040

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 86.95it/s, loss=0.245]

Epoch  48 | Train F1=0.9346 | Val F1=0.9019

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 86.31it/s, loss=0.366]

Epoch  49 | Train F1=0.9386 | Val F1=0.9082

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 81.44it/s, loss=0.311]

Epoch  50 | Train F1=0.9409 | Val F1=0.9005

Epoch 1: 100%|██████████| 133/133 [00:01<00:00, 78.88it/s, loss=0.909]

Epoch   1 | Train F1=0.5243 | Val F1=0.5160

Epoch 2: 100%|██████████| 133/133 [00:01<00:00, 80.64it/s, loss=0.57]

Epoch   2 | Train F1=0.6316 | Val F1=0.6342

Epoch 3: 100%|██████████| 133/133 [00:01<00:00, 86.26it/s, loss=0.475]

Epoch   3 | Train F1=0.7570 | Val F1=0.7492

Epoch 4: 100%|██████████| 133/133 [00:01<00:00, 86.25it/s, loss=0.432]

Epoch   4 | Train F1=0.8010 | Val F1=0.7977

Epoch 5: 100%|██████████| 133/133 [00:01<00:00, 83.61it/s, loss=0.515]

Epoch   5 | Train F1=0.8274 | Val F1=0.8236

Epoch 6: 100%|██████████| 133/133 [00:01<00:00, 83.48it/s, loss=0.287]

Epoch   6 | Train F1=0.8426 | Val F1=0.8431

Epoch 7: 100%|██████████| 133/133 [00:01<00:00, 69.04it/s, loss=0.362]

Epoch   7 | Train F1=0.8542 | Val F1=0.8501

Epoch 8: 100%|██████████| 133/133 [00:01<00:00, 79.33it/s, loss=0.207]

Epoch   8 | Train F1=0.8588 | Val F1=0.8530

Epoch 9: 100%|██████████| 133/133 [00:01<00:00, 85.64it/s, loss=0.376]

Epoch   9 | Train F1=0.8672 | Val F1=0.8584

Epoch 10: 100%|██████████| 133/133 [00:01<00:00, 84.68it/s, loss=0.422]

Epoch  10 | Train F1=0.8723 | Val F1=0.8594

Epoch 11: 100%|██████████| 133/133 [00:01<00:00, 77.88it/s, loss=0.423]

Epoch  11 | Train F1=0.8799 | Val F1=0.8659

Epoch 12: 100%|██████████| 133/133 [00:01<00:00, 81.73it/s, loss=0.413]

Epoch  12 | Train F1=0.8747 | Val F1=0.8628

Epoch 13: 100%|██████████| 133/133 [00:01<00:00, 73.56it/s, loss=0.408]

Epoch  13 | Train F1=0.8835 | Val F1=0.8661

Epoch 14: 100%|██████████| 133/133 [00:02<00:00, 63.15it/s, loss=0.247]

Epoch  14 | Train F1=0.8858 | Val F1=0.8691

Epoch 15: 100%|██████████| 133/133 [00:01<00:00, 76.48it/s, loss=0.457]

Epoch  15 | Train F1=0.8761 | Val F1=0.8519

Epoch 16: 100%|██████████| 133/133 [00:01<00:00, 81.60it/s, loss=0.429]

Epoch  16 | Train F1=0.8864 | Val F1=0.8658

Epoch 17: 100%|██████████| 133/133 [00:01<00:00, 82.10it/s, loss=0.404]

Epoch  17 | Train F1=0.8890 | Val F1=0.8676

Epoch 18: 100%|██████████| 133/133 [00:01<00:00, 83.03it/s, loss=0.291]

Epoch  18 | Train F1=0.8909 | Val F1=0.8738

Epoch 19: 100%|██████████| 133/133 [00:01<00:00, 89.88it/s, loss=0.352]

Epoch  19 | Train F1=0.8965 | Val F1=0.8772

Epoch 20: 100%|██████████| 133/133 [00:01<00:00, 88.68it/s, loss=0.245]

Epoch  20 | Train F1=0.8949 | Val F1=0.8788

Epoch 21: 100%|██████████| 133/133 [00:01<00:00, 81.15it/s, loss=0.396]

Epoch  21 | Train F1=0.8955 | Val F1=0.8745

Epoch 22: 100%|██████████| 133/133 [00:01<00:00, 82.12it/s, loss=0.513]

Epoch  22 | Train F1=0.8995 | Val F1=0.8755

Epoch 23: 100%|██████████| 133/133 [00:01<00:00, 71.87it/s, loss=0.4]

Epoch  23 | Train F1=0.9046 | Val F1=0.8769

Epoch 24: 100%|██████████| 133/133 [00:01<00:00, 85.40it/s, loss=0.242]

Epoch  24 | Train F1=0.9045 | Val F1=0.8762

Epoch 25: 100%|██████████| 133/133 [00:01<00:00, 82.84it/s, loss=0.344]

Epoch  25 | Train F1=0.9031 | Val F1=0.8753

Epoch 26: 100%|██████████| 133/133 [00:01<00:00, 85.83it/s, loss=0.5]

Epoch  26 | Train F1=0.8952 | Val F1=0.8719

Epoch 27: 100%|██████████| 133/133 [00:01<00:00, 85.88it/s, loss=0.223]

Epoch  27 | Train F1=0.9091 | Val F1=0.8812

Epoch 28: 100%|██████████| 133/133 [00:01<00:00, 76.78it/s, loss=0.363]

Epoch  28 | Train F1=0.9078 | Val F1=0.8805

Epoch 29: 100%|██████████| 133/133 [00:01<00:00, 78.19it/s, loss=0.406]

Epoch  29 | Train F1=0.9087 | Val F1=0.8834

Epoch 30: 100%|██████████| 133/133 [00:01<00:00, 86.19it/s, loss=0.522]

Epoch  30 | Train F1=0.9119 | Val F1=0.8822

Epoch 31: 100%|██████████| 133/133 [00:01<00:00, 74.14it/s, loss=0.432]

Epoch  31 | Train F1=0.9125 | Val F1=0.8792

Epoch 32: 100%|██████████| 133/133 [00:01<00:00, 85.03it/s, loss=0.185]

Epoch  32 | Train F1=0.8981 | Val F1=0.8662

Epoch 33: 100%|██████████| 133/133 [00:01<00:00, 81.54it/s, loss=0.254]

Epoch  33 | Train F1=0.9148 | Val F1=0.8869

Epoch 34: 100%|██████████| 133/133 [00:01<00:00, 85.72it/s, loss=0.272]

Epoch  34 | Train F1=0.9128 | Val F1=0.8823

Epoch 35: 100%|██████████| 133/133 [00:01<00:00, 88.46it/s, loss=0.295]

Epoch  35 | Train F1=0.9075 | Val F1=0.8803

Epoch 36: 100%|██████████| 133/133 [00:01<00:00, 77.50it/s, loss=0.314]

Epoch  36 | Train F1=0.9164 | Val F1=0.8828

Epoch 37: 100%|██████████| 133/133 [00:01<00:00, 79.77it/s, loss=0.475]

Epoch  37 | Train F1=0.9169 | Val F1=0.8817

Epoch 38: 100%|██████████| 133/133 [00:01<00:00, 83.06it/s, loss=0.269]

Epoch  38 | Train F1=0.9193 | Val F1=0.8836

Epoch 39: 100%|██████████| 133/133 [00:01<00:00, 74.80it/s, loss=0.323]

Epoch  39 | Train F1=0.9174 | Val F1=0.8820

Epoch 40: 100%|██████████| 133/133 [00:01<00:00, 85.84it/s, loss=0.406]

Epoch  40 | Train F1=0.9173 | Val F1=0.8832

Epoch 41: 100%|██████████| 133/133 [00:01<00:00, 86.53it/s, loss=0.463]

Epoch  41 | Train F1=0.9189 | Val F1=0.8887

Epoch 42: 100%|██████████| 133/133 [00:01<00:00, 89.09it/s, loss=0.475]

Epoch  42 | Train F1=0.9229 | Val F1=0.8859

Epoch 43: 100%|██████████| 133/133 [00:01<00:00, 86.61it/s, loss=0.243]

Epoch  43 | Train F1=0.9173 | Val F1=0.8779

Epoch 44: 100%|██████████| 133/133 [00:01<00:00, 81.66it/s, loss=0.228]

Epoch  44 | Train F1=0.9158 | Val F1=0.8838

Epoch 45: 100%|██████████| 133/133 [00:01<00:00, 82.30it/s, loss=0.512]

Epoch  45 | Train F1=0.9170 | Val F1=0.8843

Epoch 46: 100%|██████████| 133/133 [00:01<00:00, 89.82it/s, loss=0.218]

Epoch  46 | Train F1=0.9170 | Val F1=0.8818

Epoch 47: 100%|██████████| 133/133 [00:01<00:00, 73.80it/s, loss=0.506]

Epoch  47 | Train F1=0.9227 | Val F1=0.8843

Epoch 48: 100%|██████████| 133/133 [00:01<00:00, 81.99it/s, loss=0.451]

Epoch  48 | Train F1=0.9249 | Val F1=0.8904

Epoch 49: 100%|██████████| 133/133 [00:01<00:00, 80.20it/s, loss=0.229]

Epoch  49 | Train F1=0.9234 | Val F1=0.8847

Epoch 50: 100%|██████████| 133/133 [00:01<00:00, 81.40it/s, loss=0.408]

Epoch  50 | Train F1=0.9241 | Val F1=0.8877

Epoch 1: 100%|██████████| 132/132 [00:01<00:00, 78.91it/s, loss=0.653]

Epoch   1 | Train F1=0.6164 | Val F1=0.6108

Epoch 2: 100%|██████████| 132/132 [00:01<00:00, 80.92it/s, loss=0.691]

Epoch   2 | Train F1=0.7295 | Val F1=0.7245

Epoch 3: 100%|██████████| 132/132 [00:01<00:00, 86.84it/s, loss=0.505]

Epoch   3 | Train F1=0.7802 | Val F1=0.7668

Epoch 4: 100%|██████████| 132/132 [00:01<00:00, 78.45it/s, loss=0.335]

Epoch   4 | Train F1=0.8260 | Val F1=0.8167

Epoch 5: 100%|██████████| 132/132 [00:01<00:00, 82.55it/s, loss=0.604]

Epoch   5 | Train F1=0.8444 | Val F1=0.8292

Epoch 6: 100%|██████████| 132/132 [00:01<00:00, 82.74it/s, loss=0.31]

Epoch   6 | Train F1=0.8701 | Val F1=0.8679

Epoch 7: 100%|██████████| 132/132 [00:01<00:00, 85.00it/s, loss=0.299]

Epoch   7 | Train F1=0.8762 | Val F1=0.8750

Epoch 8: 100%|██████████| 132/132 [00:01<00:00, 81.46it/s, loss=0.404]

Epoch   8 | Train F1=0.8834 | Val F1=0.8759

Epoch 9: 100%|██████████| 132/132 [00:01<00:00, 82.00it/s, loss=0.309]

Epoch   9 | Train F1=0.8980 | Val F1=0.8949

Epoch 10: 100%|██████████| 132/132 [00:01<00:00, 88.23it/s, loss=0.291]

Epoch  10 | Train F1=0.8890 | Val F1=0.8777

Epoch 11: 100%|██████████| 132/132 [00:01<00:00, 76.10it/s, loss=0.456]

Epoch  11 | Train F1=0.8935 | Val F1=0.8830

Epoch 12: 100%|██████████| 132/132 [00:01<00:00, 66.96it/s, loss=0.268]

Epoch  12 | Train F1=0.9024 | Val F1=0.8886

Epoch 13: 100%|██████████| 132/132 [00:01<00:00, 88.01it/s, loss=0.244]

Epoch  13 | Train F1=0.9063 | Val F1=0.8954

Epoch 14: 100%|██████████| 132/132 [00:01<00:00, 87.11it/s, loss=0.311]

Epoch  14 | Train F1=0.9116 | Val F1=0.8994

Epoch 15: 100%|██████████| 132/132 [00:01<00:00, 84.28it/s, loss=0.298]

Epoch  15 | Train F1=0.9067 | Val F1=0.8913

Epoch 16: 100%|██████████| 132/132 [00:01<00:00, 85.04it/s, loss=0.419]

Epoch  16 | Train F1=0.9073 | Val F1=0.8966

Epoch 17: 100%|██████████| 132/132 [00:01<00:00, 66.43it/s, loss=0.185]

Epoch  17 | Train F1=0.9131 | Val F1=0.9035

Epoch 18: 100%|██████████| 132/132 [00:01<00:00, 80.40it/s, loss=0.595]

Epoch  18 | Train F1=0.9107 | Val F1=0.8918

Epoch 19: 100%|██████████| 132/132 [00:01<00:00, 87.60it/s, loss=0.48]

Epoch  19 | Train F1=0.9116 | Val F1=0.8987

Epoch 20: 100%|██████████| 132/132 [00:01<00:00, 79.55it/s, loss=0.41]

Epoch  20 | Train F1=0.9184 | Val F1=0.9060

Epoch 21: 100%|██████████| 132/132 [00:01<00:00, 85.33it/s, loss=0.187]

Epoch  21 | Train F1=0.9235 | Val F1=0.9071

Epoch 22: 100%|██████████| 132/132 [00:01<00:00, 88.38it/s, loss=0.274]

Epoch  22 | Train F1=0.9210 | Val F1=0.9016

Epoch 23: 100%|██████████| 132/132 [00:01<00:00, 89.71it/s, loss=0.274]

Epoch  23 | Train F1=0.9220 | Val F1=0.9053

Epoch 24: 100%|██████████| 132/132 [00:01<00:00, 89.52it/s, loss=0.357]

Epoch  24 | Train F1=0.9258 | Val F1=0.9069

Epoch 25: 100%|██████████| 132/132 [00:01<00:00, 69.85it/s, loss=0.217]

Epoch  25 | Train F1=0.9239 | Val F1=0.9060

Epoch 26: 100%|██████████| 132/132 [00:01<00:00, 89.96it/s, loss=0.476]

Epoch  26 | Train F1=0.9234 | Val F1=0.9021

Epoch 27: 100%|██████████| 132/132 [00:01<00:00, 90.16it/s, loss=0.423]

Epoch  27 | Train F1=0.9303 | Val F1=0.9092

Epoch 28: 100%|██████████| 132/132 [00:01<00:00, 86.15it/s, loss=0.315]

Epoch  28 | Train F1=0.9255 | Val F1=0.9015

Epoch 29: 100%|██████████| 132/132 [00:01<00:00, 86.69it/s, loss=0.14]

Epoch  29 | Train F1=0.9267 | Val F1=0.9061

Epoch 30: 100%|██████████| 132/132 [00:01<00:00, 84.02it/s, loss=0.376]

Epoch  30 | Train F1=0.9272 | Val F1=0.9072

Epoch 31: 100%|██████████| 132/132 [00:01<00:00, 86.66it/s, loss=0.237]

Epoch  31 | Train F1=0.9306 | Val F1=0.9062

Epoch 32: 100%|██████████| 132/132 [00:01<00:00, 92.33it/s, loss=0.359]

Epoch  32 | Train F1=0.9248 | Val F1=0.9007

Epoch 33: 100%|██████████| 132/132 [00:01<00:00, 86.38it/s, loss=0.359]

Epoch  33 | Train F1=0.9275 | Val F1=0.9049

Epoch 34: 100%|██████████| 132/132 [00:01<00:00, 78.89it/s, loss=0.364]

Epoch  34 | Train F1=0.9232 | Val F1=0.8954

Epoch 35: 100%|██████████| 132/132 [00:01<00:00, 71.62it/s, loss=0.443]

Epoch  35 | Train F1=0.9276 | Val F1=0.9036

Epoch 36: 100%|██████████| 132/132 [00:01<00:00, 87.70it/s, loss=0.329]

Epoch  36 | Train F1=0.9331 | Val F1=0.9044

Epoch 37: 100%|██████████| 132/132 [00:01<00:00, 85.79it/s, loss=0.236]

Epoch  37 | Train F1=0.9297 | Val F1=0.9030

Epoch 38: 100%|██████████| 132/132 [00:01<00:00, 87.57it/s, loss=0.166]

Epoch  38 | Train F1=0.9312 | Val F1=0.9036

Epoch 39: 100%|██████████| 132/132 [00:01<00:00, 84.91it/s, loss=0.279]

Epoch  39 | Train F1=0.9317 | Val F1=0.9048

Epoch 40: 100%|██████████| 132/132 [00:01<00:00, 75.93it/s, loss=0.132]

Epoch  40 | Train F1=0.9332 | Val F1=0.9015

Epoch 41: 100%|██████████| 132/132 [00:02<00:00, 62.84it/s, loss=0.236]

Epoch  41 | Train F1=0.9363 | Val F1=0.9072

Epoch 42: 100%|██████████| 132/132 [00:01<00:00, 78.32it/s, loss=0.235]

Epoch  42 | Train F1=0.9337 | Val F1=0.9060

Epoch 43: 100%|██████████| 132/132 [00:01<00:00, 85.18it/s, loss=0.183]

Epoch  43 | Train F1=0.9400 | Val F1=0.9102

Epoch 44: 100%|██████████| 132/132 [00:01<00:00, 89.87it/s, loss=0.167]

Epoch  44 | Train F1=0.9355 | Val F1=0.9030

Epoch 45: 100%|██████████| 132/132 [00:01<00:00, 92.69it/s, loss=0.117]

Epoch  45 | Train F1=0.9380 | Val F1=0.9118

Epoch 46: 100%|██████████| 132/132 [00:01<00:00, 90.94it/s, loss=0.24]

Epoch  46 | Train F1=0.9431 | Val F1=0.9147

Epoch 47: 100%|██████████| 132/132 [00:01<00:00, 86.18it/s, loss=0.121]

Epoch  47 | Train F1=0.9376 | Val F1=0.9108

Epoch 48: 100%|██████████| 132/132 [00:02<00:00, 65.73it/s, loss=0.155]

Epoch  48 | Train F1=0.9366 | Val F1=0.9066

Epoch 49: 100%|██████████| 132/132 [00:01<00:00, 84.49it/s, loss=0.259]

Epoch  49 | Train F1=0.9413 | Val F1=0.9149

Epoch 50: 100%|██████████| 132/132 [00:01<00:00, 71.79it/s, loss=0.103]

Epoch  50 | Train F1=0.9403 | Val F1=0.9081

In [ ]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
for i in range(7):
    df.iloc[i,i+1] = '-'
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])

In [23]:
data = {
    'Treino': [86, 94, 89, 88, 93, 94, 92],
    'head': ['-', 28, 47, 16, 16, 39, 6],
    'chest': [60, '-', 58, 12, 22, 39, 29],
    'upperarm': [51, 32, '-', 11, 5, 45, 33],
    'forearm': [26, 25, 20, '-', 25, 5, 3],
    'waist': [14, 30, 18, 39, '-', 16, 9],
    'thigh': [37, 42, 44, 12, 15, '-', 30],
    'shin': [23, 24, 35, 9, 2, 40, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df0 = pd.DataFrame(data, index=index_labels)

print(df)
print(df0)

          Treino head chest upperarm forearm waist thigh shin
head          81    -    42       49      28    36    42   35
chest         90   33     -       47      33    36    47   42
upperarm      89   46    62        -      34    17    49   55
forearm       86   30    38       48       -    27    35   45
waist         91   38    22       14      30     -    33   20
thigh         90   47    40       48      33    38     -   44
shin          92   18    42       45      32    19    38    -
          Treino head chest upperarm forearm waist thigh shin
head          86    -    60       51      26    14    37   23
chest         94   28     -       32      25    30    42   24
upperarm      89   47    58        -      20    18    44   35
forearm       88   16    12       11       -    39    12    9
waist         93   16    22        5      25     -    15    2
thigh         94   39    39       45       5    16     -   40
shin          92    6    29       33       3     9    30    -

# Treinamento de adaptação

In [43]:
vals = [0.01, 0.1, 1, 2, 3, 4, 5, 6, 10, 20, 50, 100, 200, 250, 300, 400, 500, 1000]
epochs = 100
batch_size = 125

In [25]:
def mmd2u(x, y, c):
    n = x.shape[0]
    m = y.shape[0]
    xy = torch.vstack((x,y))
    dists = torch.cdist(xy, xy)
    k = torch.exp( (-1/(2*c)) * dists**2 )
    k_x = torch.triu(k[:n, :n], diagonal=1)
    k_y = torch.triu(k[n:, n:], diagonal=1)
    k_xy = k[:n, n:]
    mmd = 2*k_x.sum()/(n*(n-1)) + 2*k_y.sum()/(m*(m-1)) - 2*k_xy.sum()/(n*m)
    return mmd

In [37]:
def train_feature_matching(Xs_train, ys_train, Xt_train, Xs_val, ys_val, Xt_val, encoder, classifier):
    if encoder is None:
        encoder = ChangEncoder().to(device)
    if classifier is None:
        classifier = ChangClassifier().to(device)
    loss_fn = nn.CrossEntropyLoss()
    opt_cls = torch.optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=1e-3)
    opt_mmd = torch.optim.Adam(encoder.parameters(), lr=1e-3)
    history = {"train_loss": [], "train_f1": [], "val_loss": [], "val_f1": [],
               "val_mmd": []}
    Ns = len(Xs_train)
    Nt = len(Xt_train)
    for epoch in range(epochs):
        encoder.train()
        classifier.train()
        perm_s = torch.randperm(Ns, device=device)
        perm_t = torch.randperm(Nt, device=device)
        Xs = Xs_train[perm_s]
        ys = ys_train[perm_s]
        Xt = Xt_train[perm_t]
        n_batches = min(Ns, Nt) // batch_size
        pbar = tqdm(range(n_batches), desc=f"Epoch {epoch+1}/{epochs}", leave=False)
        for b in pbar:
            i0 = b * batch_size
            i1 = i0 + batch_size
            Xsb = Xs[i0:i1]
            ysb = ys[i0:i1]
            Xtb = Xt[i0:i1]
            # PASSO 1: classificação
            opt_cls.zero_grad()
            feat = encoder(Xsb)
            logits = classifier(feat)
            loss_cls = loss_fn(logits, ysb)
            loss_cls.backward()
            opt_cls.step()
            # PASSO 2: feature matching
            opt_mmd.zero_grad()
            feat_s = encoder(Xsb)
            feat_t = encoder(Xtb)
            loss_mmd = 0.0
            for sigma2 in vals:
                loss_mmd += mmd2u(feat_s, feat_t, sigma2)
            loss_mmd.backward()
            opt_mmd.step()
            pbar.set_postfix(cls=f"{loss_cls.item():.4f}", mmd=f"{loss_mmd.item():.4f}")
        encoder.eval()
        classifier.eval()
        with torch.no_grad():
            feat_s = encoder(Xs_train)
            logits = classifier(feat_s)
            train_loss = loss_fn(logits, ys_train)
            train_pred = logits.argmax(1)
            train_f1 = multiclass_f1_score(train_pred, ys_train, num_classes=8)
            feat_s = encoder(Xs_val)
            feat_t = encoder(Xt_val)
            logits = classifier(feat_s)
            val_loss = loss_fn(logits, ys_val)
            val_pred = logits.argmax(1)
            val_f1 = multiclass_f1_score(val_pred, ys_val, num_classes=8)
            val_mmd = 0.0
            for sigma2 in vals:
                val_mmd += mmd2u(feat_s, feat_t, sigma2)
        history["train_loss"].append(train_loss.item())
        history["train_f1"].append(train_f1.item())
        history["val_loss"].append(val_loss.item())
        history["val_f1"].append(val_f1.item())
        history["val_mmd"].append(val_mmd.item())
        print(
            f"Epoch {epoch+1:2d} | "
            f"train F1={train_f1:.4f} | "
            f"val F1={val_f1:.4f}"
        )
    return encoder, classifier, history

In [27]:
s = 0
t = 1
inds = ycort[:,0]==s
Xs = Xcort[inds]
ys = ycort[inds][:,1]
Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, ys, test_size=0.2, random_state=1, stratify=ys)
Xs_train = torch.tensor(Xs_train, dtype=torch.float32).to(device)
Xs_test  = torch.tensor(Xs_test, dtype=torch.float32).to(device)
ys_train = torch.tensor(ys_train, dtype=torch.long).to(device)
ys_test  = torch.tensor(ys_test, dtype=torch.long).to(device)
inds = ycort[:,0]==t
Xt = Xcort[inds]
yt = ycort[inds][:,1]
Xt_train, Xt_test, yt_train, yt_test = train_test_split(Xt, yt, test_size=0.2, random_state=1, stratify=yt)
Xt_train = torch.tensor(Xt_train, dtype=torch.float32).to(device)
Xt_test  = torch.tensor(Xt_test, dtype=torch.float32).to(device)
yt_train = torch.tensor(yt_train, dtype=torch.long).to(device)
yt_test  = torch.tensor(yt_test, dtype=torch.long).to(device)

In [ ]:
enc, cla, history = train_feature_matching(Xs_train, ys_train, Xt_train, Xs_test, ys_test, Xt_test, None, None)

In [ ]:
source_loader = DataLoader(TensorDataset(Xs_test, ys_test), batch_size=125)
target_loader = DataLoader(TensorDataset(Xt_test, yt_test), batch_size=125)
_, f1s = evaluate(enc, cla, source_loader, nn.CrossEntropyLoss(), device)
_, f1t = evaluate(enc, cla, target_loader, nn.CrossEntropyLoss(), device)
doms = posis[s]
domt = posis[t]
print('Antes da adaptação \tDepois da adaptação')
print('F1 '+doms+':', df['Treino'][doms]/100, '  \tF1 '+doms+':', np.array(f1s).round(2))
print('F1 '+domt+':', df[domt][doms]/100, '\tF1 '+domt+':', np.array(f1t).round(2))

Antes da adaptação 	Depois da adaptação
F1 chest: 0.9   	F1 chest: 0.89
F1 forearm: 0.38 	F1 chest: 0.52

In [44]:
pasta = '/content/drive/MyDrive/Doutorado Unicamp/Projeto/github/chang-UDA-HAR/modelos/'
enc2 = ChangEncoder().to(device)
enc2.load_state_dict(torch.load(pasta+'baseline_encoder_chest.pth'))
cla2 = ChangClassifier().to(device)
cla2.load_state_dict(torch.load(pasta+'baseline_classifier_chest.pth'))

In [45]:
enc2, cla2, history = train_feature_matching(Xs_train, ys_train, Xt_train, Xs_test, ys_test, Xt_test, enc2, cla2)

Epoch  1 | train F1=0.9594 | val F1=0.9280

Epoch  2 | train F1=0.9454 | val F1=0.9169

Epoch  3 | train F1=0.9537 | val F1=0.9207

Epoch  4 | train F1=0.9493 | val F1=0.9179

Epoch  5 | train F1=0.9491 | val F1=0.9186

Epoch  6 | train F1=0.9399 | val F1=0.9070

Epoch  7 | train F1=0.9523 | val F1=0.9248

Epoch  8 | train F1=0.9561 | val F1=0.9235

Epoch  9 | train F1=0.9509 | val F1=0.9148

Epoch 10 | train F1=0.9588 | val F1=0.9278

Epoch 11 | train F1=0.9534 | val F1=0.9218

Epoch 12 | train F1=0.9516 | val F1=0.9172

Epoch 13 | train F1=0.9571 | val F1=0.9239

Epoch 14 | train F1=0.9564 | val F1=0.9242

Epoch 15 | train F1=0.9484 | val F1=0.9143

Epoch 16 | train F1=0.9579 | val F1=0.9236

Epoch 17 | train F1=0.9558 | val F1=0.9274

Epoch 18 | train F1=0.9547 | val F1=0.9250

Epoch 19 | train F1=0.9531 | val F1=0.9199

Epoch 20 | train F1=0.9541 | val F1=0.9211

Epoch 21 | train F1=0.9572 | val F1=0.9215

Epoch 22 | train F1=0.9606 | val F1=0.9297

Epoch 23 | train F1=0.9455 | val F1=0.9129

Epoch 24 | train F1=0.9566 | val F1=0.9207

Epoch 25 | train F1=0.9521 | val F1=0.9157

Epoch 26 | train F1=0.9601 | val F1=0.9238

Epoch 27 | train F1=0.9592 | val F1=0.9249

Epoch 28 | train F1=0.9511 | val F1=0.9190

Epoch 29 | train F1=0.9612 | val F1=0.9289

Epoch 30 | train F1=0.9558 | val F1=0.9191

Epoch 31 | train F1=0.9559 | val F1=0.9209

Epoch 32 | train F1=0.9488 | val F1=0.9163

Epoch 33 | train F1=0.9556 | val F1=0.9219

Epoch 34 | train F1=0.9555 | val F1=0.9195

Epoch 35 | train F1=0.9546 | val F1=0.9177

Epoch 36 | train F1=0.9608 | val F1=0.9228

Epoch 37 | train F1=0.9531 | val F1=0.9181

Epoch 38 | train F1=0.9475 | val F1=0.9101

Epoch 39 | train F1=0.9565 | val F1=0.9159

Epoch 40 | train F1=0.9553 | val F1=0.9214

Epoch 41 | train F1=0.9619 | val F1=0.9185

Epoch 42 | train F1=0.9542 | val F1=0.9208

Epoch 43 | train F1=0.9606 | val F1=0.9240

Epoch 44 | train F1=0.9585 | val F1=0.9195

Epoch 45 | train F1=0.9552 | val F1=0.9157

Epoch 46 | train F1=0.9645 | val F1=0.9266

Epoch 47 | train F1=0.9618 | val F1=0.9238

Epoch 48 | train F1=0.9665 | val F1=0.9264

Epoch 49 | train F1=0.9584 | val F1=0.9207

Epoch 50 | train F1=0.9608 | val F1=0.9213

Epoch 51 | train F1=0.9568 | val F1=0.9189

Epoch 52 | train F1=0.9670 | val F1=0.9277

Epoch 53 | train F1=0.9622 | val F1=0.9238

Epoch 54 | train F1=0.9523 | val F1=0.9145

Epoch 55 | train F1=0.9627 | val F1=0.9255

Epoch 56 | train F1=0.9626 | val F1=0.9276

Epoch 57 | train F1=0.9613 | val F1=0.9231

Epoch 58 | train F1=0.9618 | val F1=0.9252

Epoch 59 | train F1=0.9624 | val F1=0.9290

Epoch 60 | train F1=0.9575 | val F1=0.9186

Epoch 61 | train F1=0.9635 | val F1=0.9272

Epoch 62 | train F1=0.9674 | val F1=0.9303

Epoch 63 | train F1=0.9615 | val F1=0.9272

Epoch 64 | train F1=0.9626 | val F1=0.9227

Epoch 65 | train F1=0.9622 | val F1=0.9220

Epoch 66 | train F1=0.9625 | val F1=0.9285

Epoch 67 | train F1=0.9584 | val F1=0.9184

Epoch 68 | train F1=0.9659 | val F1=0.9246

Epoch 69 | train F1=0.9631 | val F1=0.9249

Epoch 70 | train F1=0.9596 | val F1=0.9206

Epoch 71 | train F1=0.9605 | val F1=0.9192

Epoch 72 | train F1=0.9517 | val F1=0.9163

Epoch 73 | train F1=0.9643 | val F1=0.9239

Epoch 74 | train F1=0.9602 | val F1=0.9171

Epoch 75 | train F1=0.9638 | val F1=0.9262

Epoch 76 | train F1=0.9595 | val F1=0.9225

Epoch 77 | train F1=0.9619 | val F1=0.9199

Epoch 78 | train F1=0.9623 | val F1=0.9235

Epoch 79 | train F1=0.9623 | val F1=0.9206

Epoch 80 | train F1=0.9615 | val F1=0.9216

Epoch 81 | train F1=0.9621 | val F1=0.9202

Epoch 82 | train F1=0.9633 | val F1=0.9221

Epoch 83 | train F1=0.9605 | val F1=0.9204

Epoch 84 | train F1=0.9629 | val F1=0.9282

Epoch 85 | train F1=0.9634 | val F1=0.9229

Epoch 86 | train F1=0.9681 | val F1=0.9300

Epoch 87 | train F1=0.9592 | val F1=0.9220

Epoch 88 | train F1=0.9666 | val F1=0.9260

Epoch 89 | train F1=0.9644 | val F1=0.9214

Epoch 90 | train F1=0.9685 | val F1=0.9263

Epoch 91 | train F1=0.9676 | val F1=0.9280

Epoch 92 | train F1=0.9672 | val F1=0.9275

Epoch 93 | train F1=0.9672 | val F1=0.9275

Epoch 94 | train F1=0.9706 | val F1=0.9286

Epoch 95 | train F1=0.9616 | val F1=0.9194

Epoch 96 | train F1=0.9680 | val F1=0.9276

Epoch 97 | train F1=0.9600 | val F1=0.9230

Epoch 98 | train F1=0.9633 | val F1=0.9229

Epoch 99 | train F1=0.9638 | val F1=0.9270

Epoch 100 | train F1=0.9654 | val F1=0.9233

In [46]:
source_loader = DataLoader(TensorDataset(Xs_test, ys_test), batch_size=125)
target_loader = DataLoader(TensorDataset(Xt_test, yt_test), batch_size=125)
_, f1s = evaluate(enc2, cla2, source_loader, nn.CrossEntropyLoss(), device)
_, f1t = evaluate(enc2, cla2, target_loader, nn.CrossEntropyLoss(), device)
doms = posis[s]
domt = posis[t]
print('Antes da adaptação \tDepois da adaptação')
print('F1 '+doms+':', df['Treino'][doms]/100, '  \tF1 '+doms+':', np.array(f1s).round(2))
print('F1 '+domt+':', df[domt][doms]/100, '\tF1 '+domt+':', np.array(f1t).round(2))

Antes da adaptação 	Depois da adaptação
F1 chest: 0.9   	F1 chest: 0.92
F1 forearm: 0.33 	F1 forearm: 0.5

In [47]:
px.line(history)

In [49]:
enc2 = ChangEncoder().to(device)
enc2.load_state_dict(torch.load(pasta+'baseline_encoder_chest.pth'))
cla2 = ChangClassifier().to(device)
cla2.load_state_dict(torch.load(pasta+'baseline_classifier_chest.pth'))
t = 6
Xt = Xcort[inds]
yt = ycort[inds][:,1]
Xt_train, Xt_test, yt_train, yt_test = train_test_split(Xt, yt, test_size=0.2, random_state=1, stratify=yt)
Xt_train = torch.tensor(Xt_train, dtype=torch.float32).to(device)
Xt_test  = torch.tensor(Xt_test, dtype=torch.float32).to(device)
yt_train = torch.tensor(yt_train, dtype=torch.long).to(device)
yt_test  = torch.tensor(yt_test, dtype=torch.long).to(device)

In [50]:
enc2, cla2, history = train_feature_matching(Xs_train, ys_train, Xt_train, Xs_test, ys_test, Xt_test, enc2, cla2)

Epoch  1 | train F1=0.9439 | val F1=0.9051

Epoch  2 | train F1=0.9522 | val F1=0.9211

Epoch  3 | train F1=0.9581 | val F1=0.9264

Epoch  4 | train F1=0.9491 | val F1=0.9145

Epoch  5 | train F1=0.9551 | val F1=0.9238

Epoch  6 | train F1=0.9543 | val F1=0.9206

Epoch  7 | train F1=0.9585 | val F1=0.9268

Epoch  8 | train F1=0.9575 | val F1=0.9269

Epoch  9 | train F1=0.9521 | val F1=0.9201

Epoch 10 | train F1=0.9531 | val F1=0.9243

Epoch 11 | train F1=0.9557 | val F1=0.9272

Epoch 12 | train F1=0.9593 | val F1=0.9243

Epoch 13 | train F1=0.9555 | val F1=0.9225

Epoch 14 | train F1=0.9568 | val F1=0.9259

Epoch 15 | train F1=0.9526 | val F1=0.9204

Epoch 16 | train F1=0.9447 | val F1=0.9121

Epoch 17 | train F1=0.9521 | val F1=0.9159

Epoch 18 | train F1=0.9537 | val F1=0.9215

Epoch 19 | train F1=0.9539 | val F1=0.9218

Epoch 20 | train F1=0.9565 | val F1=0.9228

Epoch 21 | train F1=0.9551 | val F1=0.9249

Epoch 22 | train F1=0.9612 | val F1=0.9243

Epoch 23 | train F1=0.9506 | val F1=0.9139

Epoch 24 | train F1=0.9562 | val F1=0.9170

Epoch 25 | train F1=0.9610 | val F1=0.9263

Epoch 26 | train F1=0.9485 | val F1=0.9155

Epoch 27 | train F1=0.9562 | val F1=0.9207

Epoch 28 | train F1=0.9536 | val F1=0.9169

Epoch 29 | train F1=0.9606 | val F1=0.9263

Epoch 30 | train F1=0.9562 | val F1=0.9168

Epoch 31 | train F1=0.9632 | val F1=0.9275

Epoch 32 | train F1=0.9535 | val F1=0.9202

Epoch 33 | train F1=0.9566 | val F1=0.9203

Epoch 34 | train F1=0.9572 | val F1=0.9269

Epoch 35 | train F1=0.9644 | val F1=0.9249

Epoch 36 | train F1=0.9569 | val F1=0.9203

Epoch 37 | train F1=0.9597 | val F1=0.9214

Epoch 38 | train F1=0.9600 | val F1=0.9231

Epoch 39 | train F1=0.9618 | val F1=0.9279

Epoch 40 | train F1=0.9589 | val F1=0.9225

Epoch 41 | train F1=0.9553 | val F1=0.9144

Epoch 42 | train F1=0.9621 | val F1=0.9233

Epoch 43 | train F1=0.9569 | val F1=0.9156

Epoch 44 | train F1=0.9555 | val F1=0.9189

Epoch 45 | train F1=0.9606 | val F1=0.9231

Epoch 46 | train F1=0.9561 | val F1=0.9174

Epoch 47 | train F1=0.9586 | val F1=0.9233

Epoch 48 | train F1=0.9615 | val F1=0.9236

Epoch 49 | train F1=0.9611 | val F1=0.9225

Epoch 50 | train F1=0.9561 | val F1=0.9184

Epoch 51 | train F1=0.9632 | val F1=0.9238

Epoch 52 | train F1=0.9504 | val F1=0.9164

Epoch 53 | train F1=0.9634 | val F1=0.9229

Epoch 54 | train F1=0.9604 | val F1=0.9251

Epoch 55 | train F1=0.9643 | val F1=0.9270

Epoch 56 | train F1=0.9597 | val F1=0.9232

Epoch 57 | train F1=0.9611 | val F1=0.9206

Epoch 58 | train F1=0.9590 | val F1=0.9231

Epoch 59 | train F1=0.9600 | val F1=0.9208

Epoch 60 | train F1=0.9651 | val F1=0.9245

Epoch 61 | train F1=0.9594 | val F1=0.9218

Epoch 62 | train F1=0.9655 | val F1=0.9231

Epoch 63 | train F1=0.9580 | val F1=0.9239

Epoch 64 | train F1=0.9613 | val F1=0.9186

Epoch 65 | train F1=0.9663 | val F1=0.9261

Epoch 66 | train F1=0.9649 | val F1=0.9242

Epoch 67 | train F1=0.9575 | val F1=0.9207

Epoch 68 | train F1=0.9603 | val F1=0.9212

Epoch 69 | train F1=0.9658 | val F1=0.9296

Epoch 70 | train F1=0.9646 | val F1=0.9261

Epoch 71 | train F1=0.9646 | val F1=0.9230

Epoch 72 | train F1=0.9638 | val F1=0.9198

Epoch 73 | train F1=0.9598 | val F1=0.9213

Epoch 74 | train F1=0.9604 | val F1=0.9257

Epoch 75 | train F1=0.9529 | val F1=0.9161

Epoch 76 | train F1=0.9613 | val F1=0.9219

Epoch 77 | train F1=0.9656 | val F1=0.9274

Epoch 78 | train F1=0.9627 | val F1=0.9272

Epoch 79 | train F1=0.9700 | val F1=0.9267

Epoch 80 | train F1=0.9654 | val F1=0.9276

Epoch 81 | train F1=0.9662 | val F1=0.9250

Epoch 82 | train F1=0.9626 | val F1=0.9236

Epoch 83 | train F1=0.9672 | val F1=0.9260

Epoch 84 | train F1=0.9679 | val F1=0.9277

Epoch 85 | train F1=0.9654 | val F1=0.9263

Epoch 86 | train F1=0.9674 | val F1=0.9255

Epoch 87 | train F1=0.9670 | val F1=0.9236

Epoch 88 | train F1=0.9625 | val F1=0.9231

Epoch 89 | train F1=0.9691 | val F1=0.9285

Epoch 90 | train F1=0.9667 | val F1=0.9245

Epoch 91 | train F1=0.9623 | val F1=0.9226

Epoch 92 | train F1=0.9703 | val F1=0.9274

Epoch 93 | train F1=0.9619 | val F1=0.9259

Epoch 94 | train F1=0.9656 | val F1=0.9286

Epoch 95 | train F1=0.9637 | val F1=0.9278

Epoch 96 | train F1=0.9641 | val F1=0.9264

Epoch 97 | train F1=0.9645 | val F1=0.9196

Epoch 98 | train F1=0.9660 | val F1=0.9224

Epoch 99 | train F1=0.9645 | val F1=0.9265

Epoch 100 | train F1=0.9636 | val F1=0.9258

In [51]:
source_loader = DataLoader(TensorDataset(Xs_test, ys_test), batch_size=125)
target_loader = DataLoader(TensorDataset(Xt_test, yt_test), batch_size=125)
_, f1s = evaluate(enc2, cla2, source_loader, nn.CrossEntropyLoss(), device)
_, f1t = evaluate(enc2, cla2, target_loader, nn.CrossEntropyLoss(), device)
doms = posis[s]
domt = posis[t]
print('Antes da adaptação \tDepois da adaptação')
print('F1 '+doms+':', df['Treino'][doms]/100, '  \tF1 '+doms+':', np.array(f1s).round(2))
print('F1 '+domt+':', df[domt][doms]/100, '\tF1 '+domt+':', np.array(f1t).round(2))

Antes da adaptação 	Depois da adaptação
F1 chest: 0.9   	F1 chest: 0.93
F1 waist: 0.36 	F1 waist: 0.49

In [52]:
px.line(history)