# Inicialização

In [1]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor
import torch.optim as optim
from torchmetrics.functional.classification import multiclass_f1_score
from sklearn.metrics import f1_score, confusion_matrix

import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import copy
from copy import deepcopy
from tqdm import tqdm
import time
import os
from sklearn.cluster import KMeans
from scipy.spatial import distance
from scipy.signal import find_peaks, sosfiltfilt, butter
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device

In [3]:
actis = ['climbingdown', 'climbingup', 'jumping', 'lying', 'running', 'sitting', 'standing', 'walking']
posis = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
users = ['proband' + x for x in np.arange(1,16).astype(str)]

In [4]:
data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz')
Xdata = data['Xdata']
ydata = data['ydata']
pos = np.where(np.diff(ydata[:,0])==-6)[0]
pos = np.insert(pos, 0, 0)
pos = np.insert(pos, len(pos), len(ydata))
yu = np.zeros_like(ydata[:,0])
for i in range(len(pos)-1):
    yu[pos[i]:pos[i+1]] = i

# Pré-processamento dados RealWorld Chang

In [3]:
def recortar_janelas(acc, J, passo):
    N = acc.shape[0]
    Nj = (N - J) // passo + 1
    janelas = np.zeros((Nj, J, 3))
    for i in range(Nj):
        janelas[i] = acc[i * passo:i * passo + J]
    return janelas

In [4]:
actis = ['climbingdown', 'climbingup', 'jumping', 'lying', 'running', 'sitting', 'standing', 'walking']
posis = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
users = ['proband' + x for x in np.arange(1,16).astype(str)]

In [ ]:
pasta = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\Dataset\\realworldcsvs\\'
J = 150
Xdata = []
ydata = []
for user in tqdm(users):
    for i, pos in enumerate(posis):
        for j, act in enumerate(actis):
            files = os.listdir(pasta+user+'\\acc\\')
            inds = [(file.find(act)>-1) and (file.find(pos)>-1) for file in files]
            if np.array(inds).any():
                ind = inds.index(True)
                acc = pd.read_csv(pasta+user+'\\acc\\'+files[ind]).values[:,2:]
                janelas = recortar_janelas(acc, J, J)
                rotulos = np.full((janelas.shape[0], 2), [i, j], dtype=int)
                Xdata.append(janelas)
                ydata.append(rotulos)
Xdata = np.concatenate(Xdata, axis=0)
Xdata = Xdata/20
ydata = np.concatenate(ydata, axis=0)
Xdata.shape, ydata.shape

100%|██████████| 15/15 [00:45<00:00,  3.02s/it]

((151486, 150, 3), (151486, 2))

In [ ]:
# Vamos salvar os dados em um arquivo .npz para facilitar o carregamento posterior
np.savez('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz', Xdata=Xdata, ydata=ydata)

In [5]:
data = np.load('C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\github\\chang-UDA-HAR\\notebooks\\Xydata.npz')
Xdata = data['Xdata']
ydata = data['ydata']
pos = np.where(np.diff(ydata[:,0])==-6)[0]
pos = np.insert(pos, 0, 0)
pos = np.insert(pos, len(pos), len(ydata))
yu = np.zeros_like(ydata[:,0])
for i in range(len(pos)-1):
    yu[pos[i]:pos[i+1]] = i

In [10]:
px.histogram(np.array(actis)[ydata[:, 1].astype(int)])

In [11]:
px.histogram(np.array(posis)[ydata[:, 0].astype(int)])

# Modelo Chang

## Definição do modelo de Chang

In [5]:
class ChangEncoder(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv1d(in_channels=3, out_channels=16, kernel_size=3)
        self.inst1 = nn.InstanceNorm1d(16, affine=True)
        self.drop1 = nn.Dropout(p=0.2)

        self.conv2 = nn.Conv1d(in_channels=16, out_channels=16, kernel_size=3)
        self.inst2 = nn.InstanceNorm1d(16, affine=True)
        self.drop2 = nn.Dropout(p=0.2)

        self.conv3 = nn.Conv1d(in_channels=16, out_channels=32, kernel_size=5, stride=4)
        self.inst3 = nn.InstanceNorm1d(32, affine=True)
        self.drop3 = nn.Dropout(p=0.2)

        self.conv4 = nn.Conv1d(in_channels=32, out_channels=32, kernel_size=3, stride=1)
        self.inst4 = nn.InstanceNorm1d(32, affine=True)
        self.drop4 = nn.Dropout(p=0.2)

        self.conv5 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=5, stride=4)
        self.inst5 = nn.InstanceNorm1d(64, affine=True)
        self.drop5 = nn.Dropout(p=0.2)

        self.conv6 = nn.Conv1d(in_channels=64, out_channels=100, kernel_size=5, stride=1)

        self.relu = nn.LeakyReLU(0.3)
        self.glap = nn.AvgPool1d(kernel_size=4)

    def forward(self, x):
        # (N,T,C) -> (N,C,T)
        x = x.transpose(1, 2)
        x = self.conv1(x)
        x = self.relu(x)
        x = self.inst1(x)
        x = self.drop1(x)

        x = self.conv2(x)
        x = self.relu(x)
        x = self.inst2(x)
        x = self.drop2(x)

        x = self.conv3(x)
        x = self.relu(x)
        x = self.inst3(x)
        x = self.drop3(x)

        x = self.conv4(x)
        x = self.relu(x)
        x = self.inst4(x)
        x = self.drop4(x)
        
        x = self.conv5(x)
        x = self.relu(x)
        x = self.inst5(x)
        x = self.drop5(x)
        
        x = self.conv6(x)
        x = self.relu(x)

        x = self.glap(x)
        x = x.flatten(start_dim=1)

        logits = x
        return logits

In [6]:
class ChangClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.densa = nn.Linear(in_features=100, out_features=8)

    def forward(self, x):
        logits = self.densa(x)
        return logits

## Treinamento

### Versão 0 (código antigo)

In [446]:
for posi in range(7):
    print(D[posi].iloc[:,:450].max().max(), D[posi].iloc[:,:450].min().min())

30.24330038394172 -27.905772938181507
29.10584118741573 -23.004128879086824
24.60838945941594 -23.373795119211223
27.10391661258158 -35.01022254108014
28.35246581033783 -32.08145329447701
25.498862803206386 -28.645988494886826
24.63936106304582 -26.89441535730718

In [447]:
posi = 0
# Vamos descartar a classe jump por ter poucas amostras
# E mudar o código de walking para 2 (era 7)
# aux = D[posi][D[posi]['activity code']!=2].replace({'activity code': 7}, 2)
# tarefas = np.array(['climbingdown', 'climbingup', 'walking', 'lying', 'running', 'sitting', 'standing'])
N = aux.shape[0]
X = aux.iloc[:,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
y = aux.iloc[:,-3].values

In [448]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

y_train = nn.functional.one_hot(torch.tensor(y_train), num_classes=8).to(torch.float32).to(device)
y_val = nn.functional.one_hot(torch.tensor(y_val), num_classes=8).to(torch.float32).to(device)
y_test = nn.functional.one_hot(torch.tensor(y_test), num_classes=8).to(torch.float32).to(device)

X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
X_val = torch.tensor(X_val, dtype=torch.float32, device=device)
X_test = torch.tensor(X_test, dtype=torch.float32, device=device)

In [449]:
[y_train.shape, y_test.shape, y_val.shape]

[torch.Size([15881, 8]), torch.Size([4412, 8]), torch.Size([1765, 8])]

In [450]:
encoder = ChangEncoder().to(device)
classif = ChangClassifier().to(device)

# torch.manual_seed(42)

loss_fn = nn.CrossEntropyLoss()

optimizer = optim.Adam(list(encoder.parameters()) + list(classif.parameters()), lr=0.001)
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

n_epochs = 20   # number of epochs to run
batch_size = 125  # size of each batch
batch_start = torch.arange(0, len(X_train), batch_size)

trainLoss = []
trainAcc = []
valLoss = []
valAcc = []

# training loop
for epoch in range(n_epochs):
    encoder.train()
    classif.train()
    with tqdm(batch_start, unit="batch", mininterval=0, disable=False) as bar:
        bar.set_description(f"Epoch {epoch}")
        for start in bar:
            # take a batch
            X_batch = X_train[start:start+batch_size,:,:]
            y_batch = y_train[start:start+batch_size,:]
            # forward pass
            y_pred = classif(encoder(X_batch))
            loss = loss_fn(y_pred, y_batch)
            # backward pass
            optimizer.zero_grad()
            loss.backward()
            # update weights
            optimizer.step()
            # print progress
            bar.set_postfix(loss=float(loss))
    # evaluate accuracy at end of each epoch
    encoder.eval()
    classif.eval()
    y_pred = classif(encoder(X_val))
    valLoss.append(float(loss_fn(y_pred, y_val)))
    labels = torch.nonzero(y_val)[:,1]
    labels_pred = torch.argmax(y_pred, dim=1)
    valAcc.append(multiclass_f1_score(labels_pred, labels, num_classes=8))
    y_pred = classif(encoder(X_train))
    trainLoss.append(float(loss_fn(y_pred, y_train)))
    labels = torch.nonzero(y_train)[:,1]
    labels_pred = torch.argmax(y_pred, dim=1)
    valAcc.append(multiclass_f1_score(labels_pred, labels, num_classes=8))

fig = go.Figure()

fig.add_trace(go.Scatter(y=valLoss, mode="lines", showlegend=True, name='validação'))
fig.add_trace(go.Scatter(y=trainLoss, mode="lines", showlegend=True, name='treino'))

fig.show()

Epoch 0: 100%|██████████| 128/128 [00:11<00:00, 11.16batch/s, loss=0.833]
Epoch 1: 100%|██████████| 128/128 [00:11<00:00, 11.27batch/s, loss=0.359]
Epoch 2: 100%|██████████| 128/128 [00:11<00:00, 11.27batch/s, loss=0.436]
Epoch 3: 100%|██████████| 128/128 [00:11<00:00, 10.91batch/s, loss=0.318]
Epoch 4: 100%|██████████| 128/128 [00:11<00:00, 11.06batch/s, loss=0.357]
Epoch 5: 100%|██████████| 128/128 [00:11<00:00, 11.03batch/s, loss=0.297]
Epoch 6: 100%|██████████| 128/128 [00:11<00:00, 11.14batch/s, loss=0.272]
Epoch 7: 100%|██████████| 128/128 [00:11<00:00, 11.08batch/s, loss=0.277]
Epoch 8: 100%|██████████| 128/128 [00:11<00:00, 11.16batch/s, loss=0.352]
Epoch 9: 100%|██████████| 128/128 [00:11<00:00, 10.92batch/s, loss=0.196]
Epoch 10: 100%|██████████| 128/128 [00:11<00:00, 11.00batch/s, loss=0.286]
Epoch 11: 100%|██████████| 128/128 [00:11<00:00, 10.98batch/s, loss=0.16]
Epoch 12: 100%|██████████| 128/128 [00:11<00:00, 10.97batch/s, loss=0.246]
Epoch 13: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.173]
Epoch 14: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.191]
Epoch 15: 100%|██████████| 128/128 [00:11<00:00, 11.03batch/s, loss=0.202]
Epoch 16: 100%|██████████| 128/128 [00:11<00:00, 11.09batch/s, loss=0.166]
Epoch 17: 100%|██████████| 128/128 [00:11<00:00, 11.08batch/s, loss=0.131]
Epoch 18: 100%|██████████| 128/128 [00:11<00:00, 10.77batch/s, loss=0.0931]
Epoch 19: 100%|██████████| 128/128 [00:11<00:00, 11.01batch/s, loss=0.113]
Epoch 20: 100%|██████████| 128/128 [00:11<00:00, 11.10batch/s, loss=0.0912]
Epoch 21: 100%|██████████| 128/128 [00:11<00:00, 11.13batch/s, loss=0.215]
Epoch 22: 100%|██████████| 128/128 [00:11<00:00, 11.11batch/s, loss=0.235]
Epoch 23: 100%|██████████| 128/128 [00:11<00:00, 11.25batch/s, loss=0.157]
Epoch 24: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0734]
Epoch 25: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.0418]
Epoch 26: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.292]
Epoch 27: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.112]
Epoch 28: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0454]
Epoch 29: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0862]
Epoch 30: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.0931]
Epoch 31: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.0874]
Epoch 32: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0495]
Epoch 33: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.0673]
Epoch 34: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.152]
Epoch 35: 100%|██████████| 128/128 [00:11<00:00, 11.31batch/s, loss=0.0372]
Epoch 36: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.137]
Epoch 37: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.119]
Epoch 38: 100%|██████████| 128/128 [00:11<00:00, 11.26batch/s, loss=0.097]
Epoch 39: 100%|██████████| 128/128 [00:11<00:00, 11.29batch/s, loss=0.0446]
Epoch 40: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.124]
Epoch 41: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.0573]
Epoch 42: 100%|██████████| 128/128 [00:11<00:00, 11.25batch/s, loss=0.0563]
Epoch 43: 100%|██████████| 128/128 [00:11<00:00, 11.28batch/s, loss=0.0577]
Epoch 44: 100%|██████████| 128/128 [00:11<00:00, 11.30batch/s, loss=0.126]
Epoch 45: 100%|██████████| 128/128 [00:11<00:00, 11.23batch/s, loss=0.033]
Epoch 46: 100%|██████████| 128/128 [00:11<00:00, 10.95batch/s, loss=0.104]
Epoch 47: 100%|██████████| 128/128 [00:11<00:00, 11.15batch/s, loss=0.0786]
Epoch 48: 100%|██████████| 128/128 [00:12<00:00, 10.47batch/s, loss=0.0801]
Epoch 49: 100%|██████████| 128/128 [00:11<00:00, 11.04batch/s, loss=0.0689]

In [14]:
def treinoModelo(dados):
        N = dados.shape[0]
        X = dados.iloc[:,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
        y = dados.iloc[:,-3].values
        X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=1, stratify=y)

        X_train, X_val, y_train, y_val = train_test_split(
                X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

        y_train = nn.functional.one_hot(torch.tensor(y_train), num_classes=8).to(torch.float32).to(device)
        y_val = nn.functional.one_hot(torch.tensor(y_val), num_classes=8).to(torch.float32).to(device)
        y_test = nn.functional.one_hot(torch.tensor(y_test), num_classes=8).to(torch.float32).to(device)

        X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
        X_val = torch.tensor(X_val, dtype=torch.float32, device=device)
        X_test = torch.tensor(X_test, dtype=torch.float32, device=device)

        encoder = ChangEncoder().to(device)
        classif = ChangClassifier().to(device)
        loss_fn = nn.CrossEntropyLoss()
        optimizer = optim.Adam(list(encoder.parameters()) + list(classif.parameters()), lr=0.001)
        n_epochs = 20   # number of epochs to run
        batch_size = 125  # size of each batch
        batch_start = torch.arange(0, len(X_train), batch_size)
        trainLoss = []
        trainAcc = []
        valLoss = []
        valAcc = []

        # training loop
        for epoch in range(n_epochs):
                encoder.train()
                classif.train()
                with tqdm(batch_start, unit="batch", mininterval=0, disable=False) as bar:
                        bar.set_description(f"Epoch {epoch}")
                        for start in bar:
                                # take a batch
                                X_batch = X_train[start:start+batch_size,:,:]
                                y_batch = y_train[start:start+batch_size,:]
                                # forward pass
                                y_pred = classif(encoder(X_batch))
                                loss = loss_fn(y_pred, y_batch)
                                # backward pass
                                optimizer.zero_grad()
                                loss.backward()
                                # update weights
                                optimizer.step()
                                # print progress
                                bar.set_postfix(loss=float(loss))
                # evaluate accuracy at end of each epoch
                encoder.eval()
                classif.eval()
                y_pred = classif(encoder(X_val))
                valLoss.append(float(loss_fn(y_pred, y_val)))
                labels = torch.nonzero(y_val)[:,1]
                labels_pred = torch.argmax(y_pred, dim=1)
                valAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))
                y_pred = classif(encoder(X_train))
                trainLoss.append(float(loss_fn(y_pred, y_train)))
                labels = torch.nonzero(y_train)[:,1]
                labels_pred = torch.argmax(y_pred, dim=1)
                trainAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))

        fig = go.Figure()
        fig.add_trace(go.Scatter(y=valLoss, mode="lines", showlegend=True, name='validação'))
        fig.add_trace(go.Scatter(y=trainLoss, mode="lines", showlegend=True, name='treino'))
        fig.show()

        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(y=valAcc, mode="lines", showlegend=True, name='validação'))
        fig2.add_trace(go.Scatter(y=trainAcc, mode="lines", showlegend=True, name='treino'))
        fig2.show()
        return encoder, classif

In [15]:
encoders = [None] * 7
classifs = [None] * 7
for posi in range(7):
    encoders[posi], classifs[posi] = treinoModelo(D[posi])

Epoch 0: 100%|██████████| 130/130 [00:01<00:00, 82.67batch/s, loss=1.25]
Epoch 1: 100%|██████████| 130/130 [00:01<00:00, 91.41batch/s, loss=0.943]
Epoch 2: 100%|██████████| 130/130 [00:01<00:00, 80.21batch/s, loss=0.847]
Epoch 3: 100%|██████████| 130/130 [00:01<00:00, 68.67batch/s, loss=0.817]
Epoch 4: 100%|██████████| 130/130 [00:01<00:00, 70.06batch/s, loss=0.764]
Epoch 5: 100%|██████████| 130/130 [00:01<00:00, 78.05batch/s, loss=0.776]
Epoch 6: 100%|██████████| 130/130 [00:01<00:00, 74.06batch/s, loss=0.724]
Epoch 7: 100%|██████████| 130/130 [00:01<00:00, 72.94batch/s, loss=0.699]
Epoch 8: 100%|██████████| 130/130 [00:01<00:00, 70.46batch/s, loss=0.73]
Epoch 9: 100%|██████████| 130/130 [00:01<00:00, 72.91batch/s, loss=0.662]
Epoch 10: 100%|██████████| 130/130 [00:01<00:00, 66.86batch/s, loss=0.612]
Epoch 11: 100%|██████████| 130/130 [00:02<00:00, 63.04batch/s, loss=0.646]
Epoch 12: 100%|██████████| 130/130 [00:01<00:00, 69.72batch/s, loss=0.682]
Epoch 13: 100%|██████████| 130/130 [00:02<00:00, 61.91batch/s, loss=0.641]
Epoch 14: 100%|██████████| 130/130 [00:02<00:00, 59.58batch/s, loss=0.666]
Epoch 15: 100%|██████████| 130/130 [00:02<00:00, 53.89batch/s, loss=0.701]
Epoch 16: 100%|██████████| 130/130 [00:02<00:00, 52.08batch/s, loss=0.609]
Epoch 17: 100%|██████████| 130/130 [00:02<00:00, 55.42batch/s, loss=0.597]
Epoch 18: 100%|██████████| 130/130 [00:02<00:00, 53.89batch/s, loss=0.612]
Epoch 19: 100%|██████████| 130/130 [00:02<00:00, 44.48batch/s, loss=0.622]

Epoch 0: 100%|██████████| 128/128 [00:02<00:00, 54.22batch/s, loss=1.42]
Epoch 1: 100%|██████████| 128/128 [00:01<00:00, 86.40batch/s, loss=1.24]
Epoch 2: 100%|██████████| 128/128 [00:01<00:00, 90.22batch/s, loss=1.13]
Epoch 3: 100%|██████████| 128/128 [00:01<00:00, 91.05batch/s, loss=1.11]
Epoch 4: 100%|██████████| 128/128 [00:01<00:00, 88.36batch/s, loss=1.11]
Epoch 5: 100%|██████████| 128/128 [00:01<00:00, 74.27batch/s, loss=1.06]
Epoch 6: 100%|██████████| 128/128 [00:09<00:00, 14.03batch/s, loss=0.981]
Epoch 7: 100%|██████████| 128/128 [00:13<00:00,  9.80batch/s, loss=1.06]
Epoch 8: 100%|██████████| 128/128 [00:08<00:00, 15.82batch/s, loss=1.04]
Epoch 9: 100%|██████████| 128/128 [00:07<00:00, 16.06batch/s, loss=1.04]
Epoch 10: 100%|██████████| 128/128 [00:07<00:00, 16.22batch/s, loss=0.867]
Epoch 11: 100%|██████████| 128/128 [00:08<00:00, 15.60batch/s, loss=1]
Epoch 12: 100%|██████████| 128/128 [00:07<00:00, 16.30batch/s, loss=0.872]
Epoch 13: 100%|██████████| 128/128 [00:07<00:00, 16.25batch/s, loss=0.882]
Epoch 14: 100%|██████████| 128/128 [00:07<00:00, 16.28batch/s, loss=0.99]
Epoch 15: 100%|██████████| 128/128 [00:07<00:00, 16.04batch/s, loss=0.896]
Epoch 16: 100%|██████████| 128/128 [00:07<00:00, 16.39batch/s, loss=0.895]
Epoch 17: 100%|██████████| 128/128 [00:07<00:00, 16.35batch/s, loss=0.805]
Epoch 18: 100%|██████████| 128/128 [00:07<00:00, 16.42batch/s, loss=0.799]
Epoch 19: 100%|██████████| 128/128 [00:07<00:00, 16.47batch/s, loss=0.769]

Epoch 0: 100%|██████████| 130/130 [00:08<00:00, 16.22batch/s, loss=1.53]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.29batch/s, loss=1.4]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.38batch/s, loss=1.23]
Epoch 3: 100%|██████████| 130/130 [00:08<00:00, 16.19batch/s, loss=1.17]
Epoch 4: 100%|██████████| 130/130 [00:08<00:00, 15.99batch/s, loss=1.09]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.39batch/s, loss=1.06]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.52batch/s, loss=0.992]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.54batch/s, loss=1.02]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.29batch/s, loss=0.978]
Epoch 9: 100%|██████████| 130/130 [00:08<00:00, 16.14batch/s, loss=0.928]
Epoch 10: 100%|██████████| 130/130 [00:08<00:00, 16.00batch/s, loss=0.929]
Epoch 11: 100%|██████████| 130/130 [00:08<00:00, 16.16batch/s, loss=0.934]
Epoch 12: 100%|██████████| 130/130 [00:08<00:00, 16.00batch/s, loss=0.886]
Epoch 13: 100%|██████████| 130/130 [00:08<00:00, 16.15batch/s, loss=0.906]
Epoch 14: 100%|██████████| 130/130 [00:08<00:00, 15.72batch/s, loss=0.889]
Epoch 15: 100%|██████████| 130/130 [00:10<00:00, 12.89batch/s, loss=0.846]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.57batch/s, loss=0.832]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.817]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.794]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.774]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.54batch/s, loss=1.31]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.948]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.777]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.704]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.669]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.613]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.628]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.607]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.588]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.57batch/s, loss=0.501]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.521]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.538]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.534]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.525]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.495]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.47batch/s, loss=0.514]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.49batch/s, loss=0.496]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.471]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.506]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.488]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=1.52]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.47batch/s, loss=1.14]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.50batch/s, loss=1.09]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=1.04]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.933]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.924]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.87]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.65batch/s, loss=0.865]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.83]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.854]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.796]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.782]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.52batch/s, loss=0.811]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.819]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.787]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.739]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.751]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.687]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.56batch/s, loss=0.73]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.64batch/s, loss=0.686]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=1.24]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=1.06]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.851]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.793]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.77]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.693]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.644]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.67]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.555]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.614]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.576]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.63batch/s, loss=0.544]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.58batch/s, loss=0.594]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.558]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.52]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.501]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.497]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.485]
Epoch 18: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.47]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.5]

Epoch 0: 100%|██████████| 130/130 [00:07<00:00, 16.32batch/s, loss=0.916]
Epoch 1: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.732]
Epoch 2: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.679]
Epoch 3: 100%|██████████| 130/130 [00:07<00:00, 16.61batch/s, loss=0.619]
Epoch 4: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.545]
Epoch 5: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.504]
Epoch 6: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.539]
Epoch 7: 100%|██████████| 130/130 [00:07<00:00, 16.60batch/s, loss=0.466]
Epoch 8: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.465]
Epoch 9: 100%|██████████| 130/130 [00:07<00:00, 16.62batch/s, loss=0.404]
Epoch 10: 100%|██████████| 130/130 [00:07<00:00, 16.53batch/s, loss=0.387]
Epoch 11: 100%|██████████| 130/130 [00:07<00:00, 16.44batch/s, loss=0.401]
Epoch 12: 100%|██████████| 130/130 [00:07<00:00, 16.55batch/s, loss=0.438]
Epoch 13: 100%|██████████| 130/130 [00:07<00:00, 16.46batch/s, loss=0.402]
Epoch 14: 100%|██████████| 130/130 [00:07<00:00, 16.30batch/s, loss=0.437]
Epoch 15: 100%|██████████| 130/130 [00:07<00:00, 16.48batch/s, loss=0.355]
Epoch 16: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.383]
Epoch 17: 100%|██████████| 130/130 [00:07<00:00, 16.59batch/s, loss=0.412]
Epoch 18: 100%|██████████| 130/130 [00:08<00:00, 16.06batch/s, loss=0.384]
Epoch 19: 100%|██████████| 130/130 [00:07<00:00, 16.34batch/s, loss=0.397]

### Versão 1

In [56]:
inds = ydata[:,0]==0
X = Xdata[inds]
y = ydata[inds][:,1]
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)

X_train = torch.tensor(X_train, dtype=torch.float32)
X_val   = torch.tensor(X_val, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.long)
y_val   = torch.tensor(y_val, dtype=torch.long)
y_test  = torch.tensor(y_test, dtype=torch.long)

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=125, shuffle=True, pin_memory=True)
val_loader = DataLoader(TensorDataset(X_val, y_val), batch_size=256, shuffle=False, pin_memory=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=256, shuffle=False, pin_memory=True)

In [62]:
@torch.no_grad()
def evaluate(encoder, classifier, loader, loss_fn, device):
    encoder.eval()
    classifier.eval()
    total_loss = 0
    total_samples = 0
    y_true = []
    y_pred = []

    for X, y in loader:
        X = X.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        logits = classifier(encoder(X))
        loss = loss_fn(logits, y)
        total_loss += loss.item() * len(y)
        total_samples += len(y)
        pred = torch.argmax(logits, dim=1)
        y_true.append(y)
        y_pred.append(pred)

    y_true = torch.cat(y_true)
    y_pred = torch.cat(y_pred)
    f1 = multiclass_f1_score(y_pred, y_true, num_classes=8, average="macro").item()

    return total_loss / total_samples, f1

In [63]:
def train_model(train_loader, val_loader, device):
    encoder = ChangEncoder().to(device)
    classifier = ChangClassifier().to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=1e-3)
    n_epochs = 100
    history = {
        "train_loss": [],
        "val_loss": [],
        "train_f1": [],
        "val_f1": []
    }
    best_f1 = -1
    best_encoder = None
    best_classifier = None

    for epoch in range(n_epochs):
        encoder.train()
        classifier.train()
        running_loss = 0
        n_samples = 0
        bar = tqdm(train_loader)

        for X, y in bar:
            X = X.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            optimizer.zero_grad()
            logits = classifier(encoder(X))
            loss = loss_fn(logits, y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * len(y)
            n_samples += len(y)
            bar.set_description(f"Epoch {epoch+1}")
            bar.set_postfix(loss=loss.item())

        train_loss, train_f1 = evaluate(
            encoder,
            classifier,
            train_loader,
            loss_fn,
            device
        )

        val_loss, val_f1 = evaluate(
            encoder,
            classifier,
            val_loader,
            loss_fn,
            device
        )

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_f1"].append(train_f1)
        history["val_f1"].append(val_f1)

        print(
            f"Epoch {epoch+1:3d} | "
            f"Train F1={train_f1:.4f} | "
            f"Val F1={val_f1:.4f}"
        )

        if val_f1 > best_f1:
            best_f1 = val_f1
            best_encoder = deepcopy(encoder)
            best_classifier = deepcopy(classifier)

    return best_encoder, best_classifier, history

In [65]:
enc, cla, history = train_model(train_loader, val_loader, device)

Epoch 1: 100%|██████████| 125/125 [00:01<00:00, 81.84it/s, loss=1.12]

Epoch   1 | Train F1=0.4455 | Val F1=0.4241

Epoch 2: 100%|██████████| 125/125 [00:01<00:00, 81.44it/s, loss=0.916]

Epoch   2 | Train F1=0.5688 | Val F1=0.5400

Epoch 3: 100%|██████████| 125/125 [00:01<00:00, 71.19it/s, loss=0.845]

Epoch   3 | Train F1=0.6446 | Val F1=0.6322

Epoch 4: 100%|██████████| 125/125 [00:01<00:00, 63.27it/s, loss=0.637]

Epoch   4 | Train F1=0.7040 | Val F1=0.6920

Epoch 5: 100%|██████████| 125/125 [00:02<00:00, 48.85it/s, loss=0.654]

Epoch   5 | Train F1=0.6917 | Val F1=0.6863

Epoch 6: 100%|██████████| 125/125 [00:01<00:00, 78.80it/s, loss=0.533]

Epoch   6 | Train F1=0.7293 | Val F1=0.7185

Epoch 7: 100%|██████████| 125/125 [00:01<00:00, 82.22it/s, loss=0.782]

Epoch   7 | Train F1=0.7627 | Val F1=0.7615

Epoch 8: 100%|██████████| 125/125 [00:01<00:00, 89.27it/s, loss=0.554]

Epoch   8 | Train F1=0.7821 | Val F1=0.7742

Epoch 9: 100%|██████████| 125/125 [00:01<00:00, 85.96it/s, loss=0.551]

Epoch   9 | Train F1=0.8021 | Val F1=0.7996

Epoch 10: 100%|██████████| 125/125 [00:02<00:00, 51.37it/s, loss=0.48]

Epoch  10 | Train F1=0.7973 | Val F1=0.7789

Epoch 11: 100%|██████████| 125/125 [00:01<00:00, 64.60it/s, loss=0.5]

Epoch  11 | Train F1=0.8206 | Val F1=0.8030

Epoch 12: 100%|██████████| 125/125 [00:01<00:00, 67.59it/s, loss=0.544]

Epoch  12 | Train F1=0.8260 | Val F1=0.7918

Epoch 13: 100%|██████████| 125/125 [00:04<00:00, 29.26it/s, loss=0.476]

Epoch  13 | Train F1=0.8363 | Val F1=0.8192

Epoch 14: 100%|██████████| 125/125 [00:03<00:00, 32.61it/s, loss=0.438]

Epoch  14 | Train F1=0.8445 | Val F1=0.8113

Epoch 15: 100%|██████████| 125/125 [00:03<00:00, 39.99it/s, loss=0.45]

Epoch  15 | Train F1=0.8418 | Val F1=0.8078

Epoch 16: 100%|██████████| 125/125 [00:02<00:00, 44.52it/s, loss=0.47]

Epoch  16 | Train F1=0.8562 | Val F1=0.8340

Epoch 17: 100%|██████████| 125/125 [00:02<00:00, 46.48it/s, loss=0.411]

Epoch  17 | Train F1=0.8593 | Val F1=0.8358

Epoch 18: 100%|██████████| 125/125 [00:02<00:00, 57.96it/s, loss=0.44]

Epoch  18 | Train F1=0.8566 | Val F1=0.8250

Epoch 19: 100%|██████████| 125/125 [00:02<00:00, 56.14it/s, loss=0.54]

Epoch  19 | Train F1=0.8680 | Val F1=0.8459

Epoch 20: 100%|██████████| 125/125 [00:01<00:00, 69.44it/s, loss=0.534]

Epoch  20 | Train F1=0.8762 | Val F1=0.8568

Epoch 21: 100%|██████████| 125/125 [00:01<00:00, 63.37it/s, loss=0.494]

Epoch  21 | Train F1=0.8797 | Val F1=0.8505

Epoch 22: 100%|██████████| 125/125 [00:02<00:00, 58.31it/s, loss=0.447]

Epoch  22 | Train F1=0.8805 | Val F1=0.8597

Epoch 23: 100%|██████████| 125/125 [00:01<00:00, 77.87it/s, loss=0.475]

Epoch  23 | Train F1=0.8816 | Val F1=0.8603

Epoch 24: 100%|██████████| 125/125 [00:01<00:00, 82.18it/s, loss=0.36]

Epoch  24 | Train F1=0.8862 | Val F1=0.8600

Epoch 25: 100%|██████████| 125/125 [00:06<00:00, 18.81it/s, loss=0.37]

Epoch  25 | Train F1=0.8984 | Val F1=0.8702

Epoch 26: 100%|██████████| 125/125 [00:08<00:00, 15.37it/s, loss=0.453]

Epoch  26 | Train F1=0.8953 | Val F1=0.8590

Epoch 27: 100%|██████████| 125/125 [00:07<00:00, 16.36it/s, loss=0.359]

Epoch  27 | Train F1=0.8956 | Val F1=0.8702

Epoch 28: 100%|██████████| 125/125 [00:07<00:00, 16.47it/s, loss=0.4]

Epoch  28 | Train F1=0.8978 | Val F1=0.8646

Epoch 29: 100%|██████████| 125/125 [00:07<00:00, 16.59it/s, loss=0.346]

Epoch  29 | Train F1=0.8981 | Val F1=0.8715

Epoch 30: 100%|██████████| 125/125 [00:07<00:00, 16.55it/s, loss=0.462]

Epoch  30 | Train F1=0.9022 | Val F1=0.8710

Epoch 31: 100%|██████████| 125/125 [00:07<00:00, 16.48it/s, loss=0.447]

Epoch  31 | Train F1=0.9084 | Val F1=0.8736

Epoch 32: 100%|██████████| 125/125 [00:07<00:00, 16.57it/s, loss=0.487]

Epoch  32 | Train F1=0.9035 | Val F1=0.8720

Epoch 33: 100%|██████████| 125/125 [00:07<00:00, 16.52it/s, loss=0.379]

Epoch  33 | Train F1=0.9111 | Val F1=0.8777

Epoch 34: 100%|██████████| 125/125 [00:07<00:00, 16.58it/s, loss=0.396]

Epoch  34 | Train F1=0.9140 | Val F1=0.8901

Epoch 35: 100%|██████████| 125/125 [00:07<00:00, 16.60it/s, loss=0.368]

Epoch  35 | Train F1=0.9090 | Val F1=0.8755

Epoch 36: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.425]

Epoch  36 | Train F1=0.9142 | Val F1=0.8836

Epoch 37: 100%|██████████| 125/125 [00:08<00:00, 15.20it/s, loss=0.332]

Epoch  37 | Train F1=0.9105 | Val F1=0.8771

Epoch 38: 100%|██████████| 125/125 [00:08<00:00, 15.05it/s, loss=0.342]

Epoch  38 | Train F1=0.9181 | Val F1=0.8815

Epoch 39: 100%|██████████| 125/125 [00:08<00:00, 15.03it/s, loss=0.377]

Epoch  39 | Train F1=0.9184 | Val F1=0.8854

Epoch 40: 100%|██████████| 125/125 [00:08<00:00, 14.86it/s, loss=0.297]

Epoch  40 | Train F1=0.9205 | Val F1=0.8838

Epoch 41: 100%|██████████| 125/125 [00:08<00:00, 15.07it/s, loss=0.412]

Epoch  41 | Train F1=0.9193 | Val F1=0.8814

Epoch 42: 100%|██████████| 125/125 [00:08<00:00, 14.92it/s, loss=0.368]

Epoch  42 | Train F1=0.9096 | Val F1=0.8723

Epoch 43: 100%|██████████| 125/125 [00:08<00:00, 15.22it/s, loss=0.373]

Epoch  43 | Train F1=0.9202 | Val F1=0.8775

Epoch 44: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.273]

Epoch  44 | Train F1=0.9199 | Val F1=0.8789

Epoch 45: 100%|██████████| 125/125 [00:08<00:00, 15.53it/s, loss=0.388]

Epoch  45 | Train F1=0.9203 | Val F1=0.8806

Epoch 46: 100%|██████████| 125/125 [00:08<00:00, 15.13it/s, loss=0.31]

Epoch  46 | Train F1=0.9199 | Val F1=0.8813

Epoch 47: 100%|██████████| 125/125 [00:08<00:00, 14.74it/s, loss=0.377]

Epoch  47 | Train F1=0.9226 | Val F1=0.8778

Epoch 48: 100%|██████████| 125/125 [00:08<00:00, 14.98it/s, loss=0.319]

Epoch  48 | Train F1=0.9208 | Val F1=0.8845

Epoch 49: 100%|██████████| 125/125 [00:08<00:00, 14.92it/s, loss=0.321]

Epoch  49 | Train F1=0.9303 | Val F1=0.8911

Epoch 50: 100%|██████████| 125/125 [00:08<00:00, 14.76it/s, loss=0.367]

Epoch  50 | Train F1=0.9275 | Val F1=0.8865

Epoch 51: 100%|██████████| 125/125 [00:08<00:00, 14.84it/s, loss=0.303]

Epoch  51 | Train F1=0.9273 | Val F1=0.8821

Epoch 52: 100%|██████████| 125/125 [00:08<00:00, 14.99it/s, loss=0.387]

Epoch  52 | Train F1=0.9287 | Val F1=0.8847

Epoch 53: 100%|██████████| 125/125 [00:08<00:00, 14.98it/s, loss=0.299]

Epoch  53 | Train F1=0.9236 | Val F1=0.8799

Epoch 54: 100%|██████████| 125/125 [00:07<00:00, 16.63it/s, loss=0.346]

Epoch  54 | Train F1=0.9282 | Val F1=0.8903

Epoch 55: 100%|██████████| 125/125 [00:07<00:00, 16.33it/s, loss=0.348]

Epoch  55 | Train F1=0.9304 | Val F1=0.8918

Epoch 56: 100%|██████████| 125/125 [00:07<00:00, 15.98it/s, loss=0.24]

Epoch  56 | Train F1=0.9333 | Val F1=0.8977

Epoch 57: 100%|██████████| 125/125 [00:07<00:00, 15.99it/s, loss=0.308]

Epoch  57 | Train F1=0.9284 | Val F1=0.8896

Epoch 58: 100%|██████████| 125/125 [00:07<00:00, 16.42it/s, loss=0.299]

Epoch  58 | Train F1=0.9337 | Val F1=0.8923

Epoch 59: 100%|██████████| 125/125 [00:07<00:00, 16.10it/s, loss=0.407]

Epoch  59 | Train F1=0.9317 | Val F1=0.8938

Epoch 60: 100%|██████████| 125/125 [00:08<00:00, 14.57it/s, loss=0.443]

Epoch  60 | Train F1=0.9217 | Val F1=0.8769

Epoch 61: 100%|██████████| 125/125 [00:08<00:00, 14.89it/s, loss=0.331]

Epoch  61 | Train F1=0.9345 | Val F1=0.9007

Epoch 62: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.32]

Epoch  62 | Train F1=0.9316 | Val F1=0.8902

Epoch 63: 100%|██████████| 125/125 [00:08<00:00, 15.04it/s, loss=0.405]

Epoch  63 | Train F1=0.9303 | Val F1=0.8873

Epoch 64: 100%|██████████| 125/125 [00:08<00:00, 14.34it/s, loss=0.318]

Epoch  64 | Train F1=0.9355 | Val F1=0.8905

Epoch 65: 100%|██████████| 125/125 [00:08<00:00, 14.99it/s, loss=0.358]

Epoch  65 | Train F1=0.9377 | Val F1=0.8948

Epoch 66: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.312]

Epoch  66 | Train F1=0.9369 | Val F1=0.8936

Epoch 67: 100%|██████████| 125/125 [00:08<00:00, 14.71it/s, loss=0.331]

Epoch  67 | Train F1=0.9332 | Val F1=0.8917

Epoch 68: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.355]

Epoch  68 | Train F1=0.9422 | Val F1=0.8978

Epoch 69: 100%|██████████| 125/125 [00:08<00:00, 14.81it/s, loss=0.327]

Epoch  69 | Train F1=0.9442 | Val F1=0.8986

Epoch 70: 100%|██████████| 125/125 [00:08<00:00, 15.14it/s, loss=0.284]

Epoch  70 | Train F1=0.9408 | Val F1=0.8974

Epoch 71: 100%|██████████| 125/125 [00:07<00:00, 16.18it/s, loss=0.212]

Epoch  71 | Train F1=0.9383 | Val F1=0.8834

Epoch 72: 100%|██████████| 125/125 [00:07<00:00, 15.94it/s, loss=0.231]

Epoch  72 | Train F1=0.9437 | Val F1=0.9013

Epoch 73: 100%|██████████| 125/125 [00:07<00:00, 15.77it/s, loss=0.353]

Epoch  73 | Train F1=0.9413 | Val F1=0.8868

Epoch 74: 100%|██████████| 125/125 [00:07<00:00, 16.32it/s, loss=0.225]

Epoch  74 | Train F1=0.9371 | Val F1=0.8880

Epoch 75: 100%|██████████| 125/125 [00:07<00:00, 16.39it/s, loss=0.293]

Epoch  75 | Train F1=0.9354 | Val F1=0.8879

Epoch 76: 100%|██████████| 125/125 [00:08<00:00, 14.64it/s, loss=0.398]

Epoch  76 | Train F1=0.9348 | Val F1=0.8848

Epoch 77: 100%|██████████| 125/125 [00:08<00:00, 14.77it/s, loss=0.362]

Epoch  77 | Train F1=0.9334 | Val F1=0.8881

Epoch 78: 100%|██████████| 125/125 [00:08<00:00, 14.88it/s, loss=0.332]

Epoch  78 | Train F1=0.9411 | Val F1=0.8960

Epoch 79: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.301]

Epoch  79 | Train F1=0.9416 | Val F1=0.8920

Epoch 80: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.256]

Epoch  80 | Train F1=0.9431 | Val F1=0.8966

Epoch 81: 100%|██████████| 125/125 [00:08<00:00, 14.85it/s, loss=0.284]

Epoch  81 | Train F1=0.9449 | Val F1=0.8935

Epoch 82: 100%|██████████| 125/125 [00:08<00:00, 14.68it/s, loss=0.292]

Epoch  82 | Train F1=0.9444 | Val F1=0.9010

Epoch 83: 100%|██████████| 125/125 [00:08<00:00, 14.93it/s, loss=0.37]

Epoch  83 | Train F1=0.9468 | Val F1=0.8922

Epoch 84: 100%|██████████| 125/125 [00:08<00:00, 14.88it/s, loss=0.367]

Epoch  84 | Train F1=0.9431 | Val F1=0.8890

Epoch 85: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.381]

Epoch  85 | Train F1=0.9408 | Val F1=0.8929

Epoch 86: 100%|██████████| 125/125 [00:08<00:00, 15.02it/s, loss=0.245]

Epoch  86 | Train F1=0.9430 | Val F1=0.8938

Epoch 87: 100%|██████████| 125/125 [00:08<00:00, 14.54it/s, loss=0.357]

Epoch  87 | Train F1=0.9454 | Val F1=0.8917

Epoch 88: 100%|██████████| 125/125 [00:08<00:00, 14.78it/s, loss=0.24]

Epoch  88 | Train F1=0.9387 | Val F1=0.8849

Epoch 89: 100%|██████████| 125/125 [00:08<00:00, 14.90it/s, loss=0.202]

Epoch  89 | Train F1=0.9482 | Val F1=0.9007

Epoch 90: 100%|██████████| 125/125 [00:08<00:00, 14.94it/s, loss=0.321]

Epoch  90 | Train F1=0.9481 | Val F1=0.8975

Epoch 91: 100%|██████████| 125/125 [00:08<00:00, 14.87it/s, loss=0.308]

Epoch  91 | Train F1=0.9495 | Val F1=0.9002

Epoch 92: 100%|██████████| 125/125 [00:08<00:00, 14.91it/s, loss=0.372]

Epoch  92 | Train F1=0.9428 | Val F1=0.8892

Epoch 93: 100%|██████████| 125/125 [00:08<00:00, 14.93it/s, loss=0.276]

Epoch  93 | Train F1=0.9481 | Val F1=0.8970

Epoch 94: 100%|██████████| 125/125 [00:08<00:00, 14.94it/s, loss=0.365]

Epoch  94 | Train F1=0.9416 | Val F1=0.8969

Epoch 95: 100%|██████████| 125/125 [00:08<00:00, 14.75it/s, loss=0.191]

Epoch  95 | Train F1=0.9461 | Val F1=0.8980

Epoch 96: 100%|██████████| 125/125 [00:07<00:00, 16.53it/s, loss=0.24]

Epoch  96 | Train F1=0.9498 | Val F1=0.8949

Epoch 97: 100%|██████████| 125/125 [00:07<00:00, 16.48it/s, loss=0.256]

Epoch  97 | Train F1=0.9446 | Val F1=0.8884

Epoch 98: 100%|██████████| 125/125 [00:07<00:00, 16.06it/s, loss=0.158]

Epoch  98 | Train F1=0.9494 | Val F1=0.8960

Epoch 99: 100%|██████████| 125/125 [00:07<00:00, 15.77it/s, loss=0.367]

Epoch  99 | Train F1=0.9505 | Val F1=0.8983

Epoch 100: 100%|██████████| 125/125 [00:07<00:00, 15.78it/s, loss=0.216]

Epoch 100 | Train F1=0.9520 | Val F1=0.9019

In [66]:
test_loss, test_f1 = evaluate(
    enc,
    cla,
    test_loader,
    nn.CrossEntropyLoss(),
    device
)

print(test_loss)
print(test_f1)

0.3545351684903582
0.9056072235107422

In [69]:
px.line(history["val_f1"], title="Val F1 Score", labels={"index": "Epoch", "value": "F1 Score"})

## Experimentações

In [55]:
PATH = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\reprodução chang\\modelos\\'
for posi in range(7):
    encoders[posi].eval()
    classifs[posi].eval()
    torch.save(encoders[posi].state_dict(), PATH+'encoder'+str(posi)+'.pth')
    torch.save(classifs[posi].state_dict(), PATH+'classif'+str(posi)+'.pth')

In [13]:
PATH = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\reprodução chang\\modelos\\'
encoders = [None] * 7
classifs = [None] * 7
for posi in range(7):
    encoders[posi] = ChangEncoder()
    classifs[posi] = ChangClassifier()
    encoders[posi].load_state_dict(torch.load(PATH+'encoder'+str(posi)+'.pth'))
    classifs[posi].load_state_dict(torch.load(PATH+'classif'+str(posi)+'.pth'))
    encoders[posi].eval()
    classifs[posi].eval()

In [14]:
def testesDominios(dados):
    loss_fn = nn.CrossEntropyLoss()
    loss = np.zeros((7,8))
    acc = np.zeros((7,8))
    for posi in range(7):
        N = dados[posi].shape[0]
        X = dados[posi].iloc[:,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
        y = dados[posi].iloc[:,-3].values
        X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=1, stratify=y)
        X_train, X_val, y_train, y_val = train_test_split(
                X_train, y_train, test_size=0.1, random_state=1, stratify=y_train)
        y_test = nn.functional.one_hot(torch.tensor(y_test), num_classes=8).to(torch.float32).to(device)
        X_test = torch.tensor(X_test, dtype=torch.float32, device=device)
        for i in range(7):
            print(i,posi)
            encoders[i].eval()
            classifs[i].eval()
            y_pred = classifs[i](encoders[i](X_test))
            labels = torch.nonzero(y_test)[:,1]
            labels_pred = torch.argmax(y_pred, dim=1)
            if i==posi:
                loss[i,0] = float(loss_fn(y_pred, y_test))
                acc[i,0] = float(multiclass_f1_score(labels_pred, labels, num_classes=8))
            else:
                loss[i,posi+1] = float(loss_fn(y_pred, y_test))
                acc[i,posi+1] = float(multiclass_f1_score(labels_pred, labels, num_classes=8))
    return loss, acc

In [15]:
loss, acc = testesDominios(D)

0 0
1 0
2 0
3 0
4 0
5 0
6 0
0 1
1 1
2 1
3 1
4 1
5 1
6 1
0 2
1 2
2 2
3 2
4 2
5 2
6 2
0 3
1 3
2 3
3 3
4 3
5 3
6 3
0 4
1 4
2 4
3 4
4 4
5 4
6 4
0 5
1 5
2 5
3 5
4 5
5 5
6 5
0 6
1 6
2 6
3 6
4 6
5 6
6 6

In [16]:
df = pd.DataFrame(acc)
df.columns = ['Fonte', 'chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
df.index = ['chest', 'forearm', 'head', 'shin', 'thigh', 'upperarm', 'waist']
df = df.round(2)
for i in range(7):
    df.iloc[i,i+1] = '-'

In [17]:
cols = df.columns.tolist()
ea = np.array(cols)[[0,3,1,6,2,7,5,4]].tolist()
df = df[ea]
linhas = df.index.tolist()
ea = np.array(linhas)[[2,0,5,1,6,4,3]]
df = df.reindex(ea)

In [24]:
latex_table = df3.to_latex(
    index=True,  # To not include the DataFrame index as a column in the table
    caption="Comparison of ML Model Performance Metrics",  # The caption to appear above the table in the LaTeX document
    label="tab:model_comparison",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="l c|c c c c c c c",  # The format of the columns: left-aligned with vertical lines between them
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table)

\begin{table}[htbp]
\caption{Comparison of ML Model Performance Metrics}
\label{tab:model_comparison}
\begin{tabular}{l c|c c c c c c c}
\toprule
 & Fonte & head & chest & upperarm & forearm & waist & thigh & shin \\
\midrule
head & 0.09 & - & 0.13 & -0.01 & -0.14 & -0.28 & -0.09 & -0.07 \\
chest & 0.13 & -0.20 & - & -0.17 & -0.17 & -0.11 & -0.12 & -0.26 \\
upperarm & 0.06 & 0.03 & 0.00 & - & -0.18 & 0.03 & -0.13 & -0.15 \\
forearm & 0.10 & -0.29 & -0.29 & -0.40 & - & 0.06 & -0.29 & -0.30 \\
waist & 0.07 & -0.28 & -0.09 & -0.20 & -0.04 & - & -0.18 & -0.17 \\
thigh & 0.13 & -0.08 & -0.05 & -0.04 & -0.35 & -0.26 & - & -0.16 \\
shin & 0.06 & -0.10 & -0.12 & -0.12 & -0.28 & -0.07 & -0.14 & - \\
\bottomrule
\end{tabular}
\end{table}

In [19]:
table = np.matrix([[0.86, 0.00, 0.60, 0.51, 0.26, 0.14, 0.37, 0.23],
                   [0.94, 0.28, 0.00, 0.32, 0.25, 0.30, 0.42, 0.24],
                   [0.89, 0.47, 0.58, 0.00, 0.20, 0.18, 0.44, 0.35],
                   [0.88, 0.16, 0.12, 0.11, 0.00, 0.39, 0.12, 0.09],
                   [0.93, 0.16, 0.22, 0.05, 0.25, 0.00, 0.15, 0.02],
                   [0.94, 0.39, 0.39, 0.45, 0.05, 0.16, 0.00, 0.40],
                   [0.92, 0.06, 0.29, 0.33, 0.03, 0.09, 0.30, 0.00]])

In [20]:
df2 = pd.DataFrame(table)
df2.columns = ['Fonte', 'head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']
df2.index = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']
for i in range(7):
    df2.iloc[i,i+1] = '-'
df2

          Fonte  head chest upperarm forearm waist thigh  shin
head       0.86     -   0.6     0.51    0.26  0.14  0.37  0.23
chest      0.94  0.28     -     0.32    0.25   0.3  0.42  0.24
upperarm   0.89  0.47  0.58        -     0.2  0.18  0.44  0.35
forearm    0.88  0.16  0.12     0.11       -  0.39  0.12  0.09
waist      0.93  0.16  0.22     0.05    0.25     -  0.15  0.02
thigh      0.94  0.39  0.39     0.45    0.05  0.16     -   0.4
shin       0.92  0.06  0.29     0.33    0.03  0.09   0.3     -

In [23]:
vals = df.values
for i in range(7):
    vals[i,i+1] = 0.
diff = np.array(table-vals).astype(float)
df3 = pd.DataFrame(diff)
df3.columns = ['Fonte', 'head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']
df3.index = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']
for i in range(7):
    df3.iloc[i,i+1] = '-'
df3

          Fonte  head chest upperarm forearm waist thigh  shin
head       0.09     -  0.13    -0.01   -0.14 -0.28 -0.09 -0.07
chest      0.13  -0.2     -    -0.17   -0.17 -0.11 -0.12 -0.26
upperarm   0.06  0.03   0.0        -   -0.18  0.03 -0.13 -0.15
forearm    0.10 -0.29 -0.29     -0.4       -  0.06 -0.29  -0.3
waist      0.07 -0.28 -0.09     -0.2   -0.04     - -0.18 -0.17
thigh      0.13 -0.08 -0.05    -0.04   -0.35 -0.26     - -0.16
shin       0.06  -0.1 -0.12    -0.12   -0.28 -0.07 -0.14     -

## Treinamento de adaptação

In [69]:
dFont = D[0]
dAlvo = D[1]

N = 22100   # Vamos usar esse número mínimo de amostras por domínio
X = dFont.iloc[:N,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
y = dFont.iloc[:N,-3].values
X_train1, _, y_train1, _ = train_test_split(
    X, y, test_size=0.2, random_state=1, stratify=y)

X_train1, X_val1, y_train1, y_val1 = train_test_split(
    X_train1, y_train1, test_size=0.1, random_state=1, stratify=y_train1)
    
X = dAlvo.iloc[:N,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
y = dAlvo.iloc[:N,-3].values
X_train2, _, y_train2, _ = train_test_split(
    X, y, test_size=0.2, random_state=1, stratify=y)

X_train2, X_val2, y_train2, y_val2 = train_test_split(
    X_train2, y_train2, test_size=0.1, random_state=1, stratify=y_train2)

y_train1 = nn.functional.one_hot(torch.tensor(y_train1), num_classes=8).to(torch.float32).to(device)
y_val1 = nn.functional.one_hot(torch.tensor(y_val1), num_classes=8).to(torch.float32).to(device)
X_train1 = torch.tensor(X_train1, dtype=torch.float32, device=device)
X_val1 = torch.tensor(X_val1, dtype=torch.float32, device=device)

y_train2 = nn.functional.one_hot(torch.tensor(y_train2), num_classes=8).to(torch.float32).to(device)
y_val2 = nn.functional.one_hot(torch.tensor(y_val2), num_classes=8).to(torch.float32).to(device)
X_train2 = torch.tensor(X_train2, dtype=torch.float32, device=device)
X_val2 = torch.tensor(X_val2, dtype=torch.float32, device=device)

In [9]:
def mmd2u(x, y, c):
    n = x.shape[0]
    m = y.shape[0]
    xy = torch.vstack((x,y))
    dists = torch.cdist(xy, xy)
    k = torch.exp( (-1/(2*c)) * dists**2 )
    k_x = torch.triu(k[:n, :n], diagonal=1)
    k_y = torch.triu(k[n:, n:], diagonal=1)
    k_xy = k[:n, n:]
    mmd = 2*k_x.sum()/(n*(n-1)) + 2*k_y.sum()/(m*(m-1)) - 2*k_xy.sum()/(n*m)
    return mmd

In [189]:
emb1 = torch.randn(5,2)
emb2 = torch.randn(5,2)
print(mmd2u(emb2,emb1,1))
fig = px.scatter(x=emb1[:,0].cpu().detach().numpy(), y=emb1[:,1].cpu().detach().numpy(), width=700, height=500)
fig.add_trace(go.Scatter(x=emb2[:,0].cpu().detach().numpy(), y=emb2[:,1].cpu().detach().numpy(), mode='markers', showlegend=True))

tensor(-0.1854)

In [10]:
def sigma_median(xy):
    dists = nn.functional.pdist(xy)
    return torch.median(dists)

In [11]:
class mmdLoss(nn.Module):
    def __init__(self):
        super(mmdLoss, self).__init__()

    def forward(self, x, y, c):
        n = x.shape[0]
        m = y.shape[0]
        xy = torch.vstack((x,y))
        dists = torch.cdist(xy, xy)
        k = torch.exp( (-1/(2*c)) * dists**2 )
        k_x = torch.triu(k[:n, :n], diagonal=1)
        k_y = torch.triu(k[n:, n:], diagonal=1)
        k_xy = k[:n, n:]
        mmd = 2*k_x.sum()/(n*(n-1)) + 2*k_y.sum()/(m*(m-1)) - 2*k_xy.sum()/(n*m)
        return mmd

In [71]:
emb1 = encoders[0](X_val1)
emb2 = encoders[0](X_val2)

In [76]:
torch.cuda.empty_cache()

In [75]:
sigma = sigma_median(torch.vstack((emb1,emb2)))
c = sigma ** 2
print(c)

tensor(260.0161, device='cuda:0', grad_fn=<PowBackward0>)

In [206]:
vals = [0.01, 0.1, 1, 2, 3, 4, 5, 6, 10, 20, 50, 100, 200, 250, 300, 400, 500, 1000]
aux = np.zeros_like(vals)
for i, j in enumerate(vals):
    aux[i] = mmd2u(emb1,emb2,j).cpu().detach().numpy()

In [210]:
px.line(x=vals,y=aux, markers='lines+markers')

In [88]:
def treinoAdapt(dFont, dAlvo):
    N = 22100   # Vamos usar esse número mínimo de amostras por domínio
    X = dFont.iloc[:N,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
    y = dFont.iloc[:N,-3].values
    X_train1, _, y_train1, _ = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)
    X_train1, X_val1, y_train1, y_val1 = train_test_split(
        X_train1, y_train1, test_size=0.1, random_state=1, stratify=y_train1)
        
    X = dAlvo.iloc[:N,:450].values.reshape(N,3,150) / 30   # Normalizando para a faixa de -1 a 1 aproximadamente pela divisão por 30
    y = dAlvo.iloc[:N,-3].values
    X_train2, _, y_train2, _ = train_test_split(
        X, y, test_size=0.2, random_state=1, stratify=y)
    X_train2, X_val2, y_train2, y_val2 = train_test_split(
        X_train2, y_train2, test_size=0.1, random_state=1, stratify=y_train2)

    y_train1 = nn.functional.one_hot(torch.tensor(y_train1), num_classes=8).to(torch.float32).to(device)
    y_val1 = nn.functional.one_hot(torch.tensor(y_val1), num_classes=8).to(torch.float32).to(device)
    X_train1 = torch.tensor(X_train1, dtype=torch.float32, device=device).detach()
    X_val1 = torch.tensor(X_val1, dtype=torch.float32, device=device).detach()
    
    y_train2 = nn.functional.one_hot(torch.tensor(y_train2), num_classes=8).to(torch.float32).to(device)
    y_val2 = nn.functional.one_hot(torch.tensor(y_val2), num_classes=8).to(torch.float32).to(device)
    X_train2 = torch.tensor(X_train2, dtype=torch.float32, device=device).detach()
    X_val2 = torch.tensor(X_val2, dtype=torch.float32, device=device).detach()

    encoder = ChangEncoder().to(device)
    classif = ChangClassifier().to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimizer1 = optim.Adam(list(encoder.parameters()) + list(classif.parameters()), lr=0.001)
    optimizer2 = optim.Adam(encoder.parameters(), lr=0.001)
    
    n_epochs = 20   # number of epochs to run
    batch_size = 125  # size of each batch
    batch_start = torch.arange(0, len(X_train1), batch_size)
    trainLoss = []
    trainAcc = []
    valLoss = []
    valAcc = []

    for epoch in range(n_epochs):
        encoder.train()
        classif.train()
        with tqdm(batch_start, unit="batch", mininterval=0, disable=False) as bar:
            bar.set_description(f"Epoch {epoch}")
            for start in bar:
                X_batch1 = X_train1[start:start+batch_size,:,:]
                X_batch2 = X_train2[start:start+batch_size,:,:]
                y_batch1 = y_train1[start:start+batch_size,:]
                # Passo de treinamento com loss de classificação
                y_pred = classif(encoder(X_batch1))
                loss1 = loss_fn(y_pred, y_batch1)
                optimizer1.zero_grad()
                loss1.backward()
                optimizer1.step()
                # Passo de treinamento com loss mmd
                emb1 = encoder(X_batch1)
                emb2 = encoder(X_batch2)
                loss2 = 0
                for i in vals: 
                    loss2 += mmd2u(emb1,emb2,i)
                optimizer2.zero_grad()
                loss2.backward()
                optimizer2.step()
                # print progress
                bar.set_postfix(loss=float(loss1))
        encoder.eval()
        classif.eval()
        y_pred = classif(encoder(X_val1))
        valLoss.append(float(loss_fn(y_pred, y_val1)))
        labels = torch.nonzero(y_val1)[:,1]
        labels_pred = torch.argmax(y_pred, dim=1)
        valAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))
        y_pred = classif(encoder(X_train1))
        trainLoss.append(float(loss_fn(y_pred, y_train1)))
        labels = torch.nonzero(y_train1)[:,1]
        labels_pred = torch.argmax(y_pred, dim=1)
        trainAcc.append(float(multiclass_f1_score(labels_pred, labels, num_classes=8)))

    fig = go.Figure()
    fig.add_trace(go.Scatter(y=valLoss, mode="lines", showlegend=True, name='validação'))
    fig.add_trace(go.Scatter(y=trainLoss, mode="lines", showlegend=True, name='treino'))
    fig.show()

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(y=valAcc, mode="lines", showlegend=True, name='validação'))
    fig2.add_trace(go.Scatter(y=trainAcc, mode="lines", showlegend=True, name='treino'))
    fig2.show()
    return encoder, classif

In [89]:
encoder, classif = treinoAdapt(dFont, dAlvo)

Epoch 0: 100%|██████████| 128/128 [00:07<00:00, 17.13batch/s, loss=1.47]
Epoch 1: 100%|██████████| 128/128 [00:10<00:00, 12.37batch/s, loss=1.12]
Epoch 2: 100%|██████████| 128/128 [00:13<00:00,  9.18batch/s, loss=0.913]
Epoch 3: 100%|██████████| 128/128 [00:14<00:00,  8.66batch/s, loss=0.777]
Epoch 4: 100%|██████████| 128/128 [00:13<00:00,  9.32batch/s, loss=0.636]
Epoch 5: 100%|██████████| 128/128 [00:13<00:00,  9.43batch/s, loss=0.693]
Epoch 6: 100%|██████████| 128/128 [00:13<00:00,  9.15batch/s, loss=0.869]
Epoch 7: 100%|██████████| 128/128 [00:13<00:00,  9.38batch/s, loss=0.702]
Epoch 8: 100%|██████████| 128/128 [00:13<00:00,  9.62batch/s, loss=0.677]
Epoch 9: 100%|██████████| 128/128 [00:13<00:00,  9.82batch/s, loss=0.769]
Epoch 10: 100%|██████████| 128/128 [00:09<00:00, 12.91batch/s, loss=0.579]
Epoch 11: 100%|██████████| 128/128 [00:09<00:00, 13.01batch/s, loss=0.667]
Epoch 12: 100%|██████████| 128/128 [00:09<00:00, 12.96batch/s, loss=0.671]
Epoch 13: 100%|██████████| 128/128 [00:09<00:00, 13.17batch/s, loss=0.645]
Epoch 14: 100%|██████████| 128/128 [00:10<00:00, 12.69batch/s, loss=0.614]
Epoch 15: 100%|██████████| 128/128 [00:13<00:00,  9.53batch/s, loss=0.534]
Epoch 16: 100%|██████████| 128/128 [00:13<00:00,  9.29batch/s, loss=0.527]
Epoch 17: 100%|██████████| 128/128 [00:13<00:00,  9.24batch/s, loss=0.645]
Epoch 18: 100%|██████████| 128/128 [00:13<00:00,  9.19batch/s, loss=0.639]
Epoch 19: 100%|██████████| 128/128 [00:13<00:00,  9.33batch/s, loss=0.572]

In [90]:
PATH = 'C:\\Meu Drive\\Doutorado Unicamp\\Projeto\\reprodução chang\\modelos\\'
encoder.eval()
classif.eval()
torch.save(encoder.state_dict(), PATH+'encoderAdpt.pth')
torch.save(classif.state_dict(), PATH+'classifAdpt.pth')

In [92]:
encoder = ChangEncoder()
classif = ChangClassifier()
encoder.load_state_dict(torch.load(PATH+'encoderAdpt.pth'))
classif.load_state_dict(torch.load(PATH+'classifAdpt.pth'))
encoder.eval()
classif.eval()

ChangClassifier(
  (densa): Linear(in_features=100, out_features=8, bias=True)
)

# Benchmarks de classificação com features

## Espectro

In [ ]:
def spectral_energy(X):
    N, T, C = X.shape
    energy = np.zeros((N, T//2, C))
    for i in range(N):
        for j in range(C):
            fft = np.fft.fft(X[i,:,j])
            energy[i,:,j] = np.abs(fft[:T//2])**2/T
    return energy

In [38]:
S = spectral_energy(Xdata)
S = S.reshape(S.shape[0], -1, order='F')

In [46]:
inds = ydata[:,0]==0
X_train, X_test, y_train, y_test = train_test_split(
    S[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
f1 = f1_score(y_test, y_pred, average='macro')
print(f"F1 Score: {f1:.4f}")

F1 Score: 0.8776

In [53]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        S[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(S[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:23<00:00,  3.39s/it]

In [ ]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          73    73     42        20       36     51     38    12
chest         87    27     87        34       28     30     40    23
upperarm      83    19     35        83       24     11     29    43
forearm       80    25     35        33       80     35     28    20
waist         88    30     13         4       21     88     13     1
thigh         91    32     38        36       35     28     91    23
shin          89     8     26        32       11      6     18    89

In [56]:
data = {
    'Treino': [84, 90, 88, 84, 91, 90, 91],
    'head': ['-', 46, 46, 30, 38, 41, 18],
    'chest': [52, '-', 64, 32, 29, 34, 34],
    'upperarm': [51, 43, '-', 39, 20, 39, 39],
    'forearm': [25, 38, 29, '-', 27, 33, 28],
    'waist': [29, 37, 18, 24, '-', 39, 21],
    'thigh': [44, 46, 62, 35, 28, '-', 38],
    'shin': [22, 35, 46, 28, 17, 51, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          84    -    52       51      25    29    44   22
chest         90   46     -       43      38    37    46   35
upperarm      88   46    64        -      29    18    62   46
forearm       84   30    32       39       -    24    35   28
waist         91   38    29       20      27     -    28   17
thigh         90   41    34       39      33    39     -   51
shin          91   18    34       39      28    21    38    -

## Frequência Fundamental, Energia e Valor Médio

In [ ]:
T0 = []
for x in tqdm(Xdata):
    x = x - np.mean(x, axis=0, keepdims=True)
    cor = [np.sum(x*x, axis=0)]
    for i in range(1, x.shape[0]):
        cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
    cor = np.array(cor).sum(axis=1)
    peaks, _ = find_peaks(cor)
    if len(peaks) > 0:
        T0.append(peaks[cor[peaks].argmax()])
    else:
        T0.append(0)
T0 = np.array(T0).reshape(-1, 1)

100%|██████████| 151486/151486 [06:31<00:00, 387.41it/s]

In [215]:
# Vamos salvar os valores de T0 em um arquivo CSV para análise posterior
T0_df = pd.DataFrame(T0, columns=['T0'])
T0_df.to_csv('T0_values.csv', index=False)

In [8]:
# Vamos carregar os valores de T0 de volta do arquivo CSV para garantir que eles foram salvos corretamente
T0_loaded = pd.read_csv('T0_values.csv')
T0 = T0_loaded['T0'].values

In [ ]:
T0 = np.array(T0)
inds = (ydata[:,1]==7)
px.scatter(T0[inds])

In [ ]:
Xs = Xdata[inds]
x = Xs[5620,:,:]
x = x - np.mean(x, axis=0, keepdims=True)
cor = [np.sum(x*x, axis=0)]
for i in range(1, x.shape[0]):
    cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
cor = np.array(cor)
peaks, _ = find_peaks(cor.sum(axis=1), distance=10)
fig = px.line(cor.sum(axis=1))
fig.add_trace(go.Scatter(x=peaks, y=cor.sum(axis=1)[peaks], mode='markers', name='Peaks'))
fig.show()

In [106]:
Vm = np.mean(Xdata, axis=1)
Xm = Xdata - np.mean(Xdata, axis=1, keepdims=True)
En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

In [167]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        Vm[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(Vm[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  6.49it/s]

In [168]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          55    55     25        12       19     19     22    10
chest         76    14     76        12       17     26     22    11
upperarm      66    12     16        66        6     14     18    27
forearm       70    13      3         2       70     13      5     0
waist         73    11     13         2       16     73     14     2
thigh         81    21     20        19        4     13     81    18
shin          79     8     22        20        3     11     14    79

In [176]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        En[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(En[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:00<00:00, 10.83it/s]

In [177]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          40    40     35        41       37     34     29    20
chest         43    34     43        36       35     38     24    15
upperarm      44    38     39        44       38     37     33    25
forearm       41    36     38        40       41     37     32    28
waist         41    32     37        38       37     41     32    21
thigh         40    27     30        35       31     33     40    35
shin          41    18     18        23       21     19     35    41

In [180]:
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        T0[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(T0[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:00<00:00,  7.45it/s]

In [181]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          31    31     23        22       24     25     21    21
chest         30    27     30        26       29     31     30    30
upperarm      31    22     27        31       31     29     29    30
forearm       31    23     28        29       31     30     28    27
waist         37    29     31        33       32     37     31    34
thigh         35    22     29        29       28     32     35    34
shin          41    24     30        32       32     34     38    41

In [182]:
feats = np.concatenate((Vm, En, T0), axis=1)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:01<00:00,  5.84it/s]

In [183]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          71    71     56        50       47     46     46    37
chest         79    54     79        49       45     53     37    25
upperarm      76    42     56        76       47     39     52    42
forearm       74    41     43        46       74     47     42    31
waist         79    49     56        43       47     79     40    28
thigh         76    40     43        46       39     43     76    53
shin          74    20     34        38       30     30     52    74

In [217]:
feats = np.concatenate((En, T0), axis=1)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:00<00:00,  8.73it/s]

In [218]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          61    61     51        55       51     46     41    34
chest         63    53     63        50       47     53     36    27
upperarm      63    46     52        63       55     47     48    38
forearm       60    47     52        57       60     50     48    39
waist         60    51     56        53       49     60     42    30
thigh         60    35     43        50       45     42     60    54
shin          63    21     28        35       33     29     51    63

In [203]:
data = {
    'Treino': [84, 90, 88, 84, 91, 90, 91],
    'head': ['-', 46, 46, 30, 38, 41, 18],
    'chest': [52, '-', 64, 32, 29, 34, 34],
    'upperarm': [51, 43, '-', 39, 20, 39, 39],
    'forearm': [25, 38, 29, '-', 27, 33, 28],
    'waist': [29, 37, 18, 24, '-', 39, 21],
    'thigh': [44, 46, 62, 35, 28, '-', 38],
    'shin': [22, 35, 46, 28, 17, 51, '-']
}

index_labels = ['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin']

df = pd.DataFrame(data, index=index_labels)

display(df)

          Treino head chest upperarm forearm waist thigh shin
head          84    -    52       51      25    29    44   22
chest         90   46     -       43      38    37    46   35
upperarm      88   46    64        -      29    18    62   46
forearm       84   30    32       39       -    24    35   28
waist         91   38    29       20      27     -    28   17
thigh         90   41    34       39      33    39     -   51
shin          91   18    34       39      28    21    38    -

## Modelo harmônico

In [5]:
def harmonic_score(T, peaks, cor, tol=2):
    score = 0
    for k in range(1,8):
        target = k*T
        d = np.abs(peaks-target)
        if np.min(d)<=tol:
            p = peaks[np.argmin(d)]
            score += cor[p]
    return score

In [78]:
sos = butter(N=6, Wn=10, btype='lp', fs=50, output='sos')
Xf = np.swapaxes(sosfiltfilt(sos, np.swapaxes(Xdata, 1, 2)), 1, 2)
T0 = []
for x in tqdm(Xf):
    x = x - np.mean(x, axis=0, keepdims=True)
    cor = [np.sum(x*x, axis=0)]
    for i in range(1, x.shape[0]):
        cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
    cor = np.array(cor).sum(axis=1)
    peaks, _ = find_peaks(cor)
    if len(peaks) > 0:
        scores = np.array([harmonic_score(T, peaks, cor) for T in peaks])
        T0.append(peaks[scores.argmax()])
    else:
        T0.append(0)
T0 = np.array(T0).reshape(-1, 1)

100%|██████████| 151486/151486 [02:56<00:00, 857.12it/s]

In [6]:
T0_loaded = pd.read_csv('T0_values.csv')
T0 = T0_loaded['T0'].values.reshape(-1, 1)
Vm = np.mean(Xdata, axis=1)
Xm = Xdata - np.mean(Xdata, axis=1, keepdims=True)
En = np.sum(Xm*Xm, axis=(1,2)).reshape(-1, 1)

In [ ]:
T2 = np.copy(T0)
EnInds = (En.ravel()>1)
for u in range(14):
    for act in [0, 1, 4, 7]:
        inds = (ydata[:,1]==act) & (yu==u) & EnInds
        aux = T2[inds]
        km = KMeans(n_clusters=2, init = 'random')
        labels = km.fit_predict(aux.reshape(-1,1))
        if np.mean(aux[labels==0]) > np.mean(aux[labels==1]):
            aux[labels==1] = aux[labels==1] * 2
        else:
            aux[labels==0] = aux[labels==0] * 2
        T2[inds] = aux

In [8]:
feats = np.concatenate((En, T2), axis=1)
baselinef1 = np.zeros((7,7))
for i in tqdm(range(7)):
    inds = ydata[:,0]==i
    X_train, X_test, y_train, y_test = train_test_split(
        feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    for j in range(7):
        inds = ydata[:,0]==j
        X_train, X_test, y_train, y_test = train_test_split(feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
        y_pred = neigh.predict(X_test)
        f1 = f1_score(y_test, y_pred, average='macro')
        baselinef1[i,j] = f1

100%|██████████| 7/7 [00:00<00:00,  7.07it/s]

In [9]:
df = pd.DataFrame((baselinef1*100).astype(int), columns=posis, index=posis)
df.insert(0, 'Treino', (baselinef1.diagonal()*100).astype(int))
df = df.reindex(index=['head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df = df.reindex(columns=['Treino','head', 'chest', 'upperarm', 'forearm', 'waist', 'thigh', 'shin'])
df

          Treino  head  chest  upperarm  forearm  waist  thigh  shin
head          62    62     51        54       52     45     41    35
chest         63    51     63        51       47     53     39    32
upperarm      63    53     55        63       56     49     46    43
forearm       62    54     54        57       62     48     47    44
waist         59    49     55        50       48     59     48    38
thigh         60    42     47        48       44     47     60    52
shin          62    28     33        33       34     32     51    62

In [12]:
i, j = 3, 0
inds = ydata[:,0]==i
X_train, X_test, y_train, y_test = train_test_split(
    feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
inds = ydata[:,0]==j
X_train, X_test, y_train, y_test = train_test_split(feats[inds], ydata[inds,1], test_size=0.2, random_state=1, stratify=ydata[inds,1])
y_pred = neigh.predict(X_test)
z = confusion_matrix(y_test, y_pred)
fig = px.imshow(z, x=actis, y=actis, text_auto=True, labels=dict(x="Estimado", y="Referência", color="Quantidade"),
    width=700, height=500, color_continuous_scale='Blues', title="Treino: {}, Teste: {}".format(posis[i], posis[j]))
fig.update_yaxes(autorange="reversed")
fig.show()

In [ ]:
inds = (ydata[:,1]==1) & (yu==7)
px.scatter(T2[inds].ravel()/50)

In [ ]:
inds = (ydata[:,1]==7)
px.histogram(En[inds].ravel())

In [ ]:
x = Xdata[inds][104]
x = x - np.mean(x, axis=0, keepdims=True)
cor = [np.sum(x*x, axis=0)]
for i in range(1, x.shape[0]):
    cor.append(np.sum(x[i:,:]*x[:-i,:], axis=0))
cor = np.array(cor).sum(axis=1)
peaks, _ = find_peaks(cor)
scores = np.array([harmonic_score(T, peaks, cor) for T in peaks])
print(peaks, scores)
px.line(cor)

## Ajustes

In [23]:
inds = (ydata[:,1]==1) & (yu==7)
i = 50
J = 150
fs = 50
L = 4
f0est = []
f0s = np.arange(0.3, 2, 0.001)
for janela in Xdata[inds]:
    janela = janela - np.mean(janela, axis=0, keepdims=True)
    erro = []
    for f0 in f0s:
        arg = np.outer(np.arange(J)/fs, np.arange(1,L+1)*2*np.pi*f0)
        C = np.cos(arg)
        S = np.sin(arg)
        theta = np.hstack((C, S))
        coefs = np.linalg.pinv(theta).dot(janela)
        recon = theta.dot(coefs)
        erro.append(np.sqrt(np.sum((janela - recon)**2)))
    f0est.append(f0s[np.argmin(erro)])